### ISSUE TITLE
Improvements to attachment functions

### ISSUE THREAD

**Issue by MasterOdin** [py-pdf/pypdf#1047]
From https://github.com/py-pdf/PyPDF2/discussions/1046, the following may be useful to useful to cherry-pick if possible:
> Improved embedded file handling (Rüdiger Jungbeck, rjungbeck)
Allow attachment of more than 1 file with PdfFileWriter.addAttachment()
Allow listing of attachments in PdfFileReader.listAttachments()
Allow retrival of attachment PdfFileReader.getAttachment()

Looking at the docs here, I think all of this would be new functionality, with probably the most useful being `listAttachments` and `getAttachment`? I'm not sure about the alteration to `addAttachment`, but perhaps make it a new function called `add_attachments`?

**Comment by MartinThoma** [comment]
Could we make an attachment property exposing a dictionary (or something that looks like it)? How does the signature of getAttachments look like?

**Comment by MasterOdin** [comment]
The [relevant code](https://github.com/Tristan79/PyPDF2/blob/f23edb3acb3b7dc59bb7ebd0219d542beabf69a0/PyPDF2/pdf.py#L1366-L1374):

```python
    def getAttachment(self, name):
        for i in range (0, len(self.trailer["/Root"]["/Names"]["/EmbeddedFiles"]["/Names"]), 2):
            if self.trailer["/Root"]["/Names"]["/EmbeddedFiles"]["/Names"][i+1].getObject()["/F"]==name:
                return self.trailer["/Root"]["/Names"]["/EmbeddedFiles"]["/Names"][i+1].getObject()["/EF"]["/F"].getObject().getData()

    def listAttachments(self):

        for i in range (0, len(self.trailer["/Root"]["/Names"]["/EmbeddedFiles"]["/Names"]), 2):
            yield self.trailer["/Root"]["/Names"]["/EmbeddedFiles"]["/Names"][i+1].getObject()["/F"]
```

**Comment by MartinThoma** [comment]
https://github.com/Tristan79/PyPDF2/commit/02e234253d8da97946c8f5168ed339e791d9621d seems to be the commit. I'll ask that user if they want to open a PR (so that we attribute this well in the commit history)

**Comment by MartinThoma** [comment]
Related: https://github.com/py-pdf/PyPDF2/pull/440/files

**Comment by MartinThoma** [comment]
@kevinl95 Would you be interested in leading the implementation to this new change? Your PR #440 already goes into that direction, but due to the changes we made you would need to rebase (and use other method names / maybe a [property](https://stackoverflow.com/q/17330160/562769))
