### ISSUE TITLE
PI: Introduce garbage collection to remove unreferenced resources for file size reduction

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1116]
## Explanation

PDF documents can contain objects which are not referenced anywhere in the document. Those objects could be deleted without affecting how the document looks like for file size reduction.

I have seen this feature in mutools: https://mupdf.com/docs/manual-mutool-clean.html and qpdf: https://qpdf.readthedocs.io/en/stable/cli.html#option-remove-unreferenced-resources

## How would your feature be used?

```python
from PyPDF2 import PdfReader, PdfWriter

reader = PdfReader("example.pdf")
writer = PdfWriter()

for page in reader.pages():
    page.remove_unreferenced_resources()
    writer.add_page(page)

with open("out.pdf", "wb") as fp:
    writer.write(fp)
```

**Comment by pubpub-zz** [comment]
The way append works, it pulls/clones only referenced objects. I think this issue should be close unless you have a specific test case to analyse

**Comment by xilopaint** [comment]
How common are unreferenced objects in PDFs?

**Comment by pubpub-zz** [comment]
2 cases I've identified:
   * you may meet this situation with revised PDF : then changed object have a new generation but elder objects are still present.
   * when you append a page, you may have properties you will not be interested in (eg : the articles which were pulling lots of pages even if not referenced in the page tree)
