### ISSUE TITLE
Annotations free text chinese characters display blank

### ISSUE THREAD

**Issue by 123woscc** [py-pdf/pypdf#1399]
When creating an annotation with Chinese characters, they are not shown.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.19041-SP0

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.5
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfReader, PdfWriter
from PyPDF2.generic import AnnotationBuilder

# Fill the writer with the pages you want
pdf_path = 'demo.pdf'
reader = PdfReader(pdf_path)
page = reader.pages[0]
writer = PdfWriter()
writer.add_page(page)

# Create the annotation and add it
annotation = AnnotationBuilder.free_text(
    "Hello World\nThis is the 测试!",
    rect=(50, 550, 200, 650),
    font="Arial",
    bold=True,
    italic=True,
    font_size="20pt",
    font_color="00ff00",
    border_color="0000ff",
    background_color="cdcdcd",
)
writer.add_annotation(page_number=0, annotation=annotation)

# Write the annotated file to disk
with open("annotated-pdf.pdf", "wb") as fp:
    writer.write(fp)
```

PDF file: 
[demo.pdf](https://github.com/py-pdf/PyPDF2/files/9806984/demo.pdf)

Actual results: the words "测试" are not displayed normally.
![image](https://user-images.githubusercontent.com/13806929/196350475-a168a334-3703-4e23-845d-01b5622c3af4.png)

Question：
Is it a font problem? Is there an interface to set the Chinese font?

**Comment by 123woscc** [comment]
I have tried setting other fonts that support Chinese, like simsum, simhei, but it still doesn't work.

**Comment by vphan6896** [comment]
You may have discovered it already in https://github.com/py-pdf/PyPDF2/blob/main/PyPDF2/generic/_annotations.py#L62.
I found this SO post as well: https://stackoverflow.com/questions/69142800/pypdf2-decoding-issue-when-adding-annotations-in-chinese-characters-with-addjs

I'm not sure how to see what fonts are available to pypdf2. Efforts to change the annotation font type were unsuccessful as you said.

**Comment by MartinThoma** [comment]
I don't know what the issue is and how to resolve it. But as a small reminder: It could be that the issue is not with PyPDF2 or the generated PDF file, but with the viewer not supporting a feature. Which viewer(s) did you try?

**Comment by nero-dv** [comment]
Can you try converting the string to a unicode type string? I'm not 100% positive whether or not the annotations are in ASCII, but if they then you will likely not see support for Chinese characters.

**Comment by MartinThoma** [comment]
Literal strings are unicode by default in Python 3.

**Comment by Louis-de-Bontin** [comment]
I have a similar problem trying to fill forms with PyPDF2.
Latin's char are displayed without any problem, but thai, arabic, and probably others seems to be displayed in white. When I try to fill the form by hand on Acrobat or Foxit, the foreign characters are displayed, but not when I fill the form on Chrome, or any browser, or with PyPDF2 of course.

**Comment by pubpub-zz** [comment]
@123woscc 
I've rerun the test with the latest version and the result is as expected:
![image](https://user-images.githubusercontent.com/4083478/224503089-b0460ac1-393a-4f79-8666-0c2d70d1d3fa.png)

be carefull to uninstall PyPDF2 and install pypdf instead. 

@Louis-de-Bontin 
I will close this issue as fixed. Fell free to open a new one with your inputs
