### ISSUE TITLE
Wrong field names when dot in names

### ISSUE THREAD

**Issue by PhunkyBob** [py-pdf/pypdf#1468]
I would like to retrieve all elements of a PDF form and display for each element it's content. 
When I read fields having a "." in its name, the "key" returned is only the last part of the key, and the value is the value of the last element having this (wrong) key.

## Environment
Windows 11 (Windows-10-10.0.22623-SP0)
Python 3.10
pypdf 3.2.0 / PyPDF2-2.11.2

## Code + PDF
I have a PDF file with the following fields: 
- customer.name
- customer.lastname
- other_field
- company.name

![pdf](https://i.imgur.com/0uFCDRj.png)

[fields_with_dots.pdf](https://github.com/py-pdf/PyPDF2/files/10142389/fields_with_dots.pdf)

I want to get all fields and the corresponding values. 
```python
from PyPDF2 import PdfFileReader

if __name__ == "__main__":
    pdf_file_name = "fields_with_dots.pdf"
    with open(pdf_file_name, "rb") as pdfobject:
        pdf = PdfFileReader(pdfobject)
        fields = pdf.getFormTextFields()
        for k, v in fields.items():
            print(f"{k:32} : {v}")
```

### What I expected
```
customer.name               : My Name
customer.lastname         : My Lastname
other_field                      : Hello world!
company.name               : My company
```
### What the result is
```
name                             : My company
lastname                         : My Lastname
other_field                      : Hello world!
```
"customer.name" is identified as "name". "company.name" is also identified as "name". 
The value is the latest found in document : "My Company".
--> value for "customer.name" is lost.

**Comment by MartinThoma** [comment]
Of course. It's the same software in the end. But in `pypdf` the development will continue and the issue will eventually be resolved.

**Comment by pubpub-zz** [comment]
@PhunkyBob,
I've implemented the handling of hierarchical fields, you will have to modify your code to add a `true` parameter to `get_form_text_fields` to get the fully_qualified_name

**Comment by PhunkyBob** [comment]
Thank you.
How can I test it?

**Comment by pubpub-zz** [comment]
> Thank you.
> How can I test it?
> 

Yes you can load the files from the PR
It is not yet merged as waiting for adding test

**Comment by PhunkyBob** [comment]
The result with your `hierachical_fields` brach: 
```
customer.name                    : My Name
customer.lastname                : My Lastname
other_field                      : Hello world!
company.name                     : My company
```
-> it's what I expected!

Thank you!
I hope this will be merged soon.

**Comment by ahmedshabib** [comment]
This still has some issues. 

if I use get_fields, it has wrong entries.

**Comment by ahmedshabib** [comment]
> @PhunkyBob, I've implemented the handling of hierarchical fields, you will have to modify your code to add a `true` parameter to `get_form_text_fields` to get the fully_qualified_name

I checked your PR, and tried it locally, if I use `get_fields` , this gives me all of the keys now, but still has some stray keys.

**Comment by pubpub-zz** [comment]
> I checked your PR, and tried it locally, if I use `get_fields` , this gives me all of the keys now, but still has some stray keys.

@ahmedshabib 
Can you provide an pdf example withe "stray keys"?
