### ISSUE TITLE
Extracting text doesn't work for cropped boxes

### ISSUE THREAD

**Issue by aster94** [py-pdf/pypdf#1508]
I am trying to read a few boxes from a nested pdf.
My approach is to crop only these three boxes, save them as a temp file and read them.
But when I try to read these boxes I don't get nothing or I get the whole pdf (as if I haven't cutted it)
I can see from the temp file that the cutting went good

## Environment

python (miniconda) 3.9.15
pypdf2 2.11.1

## Code + PDF

```python
file_path = "example.pdf"
temp_path = "temp.pdf"

from PyPDF2 import PdfReader, PdfWriter
import os
from copy import copy

def crop(PAGE, LEFT, TOP, RIGHT, BOTTOM):
    # pyPDF2 start from the bottom left
    page_x, page_y = PAGE.cropBox.getUpperLeft()

    # convert pyPDF2.FloatObjects into floats
    upper_left = [page_x.as_numeric(), page_y.as_numeric()]

    # find new margins
    new_upper_left  = (upper_left[0] + LEFT, upper_left[1] - TOP)
    new_lower_right = (upper_left[0] + RIGHT, upper_left[1] - BOTTOM)

    #crop
    PAGE.cropbox.upper_left = new_upper_left
    PAGE.cropbox.lower_right = new_lower_right

def read_pdf(FILE):
    input = PdfReader(FILE)
    output = []

    month_page_num = 0
    employee_page_num = 1
    salary_page_num = 2

    tot_pages = len(input.pages)
    #last_page = int(tot_pages/2) # do not mind about this
    last_page = 1
    print('Pages in PDF: ' + str(tot_pages))

    for page in range(last_page):
        temp = PdfWriter()

        # Remove temp file
        if os.path.exists(temp_path):
            os.remove(temp_path)

        print('Working on page: ' + str(page+1))

        # Month
        month_page = copy(input.pages[page])
        crop(month_page, 360, 60, 450, 75)
        temp.add_page(month_page)

        # Employee
        employee_page = copy(input.pages[page])
        crop(employee_page, 365, 108, 490, 124)
        temp.add_page(employee_page)

        # Salary
        salary_page = copy(input.pages[page])
        crop(salary_page, 378, 698, 448, 707)
        temp.add_page(salary_page)

        with open(temp_path, "wb") as pdf:
            temp.write(pdf)

        # extracting text from pages
        raw = PdfReader(temp_path)
        output.append({
            'month': raw.pages[month_page_num].extractText(),
            'employee': raw.pages[employee_page_num].extractText(),
            'salary': raw.pages[salary_page_num].extractText()
        })

    return output

data = read_pdf(file_path)
print(data)

```

[example.pdf](https://github.com/py-pdf/PyPDF2/files/10257588/example.pdf)
[temp.pdf](https://github.com/py-pdf/PyPDF2/files/10257620/temp.pdf)

**Comment by aster94** [comment]
ok, honestly, I am a little confused. From the docs of the visitor function:
function to be called when extracting some text at some position. It has
five arguments: text, current transformation matrix, text matrix,
font-dictionary and font-size. The font-dictionary may be None in case of
unknown fonts. If not None it may e.g. contain key “/BaseFont” with value
“/Arial,Bold”.

So since I am not applying any matrix, nor i know the font size and type,
this function should be something like this:
def visitor_body(text, cm, tm, fontDict, fontSize):
    y = tm[5]
    x = ???
    if y > 50 and y < 720 and x > 50 and x < 600:
        parts.append(text)

But what is "y = tm[5]"? and how could I also provide x coordinates?

**Comment by pubpub-zz** [comment]
Tm matrix is the matrix which provide the transformation to text coordinates. The Tm[4]/Tm[5] provide actually the position of the text (Tm[4] horizontal, Tm[5] vertical). the reference is at lower left and increase to up/right.

**Comment by aster94** [comment]
I wasn't able to find this anywhere in the docs 🤷🏻‍♂️
