### ISSUE TITLE
could not use PdfFileReader in 3.0.0

### ISSUE THREAD

**Issue by arumugam-shanmugavelayutham** [py-pdf/pypdf#1514]
getting error
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.

**Comment by MartinThoma** [comment]
That is the point. Please read the Changelog: https://github.com/py-pdf/pypdf/blob/main/CHANGELOG.md
