### ISSUE TITLE
Can't add outline

### ISSUE THREAD

**Issue by bakajikara** [py-pdf/pypdf#1518]
Outlines can no longer be added in version 3 or higher. The generated file has no bookmarks.

## Environment

Windows 11

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader, PdfWriter

writer = PdfWriter()
reader = PdfReader(open("test.pdf", "rb"))

# copy original pdf
writer.clone_document_from_reader(reader)

# add bookmark
writer.add_outline_item("Page 1", 0)
writer.add_outline_item("Page 2", 1)

# generate pdf
outputFileName = "test_bookmarked.pdf"
with open(outputFileName, "wb") as o:
    writer.write(o)

```

This results in the following PDF:

[test_bookmarked.pdf](https://github.com/py-pdf/pypdf/files/10303954/test_bookmarked.pdf)

As you can see, the PDF does not have bookmarks. It should have bookmarks.

**Comment by MartinThoma** [comment]
Thank you for reporting the issue :pray:

**Comment by MartinThoma** [comment]
As a quick-fix:

If you replace `writer.clone_document_from_reader(reader)`

by

```
for page in reader.pages:
    writer.add_page(page)
```

it works. I'll add a test this week that shows the issue.

**Comment by MartinThoma** [comment]
@pubpub-zz You might be interested in this test: https://github.com/py-pdf/pypdf/commit/cfed01f502afd1af7ed331b32ee84ddd531f9e8a

**Comment by pubpub-zz** [comment]
PR in progress
