### ISSUE TITLE
Merging pdfs seems to strip out the text properties on form fillable boxes - font choice is reset

### ISSUE THREAD

**Issue by DoNotResuscitate** [py-pdf/pypdf#1538]
Merging pdfs seems to strip out the text properties on form fillable boxes - font choice is reset for example. 

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf.__version__)"
3.2.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfMerger

def merge_pdfs(input_pdfs: list, output_pdf_path: str):
    merger = PdfMerger()

    for pdf in input_pdfs:
        merger.append(pdf)

    merger.write(output_pdf_path)
    merger.close()
```

PDFs:
[pdfa.pdf](https://github.com/py-pdf/pypdf/files/10367412/pdfa.pdf)
[pdfb.pdf](https://github.com/py-pdf/pypdf/files/10367413/pdfb.pdf)
[merge.pdf](https://github.com/py-pdf/pypdf/files/10367414/merge.pdf)

**Comment by DoNotResuscitate** [comment]
Font is set to Crimson Pro in both pdf a and b, while the merged result has it set to Arial.

**Comment by DoNotResuscitate** [comment]
Also if you're merging 2 PDFs that have annotations(form fillable boxes) with the same names (e.g. Item1) then the appended pages will copy the same values from the first PDF. The names of the annotation boxes should be modified in a way such that the data is kept when merging the pdfs.

**Comment by pubpub-zz** [comment]
@DoNotResuscitate 
I've added function to add a top field that will allow to access fields with same names. Merging has also been enhance to handle that (be careful to use PdfWriter and no more PdfMerger)
Can you try the PR?
