### ISSUE TITLE
Enable image compression

### ISSUE THREAD

**Issue by finevine** [py-pdf/pypdf#1546]
## Explanation

I want to replace images in a pdf with compressed ones.
Gettings the images and saving them to disk work like a charm with the example in doc.
But I cannot change them in the pdf

## Code Example

How would your feature be used?

```python
from pypdf import PdfReader, PdfWriter
reader = PdfReader(input_file_path, strict=False)
for page in reader.pages:
        page.images = [compress(image_file_object) for image_file_object in page.images]
        writer.add_page(page)
...  # your new feature in action!
```

I have found a bunch of code that aimed at coding this feature:
- https://arunmozhi.in/2019/01/29/replacing-image-in-a-pdf-with-python/
- https://pypi.org/project/pdfminify/

but it doesn't work as expected.

**Comment by MartinThoma** [comment]
@pubpub-zz Running the following code compresses all content streams with [DEFLATE](https://en.wikipedia.org/wiki/DEFLATE), including the images, right?

```python
from pypdf import PdfReader, PdfWriter

reader = PdfReader("example.pdf")
writer = PdfWriter()

for page in reader.pages:
    page.compress_content_streams()  # This is CPU intensive!
    writer.add_page(page)

with open("out.pdf", "wb") as f:
    writer.write(f)
```

**Comment by MartinThoma** [comment]
There are also quite a lot of [image compression algorithms](https://en.wikipedia.org/wiki/Image_compression)

**Comment by finevine** [comment]
> @pubpub-zz Running the following code compresses all content streams with [DEFLATE](https://en.wikipedia.org/wiki/DEFLATE), including the images, right?
> 
> ```python
> from pypdf import PdfReader, PdfWriter
> 
> reader = PdfReader("example.pdf")
> writer = PdfWriter()
> 
> for page in reader.pages:
>     page.compress_content_streams()  # This is CPU intensive!
>     writer.add_page(page)
> 
> with open("out.pdf", "wb") as f:
>     writer.write(f)
> ```

Yes, it does but as mentionned in the doc, it does not work 
```

+-----------+-------------------------------------------+-------+--------+---------+-------+---------+------+----------+---------+------------------------------+
| Size (Mo) |                   type                    | pypdf | ratio  | quality |  gs   |  ratio  |      | pike-pdf |  ratio  |           quality            |
+-----------+-------------------------------------------+-------+--------+---------+-------+---------+------+----------+---------+------------------------------+
|       108 | Img and OCR                               |   8,6 | 92,04% | good    | 137,3 | -27,13% | good |      163 | -50,93% | good                         |
|        20 | Traditional text and images               |    20 | 0,00%  | good    |  12,3 | 38,50%  | good |       11 | 45,00%  | good for some images         |
|        44 | Repeated huge photos in a word doc to pdf |    44 | 0,00%  | good    |   4,4 | 90,00%  | good |       21 | 52,27%  | very poor on repeated images |
|      56,6 | 400 pages of a book converted to images   |  56,6 | 0,00%  | good    |  69,2 | -22,26% | good |     53,5 | 5,48%   | good                         |
|       5,8 | 96 pages of text and images               |   3,6 | 37,93% |         |     3 | 48,28%  |      |      2,4 | 58,62%  | OK except for alpha layer    |
+-----------+-------------------------------------------+-------+--------+---------+-------+---------+------+----------+---------+------------------------------+

```
pypdf column uses you quoted method
gs column uses https://github.com/theeko74/pdfc (call to ghostscript)
pike-pdf column uses more or less https://github.com/theeko74/pdfc (resize big images with `pillowimage.resize((width/2, height/2), Image.BILINEAR)`

**Comment by pubpub-zz** [comment]
> @pubpub-zz Running the following code compresses all content streams with [DEFLATE](https://en.wikipedia.org/wiki/DEFLATE), including the images, right?
> 
> ```python
> from pypdf import PdfReader, PdfWriter
> 
> reader = PdfReader("example.pdf")
> writer = PdfWriter()
> 
> for page in reader.pages:
>     page.compress_content_streams()  # This is CPU intensive!
>     writer.add_page(page)
> 
> with open("out.pdf", "wb") as f:
>     writer.write(f)
> ```

Having a quick look to the code, It seams that only the content is deflated but not Ximages where big images should be.

@finevine,
I dislike the idea of implementing a non lossless compression : there will be too many options. However, there might be a possibility to implement a visitor function to replace the images

**Comment by finevine** [comment]
Yeah but the idea could be to implement a setter to images and let people
change images and act on each, as pikepdf offer but without too many
options (pikepdf is too complicated I think)

That was the idea of my original feature request title.

I'm willing to help but don't know how to...

It's only an idea. Having only a getter on images is frustrating!

**Comment by pubpub-zz** [comment]
some notes/ideas about image setting:
(just a draft to be cleaned-up
```
from PIL import  Image
from io import BytesIO
w = pypdf.PdfWriter()
w.append("resources/labeled-edges-center-image.pdf")
ii=Image.open("e:/tst_in.jpg")
b=BytesIO()
ii.save(b,"pdf")
rrr =  pypdf.PdfReader(b)


for p in w.pages:
    for image_file_object in page.images:      
        ii=Image.load(bytesIO(image_file_object.data),image_file_object.name.split(".")[-1])
        b = bytesIO()
        ii.save(b,"pdf")
        n=NameObject("/"+"".join(image_file_object.name.split[:-1])))
        ind = p["/Resources"]["/XObject"].raw_get(n)
        w._objects[ind.idnum] = NullObject()   # to cleanup file
        p["/Resources"]["/XObject"][n] 
                           = rrr.pages[0]["/Resources"]["/XObject"]["/image" ].clone(w).indirect_reference
w.write("e:/tt.pdf")
```
