### ISSUE TITLE
PdfReaderError: 'NullObject' object has no attribute 'get' 

### ISSUE THREAD

**Issue by jin0Kang** [py-pdf/pypdf#1565]
Hello! 
I'm trying to extract text from a PDF, but getting the 'NullObject' error when opening this PDF with PdfReader.
I was able to open the file with adobe reader, and extract text from it using other packages (e.g. pdfplumber, pdftotext). 
(Plus, there was no problem opening other files with PdfReader.)
I think it has something to do with 'encrypt_entry' being null.. 
but can't really put a finger on it - if there's something wrong with the file or it's the other issue that makes this error. 

I really would like to find a fix to this issue so that I can use PyPDF2 package for my task. 
     
## Environment

```bash
$ python -m platform
Windows-10-10.0.19044-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
reader = PyPDF2.PdfReader("../Data/pdf/[5] Az-Zour.pdf")
page = reader.pages[3]
pypdf_result = page.extract_text()
print(pypdf_result)
```

Due to the security reason, I am not allowed to share the PDF file that causes the issue. 

## Traceback

This is the complete Traceback I see:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 1
----> 1 reader = PyPDF2.PdfReader("../Data/pdf/[5] Az-Zour.pdf")
      2 page = reader.pages[3]
      3 pypdf_result = page.extract_text()

File c:\Python310\lib\site-packages\PyPDF2\_reader.py:334, in PdfReader.__init__(self, stream, strict, password)
    330 id1_entry = id_entry[0].get_object().original_bytes if id_entry else b""
    331 encrypt_entry = cast(
    332     DictionaryObject, self.trailer[TK.ENCRYPT].get_object()
    333 )
--> 334 self._encryption = Encryption.read(encrypt_entry, id1_entry)
    336 # try empty password if no password provided
    337 pwd = password if password is not None else b""

File c:\Python310\lib\site-packages\PyPDF2\_encryption.py:857, in Encryption.read(encryption_entry, first_id_entry)
    855 @staticmethod
    856 def read(encryption_entry: DictionaryObject, first_id_entry: bytes) -> "Encryption":
--> 857     filter = encryption_entry.get("/Filter")
    858     if filter != "/Standard":
    859         raise NotImplementedError(
    860             "only Standard PDF encryption handler is available"
    861         )

AttributeError: 'NullObject' object has no attribute 'get'

**Comment by pubpub-zz** [comment]
@jin0Kang 
would you prefer to share the file privately with @MartinThoma [[info@martin-thoma.de](mailto:info@martin-thoma.de)](mailto:info@martin-thoma.de ? we will not disclose it

**Comment by jin0Kang** [comment]
Unfortunately, it is not permitted for me to share the file privately or in public since it contains some restricted contents.
BUT, while testing, I extracted some pages from the file and saved it as PDF using other software,  
and then tried extract_text() again with PyPDF2 : there was no problem reading it with PdfReader.
It seems like there was something wrong with the file itself. 
I'm sorry that I can't share the file with you to get to the bottom of the issue and I'll just close this issue myself. 
Thank you!

**Comment by pubpub-zz** [comment]
Happy to welcome you as a contributor.
Waiting for your PR😊
