### ISSUE TITLE
Links to documentation pages are broken

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1569]
If you go to https://pypdf.readthedocs.io/en/latest/user/encryption-decryption.html you can see 

> Please see the note in the [installation guide](https://pypdf.readthedocs.io/en/latest/user/installation.md) for installing the extra dependencies if interacting with PDFs that use AES.

at the very top. It should link to `installation.html`, but it links to `installation.md`.

This issue was mentioned in #1525 and https://github.com/py-pdf/pypdf/pull/1537 attempted to fix it, but broke the doc building process.

Interestingly, I don't have that issue on my local machine

**Comment by abyesilyurt** [comment]
What is the version of `myst_parser` on your local?

**Comment by MartinThoma** [comment]
Ha! Good point :smile: `myst-parser==0.16.1`

Let me check what exactly was the issue on readthedocs :detective:

**Comment by MartinThoma** [comment]
```
INFO: pip is looking at multiple versions of alabaster to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements/docs.txt (line 42) and sphinx==5.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested sphinx==5.3.0
    myst-parser 0.16.1 depends on sphinx<5 and >=3.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by MartinThoma** [comment]
Sphinx 5 support was only added with `myst-parser==0.18.0`. Let's check if we need Sphinx 5 :detective:

**Comment by MartinThoma** [comment]
I've switched to Sphinx 5 with https://github.com/py-pdf/pypdf/pull/1481 , but didn't even mention Sphinx 5.

Looking in the [Sphinx Changelog](https://www.sphinx-doc.org/en/master/changes.html) I feel overwhelmed. I just re-built with sphinx 4.5 and couldn't see any issues.

**Comment by MartinThoma** [comment]
@abyesilyurt Thank you for pointing out this issue again. I need to wait for the build process on readthedocs (about 5 minutes), but I think this time it's fixed.

Sorry for my tone before.

**Comment by MartinThoma** [comment]
```
$ make html
Running Sphinx v4.5.0

Exception occurred:
  File "/home/moose/Github/py-pdf/pypdf/venv/lib/python3.7/site-packages/myst_parser/main.py", line 3, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
The full traceback has been saved in /tmp/sphinx-err-4frt4dqa.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2
```

**Comment by MartinThoma** [comment]
After installing attr:

```
$ make html                           
Running Sphinx v4.5.0

Exception occurred:
  File "/home/moose/Github/py-pdf/pypdf/venv/lib/python3.7/site-packages/myst_parser/main.py", line 4, in <module>
    from attr.validators import (
ModuleNotFoundError: No module named 'attr.validators'; 'attr' is not a package
The full traceback has been saved in /tmp/sphinx-err-cqrud3ir.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2
```

**Comment by MartinThoma** [comment]
The import is `attr`, but I needed https://pypi.org/project/attrs/ :facepalm:

**Comment by MartinThoma** [comment]
Finally, it worked :tada:
