### ISSUE TITLE
Allow radio buttons by no longer excluding /Parent from page clone

### ISSUE THREAD

**Issue by kimberv** [py-pdf/pypdf#1576]
## Explanation
It seems that when you run `writer.add_page(reader.pages[0])` the code of `_add_page` actively strips out the `/Parent` attribute of any annotation, breaking everything belonging to a radio set. This not only makes it impossible for me to set radio values on a writer page, but the resulting new pdf has lost all concept of the radio buttons it once had as editable fields. The exclusion of `/Parent` is relatively new, added about a month ago. When I override this line, everything works beautifully, radio buttons are preserved onto the new pdf and are correctly updated via `update_page_form_field_values`.  

This feels like a bug to me, even if pypdf doesnt claim to support updating radio buttons, it at least shouldn't damage them as they pass through. Whatever your reasons were to exclude /Parent, I hope radio button annotations can be given the blessing to slip through untouched by _add_page.
 
See [relevant line here](https://github.com/py-pdf/pypdf/blame/bee73dc1d3afb683dd5f1f892cf201ed6c23e5ce/pypdf/_writer.py#L264):

```python
excluded_keys += [PA.PARENT, "/StructParents"]
```

**Comment by pubpub-zz** [comment]
@kimberv 
can you try `writer.append(reader,[0])` and report weither things are going better

**Comment by kimberv** [comment]
`writer.append(reader,[0])` does have expected behavior - the radio annotations are passed through, and values are assigned to them.

**Comment by pubpub-zz** [comment]
the documentation already recommend use of `append()`
I propose to close this issue
