### ISSUE TITLE
DOC: migration guide is out of date, README pointer is confusing

### ISSUE THREAD

**Issue by dkg** [py-pdf/pypdf#1581]
In `README.md`, it says:

> NOTE: pypdf>=3.1.0 improved a lot compared to pyPdf<2.0.0 and compared to PyPDF2 < 2.0.0. Please read [the migration guide](https://pypdf.readthedocs.io/en/latest/user/migration-1-to-2.html).

This is confusing in a couple ways:

- i think the PyPDF < 2.0.0 is supposed to be PyPDF2 < 3.0.0
- the link points to a migration from v1 to v2, but the text implies that this is about the migration from v2 to v3

I'm trying to encourage other packages in debian to migrate from `PyPDF2` to `pypdf`, and i'd like to point maintainers of those packages to a clean migration guide.  Does something like that exist?

Without a clear upstream migration guide, i'm inclined to suggest something like "install the last version of PyPDF2 (2.12.1), run your full test suite, and note and resolve any PendingDeprecationWarning that you see."

If you have a better suggestion, i'd be happy to point them to it.

**Comment by MartinThoma** [comment]
There are three groups that need to do migrations:

* `pyPdf` users
* `PyPDF2 < 2.0.0` users
* `PyPDF2 >= 2.0.0` users

In chronological order, without skipping anything, the switches would be:

* Upgrade from `pyPdf` to `PyPDF2 < 2.0.0`: Almost no work. Just replace `pyPdf` by `PyPDF2`
* Upgrade from `PyPDF2<2.0.0` to `PyPDF2>=2.0.0`: A lot of renamings; see the migration guide
* Upgrade from `PyPDF2>=2.0.0` to `PyPDF2>=3.0.0`: No work, if you did the migration before (it just actually removed stuff)
* Upgrade from `PyPDF2>=3.0.0` to `pypdf>=3.1.0`: Just replace `PyPDF2` by `pypdf`.

**Comment by MartinThoma** [comment]
> I'm trying to encourage other packages in Debian to migrate from PyPDF2 to pypdf

Thank you :pray: 

Do you have a list of those?

**Comment by dkg** [comment]
This is the primary bug report: https://bugs.debian.org/1029732

There are 10 downstream bugs open, and i've just supplied https://salsa.debian.org/reproducible-builds/diffoscope/-/merge_requests/125 which should fix two of them in diffoscope.

you should be able to see a summary of them on [the src:pypdf page of the debian BTS](https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=pypdf)

**Comment by dkg** [comment]
oh, and i generated the list of reverse dependencies in debian with `apt rdepends python3-pypdf2` from a debian testing/unstable system, in case that's what you're asking.

**Comment by MartinThoma** [comment]
> i generated the list of reverse dependencies in debian with apt rdepends python3-pypdf2 from a debian testing/unstable system, in case that's what you're asking

Yes!

It gives:

* :heavy_check_mark:  Depends: python3-xhtml2pdf (>= 1.26): https://github.com/xhtml2pdf/xhtml2pdf - seems like debian wasn't updated for a while. I've upgraded from PyPDF3 to pypdf in https://github.com/xhtml2pdf/xhtml2pdf/pull/656
* :heavy_check_mark:   Recommends: xml2rfc done with https://github.com/ietf-tools/xml2rfc/pull/953
* :hourglass_flowing_sand:  Depends: tryton-modules-stock-package-shipping-dpd - still https://github.com/tryton/stock_package_shipping_dpd/blob/develop/setup.py#L61
* Depends: bookletimposer - still https://github.com/con-f-use/bookletimposer/blob/master/setup.py#L115
* Depends: pdfposter - project is dead; the last thing they did was [upgrade to PyPDF2](https://github.com/voidus/pdfposter/commit/a313569de57291b2e492cbb5ffd92e0418c9359b)
* Depends: oca-core - still https://github.com/OCA/OCB/blob/16.0/setup.py#L47
* Depends: krop - still https://github.com/arminstraub/krop/blob/master/krop/pdfcropper.py#L23
* Depends: kraft - I don't find any pypdf dependency
* Recommends: diffoscope - I don't find any pypdf dependency

**Comment by MartinThoma** [comment]
I was looking at https://github.com/unikraft/kraft/tree/staging/kraft, but that was the wrong one.
I've opened an issue there: https://github.com/dragotin/kraft/issues/199

**Comment by MartinThoma** [comment]
I don't think there is anything we can do about this topic anymore. If anybody has concrete suggestions, please raise them.

For the moment, I will close this issue.
