### ISSUE TITLE
Spec about XMP user-defined keys.

### ISSUE THREAD

**Issue by crlf0710** [py-pdf/pypdf#1587]
Not really a bug, but [the comments here](https://github.com/py-pdf/pypdf/blob/8e819d1d00c758d4ccb8c8cd09c79269d0f3a3b9/pypdf/xmp.py#L40-L59) complains about the undocumented-ness of such behavior. However it's actually documented in this spec file:
https://github.com/adobe/xmp-docs/blob/master/XMPSpecifications/XMPSpecificationPart3.pdf and on page 53.

Came hereby accidently by googling some related stuff, but i think this might be worth pointing out.

**Comment by pubpub-zz** [comment]
Thanks for your pointer
I agree that pointing all those docs may help people to understand pdf. 
@MartinThoma what do you think to add a dedicate "references" page in About pypdf
the links to pdf reference (listed in https://opensource.adobe.com/dc-acrobat-sdk-docs/pdflsdk/#pdf-reference) should be referenced too.

**Comment by MartinThoma** [comment]
@pubpub-zz I typically like having such documentation close to where it's needed (if it's only one place), e.g. like this: https://github.com/py-pdf/pypdf/pull/1592

For general documentation, I would rather put it here: https://github.com/py-pdf/awesome-pdf#the-file-format

**Comment by pubpub-zz** [comment]
> @pubpub-zz I typically like having such documentation close to where it's needed (if it's only one place), e.g. like this: #1592
> 
> For general documentation, I would rather put it here: https://github.com/py-pdf/awesome-pdf#the-file-format

Sounds good to me. However having a link( or better inclusion?) to  https://github.com/py-pdf/awesome-pdf#the-file-format may be useful, to guide people who are looking for a better understanding of pdf ?

**Comment by MartinThoma** [comment]
I've added it https://github.com/py-pdf/awesome-pdf#the-file-format :-)
