### ISSUE TITLE
PdfReader : extracting header / footer from the PDF

### ISSUE THREAD

**Issue by jin0Kang** [py-pdf/pypdf#1588]
Hello! 
While extracting texts from PDFs, 
I found out that PyPDF detects header/footer in the body of the file and returns the output - header/footer first, and then the contents. 

Out of 14 files that I'm working on, every file that has h/f in it returned h/f first and then the body (see  'Output' of TEST1 below) except one file (see 'Output' of TEST2 below).

I was wondering why this exception happens, looked through the codes, 
but couldn't find the key to get to this issue. 

It would be really helpful if I could get some clues here.
I also would like to know where in code I should look into to understand the way PdfReader reads header/footer from the file. 

Just in case the synonym 'header' makes confusion - 
when I said header/footer here, I meant the texts on the top/bottom of every page, 
not the header, the first 8 bytes of PDF that contains information about version.  

Thank you! 

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.19044-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python

print("---------TEST1----------")
reader = PyPDF2.PdfReader("../Data/pdf/test1.pdf")
page = reader.pages[0]
pypdf_result = page.extract_text()
print(pypdf_result)
print("\n---------TEST2----------")
reader = PyPDF2.PdfReader("../Data/pdf/test2.pdf")
page = reader.pages[0]
pypdf_result = page.extract_text()
print(pypdf_result)

```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

[test1.pdf](https://github.com/py-pdf/pypdf/files/10541529/test1.pdf)
[test2.pdf](https://github.com/py-pdf/pypdf/files/10541530/test2.pdf)

## Output

This is the complete Output I see:

---------TEST1----------
Here is the Header ! 1 / 64 
Here  is the Fo oter!  
 2014 -12-27  
  
 
 
Exhibit
 
4.28 
CONTRACT  
FOR  
CONSTRUCTION  AND  SAL

---------TEST2----------
Exhibit 4.28 
CONTRACT 
FOR 
CONSTRUCTION
 
AND
 
SAL
 
 
 
 
 
1
/
 6
4
 
 
 
H
e
r
e
 
i
s
 
t
h
e
 
H
e
a
d
e
r
!
 201 4 - 1 2 - h e r e  i s  t h e  f o o t e r

**Comment by pubpub-zz** [comment]
Pypdf currently extracts text as it is within the file. It does not mean it reads the text from top to down
 I would guess in your file it is the case. It does not mean it will be always like that 
For the line return it can be the way the text is 'printed'. Pypdf is currently not always very efficient

**Comment by jin0Kang** [comment]
So it doesn't recognize the header/footer and return it separately, does it?  
When it (seemed like it) did, that's because the texts in my files is there that way within the files. - did I get it right?

**Comment by MartinThoma** [comment]
@jin0Kang Does https://github.com/py-pdf/pypdf/pull/1590/files answer your questions?

**Comment by MartinThoma** [comment]
@jin0Kang Thank you for providing two examples. I think the second one is interesting and something we would like to do better. Instead of

```
H
e
r
e

i
s

t
h
e

H
e
a
d
e
r
!
```

We would like to extract

> Here is the Header!

That is something I would consider a bug int pypdf.

The question about header/footer detection is a different topic. While the comment in the mentioned PR is more nuanced, the gist of it is that we will never directly do that. pypdf will only provide the tools to write such heuristics for detecting them yourself.

**Comment by jin0Kang** [comment]
> @jin0Kang Does https://github.com/py-pdf/pypdf/pull/1590/files answer your questions?

Totally.
I think I was kind of in the lack of understanding the format of PDF.
Your comment made it all clear that was confusing to me. 
Thank you very much.

**Comment by pubpub-zz** [comment]
@MartinThoma 
I agree with you test2.pdf is a good candidate for test when we will improve text_extraction. I propose to create a discussion thread to store all those good examples whilst closing the issues
