### ISSUE TITLE
Fixing RTL ligatures decomposition order

### ISSUE THREAD

**Issue by naourass** [py-pdf/pypdf#1589]
## Explanation

When you extract Arabic text, the words are returned in backward order which is a normal behavior for RTL languages, and you need to use bidi algorithm to be able to display it correctly across UI/GUIs.

The problem is when you have ligatures chars that are composed of two or more chars, these ligatures are not reversed which makes the extracted text inaccurate.

**_Here's an example:_**

Let's suppose we have a font with a ligature glyph "لا" that maps to "uni0644 uni0627". The pdf is rendered like this:

![image](https://user-images.githubusercontent.com/4897498/215669836-14d0e66f-cb6e-4fb3-ac86-1299e446e41d.png)

When you extract the pdf text using `page.extract_text()` you get this:
كارتــــــشلاا

Notice how all chars are in reverse order except "لا".

And here's the final result after applying bidi algorithm:
االشــــــتراك

**_Sample PDF:_**
https://drive.google.com/file/d/1SYi4aDRGsgwQydukwfLrkSXoQgH7oPBn/view?usp=sharing

## Implementation
```
# pypdf/_page.py

def _extract_text():
    ...
    elif operator == b"Tj":
        ...
        for x in "".join(
            [cmap[1][x] if x in cmap[1] else x for x in t]
        ):
            ...
```
Before joining `[cmap[1][x] if x in cmap[1] else x for x in t]` into a single string, we can check if there's items with more than one character and if these characters are in the RTL range. If it's the case, we can reverse their order before joining the list.

This could be done by extracting the _RTL Range Check_ method and using it twice (for ligature decomposition and for text appending), or by refactoring the logic of how RTL extraction is handled.

**Comment by naourass** [comment]
Here's another explanation from an [SO answer](https://stackoverflow.com/a/75280462/2355730) for viewers that are not familiar with Arabic:

> An example using RTL with english (sorry), suppose the word "fire" is rendering RTL as "erif" with 3 glyphs: e, r, and fi (through arbitrary CIDs, perhaps \001\002\003). If the CIDs are used to get the Unicode information, and the "fi" ligature is de-ligatured, you'll get "erfi" as the data.

**Comment by pubpub-zz** [comment]
@naourass 
can you review  #1578 and confirm that the side effect is the same. I've started the analysis there and my first thoughts (not validated yet) is that the RTL should be consider when merging Tj (line 1886 and further). Do you want to confirm my analysis and propose a PR? 😉

**Comment by naourass** [comment]
@pubpub-zz
In addition to the issue of this thread which is RTL de-ligaturing, #1578 reflect another issue with _Diacritics_ positioning during RTL extraction. To summarize, there's currently two apparent issues with RTL text extraction:

1. Ligature decomposition: this affect all RTL languages, the ligatures should be reversed before joining each _JT operator_ chars into one string.
2. Diacritics positioning: this affects RTL languages that supports diacritics (I'm not sure if all RTL languages does). It seems that the diacritics are appended to the wrong extremity, which screw up the structure of the entire line of text.

I'll initiate a PR for the first point, and I'll start inspecting the second point further once possible.

**Comment by naourass** [comment]
@pubpub-zz

There's an issue with `015-arabic/habibi.pdf`. I've deleted all the chars except "h". It turned out that "h" is a glyph that is mapped to the whole representation of "حَبيبي h".

_**Here's how the PDF is rendered ([link to the file here](https://drive.google.com/file/d/1srIn4wN9rsw2NBWuQYg4jHSGPat46RqX/view)):**_

![image](https://user-images.githubusercontent.com/4897498/216234090-3f3cc6f6-cfbf-4483-a9d7-5ccfb7c18454.png)

**_Here's what happens if you copy the "h" char from the PDF and paste it in a browser url bar:_**

![image](https://user-images.githubusercontent.com/4897498/216234465-965fcee2-11e9-41ca-ae44-9e853fb22bd7.png)

![image](https://user-images.githubusercontent.com/4897498/216234960-c9b2295d-bb6e-420e-ade1-465167c63c62.png)

**_Here's the content stream and the cmap:_**
```
BT
0 0 0 rg
/GS0 gs
/C2_0 12 Tf
386.3 747.978 Td
<004B>Tj
ET
```

```
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo
<< /Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>> def
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <ffff>
endcodespacerange
4 beginbfchar
<004b> <062d064e0628064a0628064a00200068>
<0044> <0061>
<0045> <0062>
<004c> <0069>
endbfchar
endcmap
CMapName currentdict /CMap defineresource pop
end
end
```

Notice how `<004b>` is mapped to _<062d064e0628064a0628064a00200068>_. I've almost pulled my here to figure out what's happening here, fortunately I've found it 😆.

Let me know where should I publish the new sample Arabic PDF(s) please. Inside resources folder, in network, in samples submodule or somewhere else?

**Comment by pubpub-zz** [comment]
The best is to put the files in the issues. You can then. Reference them from the tests using the url

**Comment by naourass** [comment]
Fixed `Habibi.pdf` for `test_arab_text_extraction()`:
[https://github.com/py-pdf/pypdf/files/10566891/habibi-fixed.pdf](https://github.com/py-pdf/pypdf/files/10566891/habibi-fixed.pdf)

**Comment by naourass** [comment]
Fixed `Habibi.pdf` for `test_arab_text_extraction()`:
[https://github.com/py-pdf/pypdf/files/10567266/habibi-fixed.pdf](https://github.com/py-pdf/pypdf/files/10567266/habibi-fixed.pdf)

**Comment by naourass** [comment]
Fixed `Habibi.pdf` for `test_arab_text_extraction()`:
[https://github.com/py-pdf/pypdf/files/10567356/habibi-fixed.pdf](https://github.com/py-pdf/pypdf/files/10567356/habibi-fixed.pdf)

**Comment by naourass** [comment]
@pubpub-zz
I've made a [PR](https://github.com/py-pdf/pypdf/pull/1597) to fix the main arabic extraction test. I'll make another one for ligature decomposition. Let me know if there's any problem.

**Comment by naourass** [comment]
@pubpub-zz 
Thanks for your feedback. I need some confirmation if it's better to keep the odd habibi.pdf inside the main Arabic extraction test, or to move it into a new Ligatures Decomposition test since it contains an uncommon and very special case ligature (glyph "h" mapped to Arabic+Latin+White characters. Can you review this please:
https://github.com/py-pdf/pypdf/pull/1597#discussion_r1095379136

**Comment by naourass** [comment]
Added `arabic-ligature.pdf` for `test_ligature_aracb_extraction()`:
[https://github.com/py-pdf/pypdf/files/10707635/arabic-ligature.pdf](https://github.com/py-pdf/pypdf/files/10707635/arabic-ligature.pdf)

**_P.S._** We'll still have to test also bidirectional text (Arabic+Latin) including Arabic inside Latin, Latin inside Arabic, Arabic then Latin, Latin then Arabic, end with punctuation, and end with diacritic.

**Comment by naourass** [comment]
@pubpub-zz Awesome, RTL ligatures order has been fixed in https://github.com/py-pdf/pypdf/commit/f5ac79bb552f2e55579854565a31a67fdfdee275. I'll be closing the draft PR.

**Comment by pubpub-zz** [comment]
I close this issue as Fixed
