### ISSUE TITLE
Page merging broken since #1371

### ISSUE THREAD

**Issue by raphaelm** [py-pdf/pypdf#1601]
We are using PyPDF to implement a "n-up" feature in our application. With the upgrade from PyPDF 2.12.x to PyPDF 3.x, this broke. We are now only getting white pages as the output.

## Environment

```bash
$ python -m platform
Linux-6.0.9-arch1-1-x86_64-with-glibc2.36

$ python -c "import pypdf;print(pypdf.__version__)"
3.3.0
```

## Code + PDF

Our actual source code is here:
https://github.com/pretix/pretix/blob/79ee89bde91293e22c314c436ac095b3c9b811c5/src/pretix/plugins/badges/exporters.py#L218-L242

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfWriter, PdfReader

in_pdf = PdfReader('badges-38.pdf')
out_pdf = PdfWriter()

page_1 = out_pdf.add_blank_page(in_pdf.pages[0].mediabox[2], in_pdf.pages[0].mediabox[3])
page_1.merge_page(in_pdf.pages[0])

out_pdf.write('pypdf3.pdf')

from PyPDF2 import PdfWriter, PdfReader  # with PyPDF2 being version 2.12.1

in_pdf = PdfReader('badges-38.pdf')
out_pdf = PdfWriter()

page_1 = out_pdf.add_blank_page(in_pdf.pages[0].mediabox[2], in_pdf.pages[0].mediabox[3])
page_1.merge_page(in_pdf.pages[0])

out_pdf.write('pypdf2.pdf')
```

**pypdf2.pdf will look the same as badges-38.pdf. pypdf3.pdf is completely white. The only difference is the PyPDF version.**

It does not seem to be dependent on the input file, but alas, here's one I used:
[badges-38.pdf](https://github.com/py-pdf/pypdf/files/10579503/badges-38.pdf)

**Comment by pubpub-zz** [comment]
Thanks for the report
I've completed #1567 to fix this issue (may be linked the `add_blank_page()` but not sure it was this only ?

**Comment by raphaelm** [comment]
Amazing, thanks for the quick fix and release <3
