### ISSUE TITLE
 A way to modify /edit  PDF Form Field Names

### ISSUE THREAD

**Issue by ccsv** [py-pdf/pypdf#1606]
## Explanation

It would good to have a way to modify the field names for fill able fields so that things like `FORMNAME[0].Page1[0].FormField1[0]Name` can be changed to "Name"

## Code Example

I think this would be used something like
```python
from pypdf import PdfReader

reader = PdfReader("form.pdf")
fields = reader.get_form_text_fields()
fields.rename(
    page=reader.pages[0],
    keys={
        "FIELD1_OLD_NAME": "FIELD1_NEW_NAME",
        "FIELD2_OLD_NAME": "FIELD2_NEW_NAME",  # ...
    },
)

```

**Comment by pubpub-zz** [comment]
Your post is quite difficult to understand:
* in the explanation, you are dealing with fields tree:

The fields are organized in a tree, linked upward through Parents. and downward through Kids : Top level fields have no parents and you should just add the indirect reference of the Root['/Acroform']['/Fields']

* in the code example you are dealing with renaming directly the fields.

`get_fields()` the values in the dictionnary return have an attribute `indirect_reference` that is pointing to the original pdf dDictionaryObject where you can change the fields including the '/TU' and '/TM' properties.
