### ISSUE TITLE
text_extraction invalid for habibi.pdf

### ISSUE THREAD

**Issue by pubpub-zz** [py-pdf/pypdf#1619]
I've opened https://github.com/py-pdf/sample-files/pull/13 to put `habibi.pdf` in the sample-files repo.  i recommend including a test for it before merging this.

the extracted show the arab characters to be reversed

_Originally posted by @dkg in https://github.com/py-pdf/pypdf/issues/1126#issuecomment-1186507898_

**Comment by pubpub-zz** [comment]
@dkg 
thanks for the sample :)

**Comment by MartinThoma** [comment]
Thank you for the improvement @pubpub-zz :pray: 

I'll make a release this weekend :-)
