### ISSUE TITLE
� when extracting arabic text

### ISSUE THREAD

**Issue by AldawsariNLP** [py-pdf/pypdf#1621]
When i convert arabic pdf document to txt I got this result: 

this symbol � is not an arabic character. What should i do to get better results for arabic language? 
```bash
رقم �و سرف �سحيفة دعواها بطلب اإلغاء ذلك القرار، واإعادتها اإىل العمل، و � من العمل، وختمت سرت النظر فيها �سية، واإحالتها اإىل هذه الدائرة با �ستحقه من رواتب. وبقيد دعواها ق�ما ت ساألت الدائرة � هـــ، 1434 /4/25 سة�سات. ففي جل�سبط اجلل� سر�على النحو املبني يف حما املُدَّعمِية عن دعواها فَقَرَّرت باأنَّها وفق لئحة دعواها املرفقة، واأنها تظلمت لدى املدعى  سة �هـ. وبجل 1433 /2/27 هـ، وتظلمت اإىل اخلدمة املدنية بتاريخ 1433 /2/24 عليها بتاريخ ستندات جاء �هـــ قدم مَُثِّل املدعى عليها مذكرة اأرفق معها جمموعة من امل 1433 /10/22  سة�ستني وتََّ تكليفها
```
Thanks

**Comment by pubpub-zz** [comment]
Can you provide the pdf file ?

**Comment by MartinThoma** [comment]
Please always let us know which version of pypdf you're using. You can do that with `print(pypdf.__version__)`

**Comment by AldawsariNLP** [comment]
Sorry for the late reply, 
 I am using : pypdf: "^3.4.0"
[hukm1.pdf](https://github.com/py-pdf/pypdf/files/10717398/hukm1.pdf)


Thanks

**Comment by pubpub-zz** [comment]
@AldawsariNLP 
When I use copy and paste from acrobat reader , I get the same odd characters:

![image](https://user-images.githubusercontent.com/4083478/218339814-f20d888b-ae5e-453a-82ef-6dc65932d7b3.png)

This is not an issue with pypdf

**Comment by AldawsariNLP** [comment]
oh i see. I will try to find out a way to recognize these odd characters. Thanks
