### ISSUE TITLE
Rotation is kept when using the same page again

### ISSUE THREAD

**Issue by jblob** [py-pdf/pypdf#1630]
when rotating a page und using the same page again to create a document  with another or no rotation the value of the rotoation is the previous rotation plus the new rotation. I would expect to get the page rotated only by the second value.

In the example below the following rotations are used:
page1: 90°
page2: 180°
page3: 180°
expected:
page1: 90°
page2: 90°
page3: 0°

```python
from pypdf import PdfReader, PdfWriter


def rotate_pages_test(pdf_path):
    writer = PdfWriter()
    reader = PdfReader(pdf_path)
    page_1 = reader.pages[0].rotate(90)
    writer.add_page(page_1)
    page_2 = reader.pages[0].rotate(90)
    writer.add_page(page_2)
    page_3 = reader.pages[0]
    writer.add_page(page_3)

    with open("rotate_pages_test.pdf", "wb") as fh:
        writer.write(fh)


if __name__ == "__main__":
    path = "crazyones.pdf"
    rotate_pages_test(path)
```

**Comment by MartinThoma** [comment]
@jblob PyPDF2 is deprecated. Please try again with `pypdf`. Please also add the version you are using + a PDF that shows the behavior (if it's for all, use `"crazyones.pdf"`).

I'll close this until the information is there.

**Comment by jblob** [comment]
same behaviour with pypdf, code snippet updated

**Comment by MartinThoma** [comment]
> Please also add the version you are using

**Comment by pubpub-zz** [comment]
@jblob, 
what you are describing sounds logic : 
page_1 is pointing to reader.pages[0] that has been modified to add /Rotate field set to 90
then you assign page_2 to reader.pages[0] already rotated to 90 , so arrive to 180 °; page_1, page_2, and reader.page[0] are all refering to same page : it is absolutely normal to get the same results.

a better option is to use writer.append() and then use .rotate() on writer.page[]

**Comment by pubpub-zz** [comment]
documentation has been updated. This issue can be closed
