### ISSUE TITLE
Broken characters when merging pages

### ISSUE THREAD

**Issue by raphaelm** [py-pdf/pypdf#1640]
We are using PyPDF to implement a "n-up" feature in our application. With the upgrade from PyPDF 2.12.x to PyPDF 3.x and the fix for #1601, this now generally works again but breaks in funny ways with text.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-6.0.9-arch1-1-x86_64-with-glibc2.36

$ python -c "import pypdf;print(pypdf.__version__)"
3.4.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from decimal import Decimal
from pypdf import PdfWriter, PdfReader, Transformation
from pypdf.generic import RectangleObject

mm = 72.0 / 2.54 * 0.1

out_pdf = PdfWriter()
page_1 = out_pdf.add_blank_page(210 * mm, 297 * mm)

in_pdf_1 = PdfReader('badges_3vjrh_7LXDZ_1-1.pdf')
in_page_1 = in_pdf_1.pages[0]
page_1.merge_page(in_page_1)

in_pdf_2 = PdfReader('badges_3vjrh_7LXDZ_2-1.pdf')
in_page_2 = in_pdf_2.pages[0]
in_page_2.add_transformation(Transformation().translate(0, +150 * mm))
in_page_2.mediabox = RectangleObject((
    Decimal('%.5f' % (in_page_2.mediabox.left.as_numeric())),
    Decimal('%.5f' % (in_page_2.mediabox.bottom.as_numeric() + 150 * mm)),
    Decimal('%.5f' % (in_page_2.mediabox.right.as_numeric() )),
    Decimal('%.5f' % (in_page_2.mediabox.top.as_numeric() + 150 * mm))
))
in_page_2.trimbox = in_page_2.mediabox
page_1.merge_page(in_page_2)

out_pdf.write('merge.pdf')
```

Input files:
[badges_3vjrh_7LXDZ_1-1.pdf](https://github.com/py-pdf/pypdf/files/10768334/badges_3vjrh_7LXDZ_1-1.pdf)
[badges_3vjrh_7LXDZ_2-1.pdf](https://github.com/py-pdf/pypdf/files/10768335/badges_3vjrh_7LXDZ_2-1.pdf)

## Expected output

The expected output is this. We can obtain this output by using e.g. PyPDF 2.12.1:
[pypdf2.pdf](https://github.com/py-pdf/pypdf/files/10768345/pypdf2.pdf)

## Actual output

The actual output from PyPDF3 is this:
[pypdf3.pdf](https://github.com/py-pdf/pypdf/files/10768347/pypdf3.pdf)

Note that the first line now reads "Hans-J**ö**rgen" instead of "Hans-J**ü**rgen"

**Comment by MartinThoma** [comment]
> The actual output from PyPDF3 is this:
[pypdf3.pdf](https://github.com/py-pdf/pypdf/files/10768347/pypdf3.pdf)

I guess you mean pypdf==3.4.1, right?
I'm asking because PyPDF3 is a completely different project.

**Comment by pubpub-zz** [comment]
Error found. not referening the good object. Funny effect and quite tricky to locate
 I've produced the PR If you want to try

**Comment by raphaelm** [comment]
> I guess you mean pypdf==3.4.1, right?
> I'm asking because PyPDF3 is a completely different project. 

Yes! Sorry.

> Error found. not referening the good object. Funny effect and quite tricky to locate
>  I've produced the PR If you want to try

It's amazing how quick you are ❤️ Happy to test the PR on Monday!

**Comment by raphaelm** [comment]
Yup, PR seems to work for me! :)

**Comment by MartinThoma** [comment]
The fix was just merged and will be in `pypdf>3.4.1` (this weekend on PyPI)

**Comment by MartinThoma** [comment]
Thank you for reporting it! If you want I can add you as a contributor: https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by raphaelm** [comment]
Nah, that's fine, but thanks! :)
