### ISSUE TITLE
Unable to extract nested PDFs due to directory structure

### ISSUE THREAD

**Issue by saranshbansal** [py-pdf/pypdf#1645]
I'm trying to extract all the attachments from a PDF.

## Code + PDF
Here's my code:

```python
from PyPDF2 import PdfReader


# creating a pdf file object
pdfFileObj = open('example.pdf', 'rb')

# creating a pdf reader object
pdfReader: PdfReader = PyPDF2.PdfReader(pdfFileObj)
attachments = get_attachments(pdfReader)


def get_attachments(reader: PdfReader) -> dict:
    """
    Retrieves the file attachments of the PDF as a dictionary of file names
    and the file data as a bytestring.
    :return: dictionary of filenames and bytestrings
    """
    catalog = reader.trailer["/Root"]
    print(catalog['/Names']) # ERROR
    fileNames = catalog['/Names']['/EmbeddedFiles']['/Kids'][0].getObject()['/Names']
    attachments = {}
    for f in fileNames:
        if isinstance(f, str):
            name = f
            dataIndex = fileNames.index(f) + 1
            fDict = fileNames[dataIndex].getObject()
            fData = fDict['/EF']['/F'].getData()
            attachments[name] = fData

    return attachments
```

When I run the code, I get this error:

```
File "/Users/saranshbansal/PycharmProjects/CVFilter/util.py", line 31, in get_attachments
    print(catalog['/Names'])
  File "/Users/saranshbansal/PycharmProjects/CVFilter/venv/lib/python3.8/site-packages/PyPDF2/generic/_data_structures.py", line 266, in __getitem__
    return dict.__getitem__(self, key).get_object()
KeyError: '/Names'
```

When I tried to understand the file structure inside `catalog` object, I couldn't find any place where attachments could be stored.

Attached is a sample PDF that I'm working with:
[R-00199139 - Software Engineer_2023-02-09-04-31-12.pdf](https://github.com/py-pdf/pypdf/files/10779648/R-00199139.-.Software.Engineer_2023-02-09-04-31-12.pdf)

**Comment by pubpub-zz** [comment]
When you look at firts page, you will see many annots which are actually some links to external documents. There is no attachments in your pdf.

**Comment by saranshbansal** [comment]
> When you look at firts page, you will see many annots which are actually some links to external documents. There is no attachments in your pdf.

Thanks @pubpub-zz, I didn't realize those were annotations. Also, the annotations should point to pages inside the document itself rather than some external link.

In this case, is it possible to extract pages out of the pdf based on annotations? I need to read every CV inside this PDF programmatically which could span multiple pages and I can't seem to find a way to do that.

**Comment by GitHubRulesOK** [comment]
Hmmm
The paperclips links point to a local file (that naturally is not in my graphics folder

But the link should have been set to later pages ? odd did somebody simply merge? looking at the different fonts OMG it must have been a merge of many files, luckily most are embeded.
![image](https://user-images.githubusercontent.com/12754913/220524727-bbbc9f6b-76a8-4e05-81a0-238d9761964f.png)

But the links do specify a page  AHHH the names don't match `.-.` is != ` - ` rename to `R-00199139 - Software Engineer_2023-02-09-04-31-12.pdf`
![image](https://user-images.githubusercontent.com/12754913/220525573-91ee3f32-3533-4d03-bfb0-5726b55168ef.png)

**Comment by pubpub-zz** [comment]
> Thanks @pubpub-zz, I didn't realize those were annotations. Also, the annotations should point to pages inside the document itself rather than some external link.
> 
> In this case, is it possible to extract pages out of the pdf based on annotations? I need to read every CV inside this PDF programmatically which could span multiple pages and I can't seem to find a way to do that.

@saranshbansal , all explainations were provided from my point of view. Can you clarify if you are looking for something else?

**Comment by GitHubRulesOK** [comment]
The File needs overhaul see the oddly high value for the `goto Y`  but not relevant to the question which how to get a list of page numbers for cleaving the file back into its constituent parts so the annot /D numbers are base 0  = 2 4 6 8 9.... showing its uneven splits required.

**Comment by pubpub-zz** [comment]
> The File needs overhaul see the oddly high value for the `goto Y` but not relevant to the question which is how to get a list of page numbers for cleaving the file back into its constituent parts so the annot /D numbers are base 0 = 2 4 6 8 9.... showing its uneven splits required. pages 3-4 5-6 7-8 & only 9 etc. so would need paired outputs

Some CV are one page only, and it might be difficult to find the name. You have another option: the outlines seem correctly filled and are holding the the name
you can create new pdf with PdfWriter()  / append(), and write them the title
To get the pages you can use this : r.flattened_pages.index(r.outline[n]["/Page"])

You should have all you need to complete your extraction.

**Comment by pubpub-zz** [comment]
I close now this issue as you may have all your answers. feel free to add more elements if any
