### ISSUE TITLE
merge_pdf() CPU throttling on Azure Function

### ISSUE THREAD

**Issue by devistollon** [py-pdf/pypdf#1651]
We are creating an Azure Function that receives a PDF as an input and merge a timestamp (created with _reportlab_ library) and a PDF with a watermark (read as a BytesIO stream).
When working on my local PC the file is correctly processed but when I deploy the code in the Azure Function it throws a CPU throttling warning in the Log stream.
Are there any known problems about the using of the library on a Function/Lambda?

**Comment by MartinThoma** [comment]
If the same code and the same PDF (that you didn't share) with an unknown version of pypdf didn't cause any issues locally, I guess this is not about pypdf.

I'm closing this now as there is no way the core pypdf devs can help you with this little information.

If you (or other people) have any more information, please share it here :-)
