### ISSUE TITLE
Enhance Documentation on merging rotated PDFs

### ISSUE THREAD

**Issue by Lars147** [py-pdf/pypdf#1655]
## Explanation

Documentation on the function `pdf_page.transfer_rotation_to_content()` would be a great benefit. I had a hard time figuring out what I was missing when merging a rotated pdf file.

**Comment by pubpub-zz** [comment]
@Lars147 can you from your better understanding, contribute and propose a PR?

**Comment by MartinThoma** [comment]
Here is an example how a documentation PR can look like: https://github.com/py-pdf/pypdf/pull/1647

**Comment by pubpub-zz** [comment]
@Lars147 
+1 ?

**Comment by amaank404** [comment]
Believe me when I say this, it took me a while to figure this out. +1

**Comment by MartinThoma** [comment]
@amaank404 Do you want to improve the documentation?

**Comment by stefan6419846** [comment]
This is already documented for at least the stamping/watermarking docs.

**Comment by amaank404** [comment]
> This is already documented for at least the stamping/watermarking docs.

I beg to differ, I started by reading the API Docs directly. I suppose it would be better if a little reference to this apply function was present. Like a footnote that to actually apply the values to the elements, please look at this function (Important for merging purposes).

I am taking up this issue, I propose to add a reference to the rotate functions of pageobject and transform function of the pageobject. I will do so once I get approval from people here.
