### ISSUE TITLE
ENH: Support adding multiple file attachments

### ISSUE THREAD

**Issue by moodh** [py-pdf/pypdf#169]
Hi!
I would like the possibility of merging in pages as hidden attachments, is this possible with pypdf at all?

Edit:
This seems to have been added now (thanks!), but it seems the addAttachment() method can only add a single hidden attachment which is very problematic. I saw the bugfix for this in https://github.com/mstamy2/PyPDF2/issues/275 so I'd really appriciate if this was merged. :)

It also seems that the method doesn't handle unicode input (python 2.7).

Thanks!

**Comment by moodh** [comment]
This seems to have been added now (thanks!), but is there a way to read the hidden attachments? Or at least get the document information about them?

**Comment by MartinThoma** [comment]
It's called File Attachment in pdf:

* https://pypdf2.readthedocs.io/en/latest/user/reading-pdf-annotations.html
* https://pypdf2.readthedocs.io/en/latest/user/adding-pdf-annotations.html


Does that help / answer the question? Is it maybe already solved?
