### ISSUE TITLE
Add Links doesn't work (internal or external)

### ISSUE THREAD

**Issue by corsair20141** [py-pdf/pypdf#1691]
When I try to add an internal OR external link following the documentation, the output 1 page PDF doesn't contain any link or visible box element at all. I have tried viewing in Adobe Reader and Chrome.

## Environment

```bash
$ python -m platform
Windows-10-10.0.22621-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.5.1
```

## Code + PDF

This is a minimal, complete example that shows the issue (straight from the Documentation):

```python
import pypdf
from pypdf.generic import AnnotationBuilder

reader = pypdf.PdfReader("Test.pdf")
page = reader.pages[0]
writer = pypdf.PdfWriter()
writer.add_page(page)

# Add the line
annotation = AnnotationBuilder.link(
    rect=(50, 550, 200, 650),
    url="https://martin-thoma.com/",
)
writer.add_annotation(page_number=0, annotation=annotation)

# Write the annotated file to disk
with open("Test_ANNOTATED.pdf", "wb") as fp:
    writer.write(fp)
```

PDF sample: [Test.pdf](https://github.com/py-pdf/pypdf/files/10913131/Test.pdf)

**Comment by Camyden74** [comment]
I'm having this same issue  I'm able to add the rectangle polygon line etc.. from the example code but adding links does not work

**Comment by Camyden74** [comment]
I was able to make a web link with PyPDF2 as the import but I can’t figure out the in document link ….to link to another page.  I don’t understand how to use fit_args or what to put there

**Comment by Camyden74** [comment]
I'm a beginner and can't for the life of me figure out how to add the answer for you on Overstack... I've solved this issue Colton if you want to reach out you can find my on FB https://www.facebook.com/camilla.ricketts.5

**Comment by corsair20141** [comment]
Can you add it here so the team can close the ticket if it is not a bug?

**Comment by Camyden74** [comment]
`from pypdf import PdfReader, PdfWriter
from pypdf.generic import AnnotationBuilder
from pypdf.generic import Fit

pdf_path = "LinkTest.pdf"
reader = PdfReader(pdf_path)
page = reader.pages[0]
writer = PdfWriter()
writer.add_page(page)

# Create a Fit object with type 'FitH' and top coordinate 155
fit = Fit('/Fit')
fitaArgs = ()

# Add the line
annotation = AnnotationBuilder.rectangle(
    rect=(590, 662, 680, 720),
)
writer.add_annotation(page_number=0, annotation=annotation)

annotation = AnnotationBuilder.link(
    rect=(590, 662, 680, 720),
    target_page_index=3,
    fit=fit

)

writer.add_annotation(page_number=0, annotation=annotation)

# Write the annotated file to disk
with open("annotated-pdf.pdf", "wb") as fp:
    writer.write(fp)`

**Comment by MartinThoma** [comment]
@Camyden74 The link is added without any visual hint by default. If you want to see where it is, add the `border`, e.g.:

```
annotation = AnnotationBuilder.link(
    border=[0, 0, 1],
    rect=(50, 550, 200, 650),
    url="https://martin-thoma.com/",
)
```

**Comment by MartinThoma** [comment]
@corsair20141 Does adding a border solve your issue?

**Comment by Camyden74** [comment]
@MartinThoma actually I'm adding in document links I'm using the rectangle before the link annotation to help guide me on placement as I'm reading through the pdf and matching text with regex then adding the link based on the position of the text

**Comment by MartinThoma** [comment]
I don't understand the issue. The link is there:

![image](https://user-images.githubusercontent.com/1658117/226176464-8d452d34-8638-482c-9653-294783bdf828.png)

Feel free to add more comments. If I understand what the problem is (if there is a problem) I will open again.
