### ISSUE TITLE
Add .page_mode to PDFMerger

### ISSUE THREAD

**Issue by tcplomp** [py-pdf/pypdf#1692]
## Explanation

The PDFMerger class misses the .page_mode property, it needs to use .output.page_mode. Other properties have been exposed (for instance .page_layout).

## Code Example

```python
from pypdf import PdfMerger

mergedfile = PdfMerger

#existing code
mergedfile.output.page_mode = '/UseOutlines'

#new code
mergedfile.page_mode = '/UseOutlines'

**Comment by pubpub-zz** [comment]
PdfMerger is deprecating. You should be able to work with PdfWriter and append()

**Comment by pubpub-zz** [comment]
@tcplomp 

Is it ok with PdfWriter ? can we close this ?

**Comment by tcplomp** [comment]
Yes PdfWriter does the job correct.

**Comment by tcplomp** [comment]
Implemented in PdfWriter
