### ISSUE TITLE
Possible infinite loop in functions `skip_over_whitespace` and `skip_over_comment`

### ISSUE THREAD

**Issue by peteris-zealid** [py-pdf/pypdf#1693]
If the stream reaches its end then tok will be an empty `bytes` and `b"" in b"anything" == True`.
This can cause an infinite loop for a corrupted pdf.

Some lines for reference.
```
while tok in WHITESPACES:
    tok = stream.read(1)
```

Skip over comment has a similar problem.

**Comment by pubpub-zz** [comment]
Thanks for the review do you have any file showing the issue and that can be used for testing ? Can you propose a PR ?

**Comment by peteris-zealid** [comment]
Failed to construct a pdf that causes an infinite loop in practice.

**Comment by pubpub-zz** [comment]
issue to be closed cf #1694
