### ISSUE TITLE
Modify Pdf Content

### ISSUE THREAD

**Issue by ghilmanrandhawa** [py-pdf/pypdf#1696]
Currently, I need to update the text within the "{{name}}" field in a PDF file and generate a new PDF file with the updated content. However, I am unable to create a new PDF file at the moment.

**Comment by pubpub-zz** [comment]
@ghilmanrandhawa
Can we close this issue ?

**Comment by BhavyaMPatel** [comment]
import re
import PyPDF2
import spacy
from spacypdfreader import pdf_reader
nlp = spacy.load("en_core_web_sm")

def mask_pii_data():
    print("h")
    
    with open('BhavyaMPatel_Resume.pdf', 'rb') as pdf_file:
        # Create a PDF reader object
        pdf_reader = PyPDF2.PdfReader(pdf_file)

        # Create a PDF writer object
        pdf_writer = PyPDF2.PdfWriter()

        # Iterate over the pages in the PDF file
        for page_num in range(len(pdf_reader.pages)):
            # Get the current page
            page = pdf_reader.pages[page_num] 

            # Get the page text
            page_text = page.extract_text()
            
            doc=nlp(page_text)
            final_text = ' '.join("$$$" if token.ent_type_ == "PERSON"  else token.text for token in doc)
        
            
            page_text=page_text.replace(page_text,final_text)
            print(page_text)
            print('h')
            **#Here I Change The Text That Need To Update so now how to convert back  it to pageobject because extracted text is 
             changed but page object is still unmodified** 


            # Add the modified page to the PDF writer object
            pdf_writer.add_page(page)
            

        # Write the modified PDF file back to disk
        with open('masked_' + 'BhavyaMPatel_Resume.pdf', 'wb') as output_file:
            pdf_writer.write(output_file)

mask_pii_data()

**Comment by BhavyaMPatel** [comment]
hi could see my comment on line after final_text 
that i change the extracted text but pageobject is still unmodified so how to modified it 
Thank you

**Comment by pubpub-zz** [comment]
All is on post n°2 of this thread.

**Comment by hoehermann** [comment]
For future reference, I am trying do some search-and-replacing in PDF. So far, I came up with [this](https://github.com/hoehermann/pypdf_strreplace). It works for some cases. It is good enough for me, maybe it helps other people as well. :)

**Comment by BhavyaMPatel** [comment]
@hoehermann I will refer it , thank you
