### ISSUE TITLE
issue with pytest

### ISSUE THREAD

**Issue by pubpub-zz** [py-pdf/pypdf#1700]
## Environment

windows 11
python 3.11
pytest 7.2.2
pypdf 3.5.1+dev

## Code + PDF

pytest can not be run without mod:

## Traceback

````
pytest

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --disable-socket --enable-socket
  inifile: e:\PyPDF4.git\PyPDF2\pyproject.toml
  rootdir: e:\PyPDF4.git\PyPDF2
````

for the moment I have a workaround commenting the addopts in pyproject.toml

Is this normal ?

**Comment by MartinThoma** [comment]
It seems like you didn't install `pytest-socket`:

```
pip install -r requirements/ci-3.11.txt
```

**Comment by pubpub-zz** [comment]
great! thanks
