### ISSUE TITLE
Bold text get duplicated from extract_text() due to overlapping text in PDF

### ISSUE THREAD

**Issue by 154192** [py-pdf/pypdf#1731]
Duplicated text for bold text with extract_text()

![image](https://user-images.githubusercontent.com/30179436/226504868-a826922c-ca02-4b9e-a380-b386bc3d8a93.png)

[300218_2011.pdf](https://github.com/py-pdf/pypdf/files/11024449/300218_2011.pdf)
[300218_2011.txt](https://github.com/py-pdf/pypdf/files/11024452/300218_2011.txt)

**Comment by pubpub-zz** [comment]
when you look within the pdf encoding you will see that the text is present many times. This can be confirmed if you zoom a lot you will see the characters overlapping:
![image](https://user-images.githubusercontent.com/4083478/226525234-47f7d40c-b1bc-4837-adfa-d2fc192756cd.png)
If you read the file with PDF.js you will get it multiple times too.

The only solution I would propose you is to post process your `parts` array searching for duplicates before you join them into `text_body`

**Comment by 154192** [comment]
> when you look within the pdf encoding you will see that the text is present many times. This can be confirmed if you zoom a lot you will see the characters overlapping: ![image](https://user-images.githubusercontent.com/4083478/226525234-47f7d40c-b1bc-4837-adfa-d2fc192756cd.png) If you read the file with PDF.js you will get it multiple times too.
> 
> The only solution I would propose you is to post process your `parts` array searching for duplicates before you join them into `text_body`

Hello, can you encapsulate a function to solve this problem? This situation is common when parsing pdf files, or can you provide me with the code to solve it? Thank you!

**Comment by pubpub-zz** [comment]
No : extract is doing its job : the text is present many times and PDF.js is extracting the same. it is something you have to do in your code

**Comment by MartinThoma** [comment]
@pubpub-zz is right: This is out of scope. As it might be hard to see what is in scope and what not, I'm preparing some documentation: https://github.com/py-pdf/pypdf/pull/1743
