### ISSUE TITLE
How to discard cropped information from a PDF

### ISSUE THREAD

**Issue by CHIJUI0128** [py-pdf/pypdf#1736]
I need to crop a PDF to extract some specific information in that PDF document. Is there a way that I can crop a PDF and only preserve the image inside the cropped area, and discard all the other information outside the cropped area?

I have tried using pypdf to crop it using the following code.
thanks~

```python
from pypdf import PdfReader, PdfWriter

with open("in.pdf", "rb") as in_f:
    reader = PdfReader(in_f)
    output = PdfWriter()

    num_pages = 4

    for i in range(num_pages):
        page = reader.pages[i]
        print (page.mediabox.right(), page.mediabox.top())
        page.cropbox.lower_left = (50, 50)
        page.cropbox.upper_right = (200, 200)
        output.add_page(page)

    with open("out.pdf", "wb") as out_f:
        output.write(out_f)
```

This issue seems similar to https://github.com/py-pdf/pypdf/issues/1508

**Comment by CHIJUI0128** [comment]
Or have any ideas for me?
thank you all

**Comment by CHIJUI0128** [comment]
@pubpub-zz 
May I ask your thoughts?
This issue is similar to #1508

**Comment by pubpub-zz** [comment]
Your approach seems good however prefer to work within the PdfWriter:
```
output = PdfWriter()
output.clone_document_from_reader(PdfReader("in.pdf"))
for page in output.pages:
    print (page.mediabox.upper_right)
    page.cropbox.lower_left = (50, 50)
    page.cropbox.upper_right = (200, 200)

output.write("out.pdf")
```
just drafted, I did not tried it.

**Comment by CHIJUI0128** [comment]
@pubpub-zz
Hi thank you for your response
This issue arises because the entire PDF file cannot be disclosed to the client.
First of all, I decided to share the part that can be revealed.
Then create a blank page and paste the part that can be disclosed

**Comment by CHIJUI0128** [comment]
```
from PyPDF2 import PdfWriter, PdfReader

reader = PdfReader("text6.pdf") 
writer = PdfWriter()


page1 = reader.pages[0]
page1.mediaBox.upper_right = (page1.mediaBox.right/2, page1.mediaBox.top/2 )
page1.cropBox.upper_right = (page1.cropBox.right/2, page1.cropBox.top/2 )
print(page1.mediaBox.getWidth(),page1.mediaBox.getHeight())

Blank_page = PageObject.createBlankPage(None, page1.mediaBox.getWidth(), page1.mediaBox.getHeight())
print(Blank_page.mediaBox.getWidth(),Blank_page.mediaBox.getHeight())

Blank_page.mergePage(page1)

writer.addPage(Blank_page)

with open("PyPDF2-output.pdf", "wb") as fp:
    writer.write(fp)
```

**Comment by pubpub-zz** [comment]
@CHIJUI0128 
you are  PyPDF2 we do not support anymore.
Also, please remember that we are volunteers who are maintaining a community project. If you want some actual support you should at lease consider some sponsoring : have a look at #1660

**Comment by pubpub-zz** [comment]
@CHIJUI0128 
what is the update. Should we close this ?
