### ISSUE TITLE
Add documentation about PDF/A

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1739]
I think we should add some documentation about PDF/A and pypdf.

And I want to save https://www.slub-dresden.de/veroeffentlichen/dissertationen-habilitationen/elektronische-veroeffentlichung/slub-pdfa-validator for later :-)

**Comment by MartinThoma** [comment]
https://avepdf.com/de/pdfa-validation

**Comment by pubpub-zz** [comment]
> I think we should add some documentation about PDF/A and pypdf.
> 
> And I want to save https://www.slub-dresden.de/veroeffentlichen/open-access-publizieren/pdfa-erstellung/slub-pdfa-validator for later :-)

Ich spreche kein Deutsch 😭

**Comment by pubpub-zz** [comment]
> I think we should add some documentation about PDF/A and pypdf.
> 
> And I want to save https://www.slub-dresden.de/veroeffentlichen/open-access-publizieren/pdfa-erstellung/slub-pdfa-validator for later :-)


Ich spreche nicht Deutsch
