### ISSUE TITLE
AttributeError: 'NumberObject' object has no attribute 'indirect_reference'

### ISSUE THREAD

**Issue by mask616** [py-pdf/pypdf#1742]
## Environment

Which environment were you using when you encountered the problem?

* os： windows10
* pypdf version: 3.0.1

```bash
$ python -m platform
Windows-10-10.0.19044-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
def merge(pdfFilelist, output):
    if(len(pdfFilelist) == 0):
        return
    merger = PdfWriter()
    for pdf in pdfFilelist:
        merger.append(pdf)
        # pdf_reader_page(pdf, merger)
    merger.write(output)
    merger.close()
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

* file1: https://sharelink.rongdasoft.com/share-link/index.html?q=16bf855ee9cb7000&type=1
* file2: https://sharelink.rongdasoft.com/share-link/index.html?q=16bf85b05aa49000&type=1

## Traceback

This is the complete Traceback I see:

```
File "D:\01workspace\02myself\python_source\study\venv\lib\site-packages\PyPDF2\_writer.py", line 2326, in append
    self.merge(
  File "D:\01workspace\02myself\python_source\study\venv\lib\site-packages\PyPDF2\_utils.py", line 417, in wrapper
    return func(*args, **kwargs)
  File "D:\01workspace\02myself\python_source\study\venv\lib\site-packages\PyPDF2\_writer.py", line 2416, in merge
    elif dest["/Page"].indirect_reference.idnum in srcpages:
AttributeError: 'NumberObject' object has no attribute 'indirect_reference'
```

**Comment by pubpub-zz** [comment]
@mask616 
Can you please add the files directly in the thread : the link you are provided are in chinese and can not be understood

**Comment by MartinThoma** [comment]
@mask616 Can you please upgrade your pypdf version to 3.6.0 and try again?

**Comment by pubpub-zz** [comment]
@mask616 
I close this thread as not updated with the PDF. feel free to ask to reopen it after attaching the files

**Comment by parthtoatter** [comment]
I'm facing the similar issue. Kindly let me know if you happen to find a solution

**Comment by development-lnxct** [comment]
I'm facing the same issue while merging pdfs, in fact, on my local system. the images render our perfectly but on the server side pypdf fails to render images. Ending up in this error
