### ISSUE TITLE
Linked form fields are deleted after merging (since v3.0)

### ISSUE THREAD

**Issue by spacerat1** [py-pdf/pypdf#1753]
I have a PDF file with linked form fields.
(all fields have the same name, so if you enter text in one of the fields, the text will appear in all other fields too)
I used XChange Editor Plus for creating this form fields.

If i merge some PDFs, all linked form fields are deleted after/while merging. 
This issue occurs in v3.0.1 (PyPDF2) and in  3.7.0 (pypdf).
It worked up to v2.12.1 (PyPDF2)
[before_merging.pdf](https://github.com/py-pdf/pypdf/files/11088649/before_merging.pdf)
[after_merging.pdf](https://github.com/py-pdf/pypdf/files/11088651/after_merging.pdf)

**Comment by pubpub-zz** [comment]
@spacerat1 
can you provide the code you are using. without we can not provide any advice

**Comment by spacerat1** [comment]
Hello.
i simplified my code to the essential part. Just put the before_merging.pdf and any other pdf file (i.e the before_merging_1.pdf)  in a folder and merge these files. This uses PyPDF2 3.0.1, but i have the same issue using pypdf v3.7.0


```
import os
from PyPDF2 import PdfMerger  #change PyPDF2 to pypdf if you use a newer version
from tkinter import filedialog

file_name = 'after_merging.pdf'

if root_path := filedialog.askdirectory(): # specify the folder with the pdf files to merge
    file_list = os.listdir(root_path)
    merger = PdfMerger()
    for file in file_list:
            if os.path.isfile(f'{root_path}/{file}') and os.path.splitext(f'{root_path}/{file}')[1] == '.pdf': # if file is pdf, append it
                merger.append(f'{root_path}/{file}')
    merger.write(f'{root_path}/{file_name}') # write the new file
```


[before_merging.pdf](https://github.com/py-pdf/pypdf/files/11093125/before_merging.pdf)
[before_merging_1.pdf](https://github.com/py-pdf/pypdf/files/11093128/before_merging_1.pdf)

**Comment by pubpub-zz** [comment]
can you retry using PdfWriter instead of PdfMerger : the append function has been improved there. PdfMerger is deprecating

**Comment by spacerat1** [comment]
I replaced PdfMerger with PdfWriter.
This works like a charm. Thanks for the hint.

**Comment by MartinThoma** [comment]
Let's leave this open. If we broke PDF Merger on the way we should fix it (and if pdfmerger is no longer necessary, we should mark it as deprecated)

**Comment by pubpub-zz** [comment]
> Let's leave this open. If we broke PDF Merger on the way we should fix it (and if pdfmerger is no longer necessary, we should mark it as deprecated)

We should mark PdfMerger as obsolete

**Comment by pubpub-zz** [comment]
PdfMerger is under depreciation. #1824
We can close this issue
