### ISSUE TITLE
SEC: Switch to AES for encryption

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1754]
Currently, pypdf uses the security handler revision number 3 (R=3) and V=2. That means:

> "Algorithm 1: Encryption of data using the RC4 or AES algorithms"
in 7.6.2, "General Encryption Algorithm," but permitting encryption key lengths
greater than 40 bits.

RC4 is not secure ([source](https://en.wikipedia.org/wiki/RC4)). At the very least we should issue a big warning + document this behavior. By default, we should use secure encryption methods

AES encryption is not implemented so far. Only decryption.

**Comment by xilopaint** [comment]
> AES encryption is not implemented so far. Only decryption.

Is this mean pypdf can do AES decryption without external dependencies? If so, I thought even decryption would only be possible with PyCryptodome.

**Comment by MartinThoma** [comment]
> even decryption would only be possible with PyCryptodome

That is correct
