### ISSUE TITLE
xfa pdf cloned using `clone_document_from_reader` does not display content of signed PDF

### ISSUE THREAD

**Issue by udhavsethi** [py-pdf/pypdf#1757]
I am trying to fill xfa pdf forms programmatically. As a first step, I'm attempting to clone an input PDF file using the clone_document_from_reader function, but I'm encountering an issue where the output file displays "Please wait..." and doesn't show the content of the original document. Any guidelines on cloning and filling or even filling in place would be really helpful. Thanks!

## Environment

Which environment were you using when you encountered the problem?

```bash

$ python --version
Python 3.9.12

$ python -m platform
macOS-10.16-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.5.1
```

## Code + PDF

```python
import pypdf

input_file = "form.pdf"
output_file = "form_clone.pdf"

reader = pypdf.PdfReader(open(input_file, 'rb'))
writer = pypdf.PdfWriter()

writer.clone_document_from_reader(reader)
with open(output_file, 'wb') as output:
    writer.write(output)
```

form.pdf:
<img width="1202" alt="form" src="https://user-images.githubusercontent.com/7031380/228698398-2c103309-318b-443a-8eea-c4bb52a51411.png">

form_clone.pdf:
<img width="1392" alt="form_clone" src="https://user-images.githubusercontent.com/7031380/228698400-438acad9-4bd8-416d-a25c-d481f0db8754.png">

**Comment by MartinThoma** [comment]
Can you please upload the pdf? A screenshot does not help

**Comment by MartinThoma** [comment]
Can you please try with pypdf==3.7.0 (the latest version)?

**Comment by udhavsethi** [comment]
@MartinThoma thank you for your response!

I tried again with pypdf==3.7.0. The output is different now - I can view the contents of the pdf. But the editable fields in the form are gone, and I see a warning about JavaScript being disabled:

<img width="1451" alt="Screen Shot 2023-03-30 at 7 37 32 PM" src="https://user-images.githubusercontent.com/7031380/228987912-6a0225f8-1755-4148-ba24-6530b21e2eb0.png">

Also, on first opening the pdf, I see the following popup from Adobe Acrobat:
<img width="260" alt="Screen Shot 2023-03-30 at 7 45 05 PM" src="https://user-images.githubusercontent.com/7031380/228988895-9a789c30-f998-4b79-85dc-a0c6775de325.png">

The pdf I'm trying to work with is [here](https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5257e.pdf)

**Comment by pubpub-zz** [comment]
@udhavsethi 
your PDF is signed. the cloning of the document has modified the document and therefore broke the certification, preventing fields to appear. pypdf is for the moment not able to handle that. sorry😔

**Comment by pubpub-zz** [comment]
I propose to close this issue 'Not Planned'
