### ISSUE TITLE
Merging pdfs without page breaks

### ISSUE THREAD

**Issue by Chryron** [py-pdf/pypdf#1763]
I am trying to merge two pdf files into one, such that there is no page break between them. 

Two identical example pdf files are here: [pdf1][1], [pdf2][2]

I would like to merge the above files to produce something similar to this result: [ideal_output_pdf][3]

I can merge the two input pdfs into an [output][4] with a page break between where pdf1 ends and pdf2 begins:

```python
import PyPDF2

pdf1= open('pdfs/output1.pdf', 'rb')
pdf2= open('pdfs/output2.pdf', 'rb')

file1 = PyPDF2.PdfReader(pdf1)
file2 = PyPDF2.PdfReader(pdf2)
output = PyPDF2.PdfMerger()
output.append(file1)
output.append(file2)

with open("failed_merged.pdf", "wb") as outputStream:
    output.write(outputStream)

# Close the PDF files
pdf1.close()
pdf2.close()
```
However, when I attempt to do this after calling `merge_page` on the last `PageObject` of `file1`, it does not produce the desired result.

```python
import PyPDF2

pdf1= open('pdfs/output1.pdf', 'rb')
pdf2= open('pdfs/output2.pdf', 'rb')

file1 = PyPDF2.PdfReader(pdf1)
file2 = PyPDF2.PdfReader(pdf2)
output = PyPDF2.PdfWriter() 
page = file1.pages[-1]
page.merge_page(file2.pages[0])
output.add_page(page) # PdfMerger().append(file1) has not worked for me either

with open("merged_attempt.pdf", "wb") as outputStream:
    output.write(outputStream)

# Close the PDF files
pdf1.close()
pdf2.close()

```

I assumed calling `.merge_page` on the last and first pages of pdfs 1 and 2 respectively would allow me to do what I wanted, but it only seems to produce the unmerged page. Any help on how to do this and whether it is possible would be appreciated!

  [1]: https://github.com/Chryron/pdf-merging/blob/main/pdfs/output1.pdf
  [2]: https://github.com/Chryron/pdf-merging/blob/main/pdfs/output2.pdf
  [3]: https://github.com/Chryron/pdf-merging/blob/main/pdfs/ideal_merged.pdf
  [4]: https://github.com/Chryron/pdf-merging/blob/main/pdfs/failed_merged.pdf

**Comment by pubpub-zz** [comment]
@Chryron 
first you are using an obsolete version. You have to uninstall PyPDF2 and install pypdf
then have a look at this thread :
https://github.com/py-pdf/pypdf/issues/1676#issuecomment-1454050030

**Comment by pubpub-zz** [comment]
@Chryron
Any Update ?

**Comment by pubpub-zz** [comment]
I close this isssue without update. feel free to ask to reopen it if you have more data
