### ISSUE TITLE
Issue with Transformation().Rotate

### ISSUE THREAD

**Issue by keggering** [py-pdf/pypdf#1764]
I am using PyPDF2 to create a booklet (aka Saddle-Stitch) PDF by combining two landscape-orientation Letter-size (8.5 x 11) pages (i.e. single-page PDF files) into one Tabloid (17x11) sheet in portrait orientation. 

It seems that PyPDF2.Transformation().rotate(180) does not work. However, a rotation of 179.99999999999 does. 

I haven't dug into the source code as to why, but wanted to raise the issue somewhere. If there is a better thread to raise this in, please let me know.

Thanks!

**Comment by pubpub-zz** [comment]
@keggering 
I order to be more precise, can you provide a code sample (perhaps using crazyones.pdf") ?

**Comment by MartinThoma** [comment]
I'm closing this issue for the moment as there is too little information. Once there is more, I can reopen
