### ISSUE TITLE
Help: how to use Lossless Compression

### ISSUE THREAD

**Issue by tomasserravento** [py-pdf/pypdf#1777]
Hi guys, how are you? First of all thank you so much for making and mantaining this amazing library!

I am trying to use the Lossless Compression but cant make it work at least for me. Could you please tell me if I may be missing to install something? I installed pypdf with the full command, Im using Python 3.10.6 and pypdf 3.7.1

I tried compressing many PDFs and all of them return with the same size (Ive tried PDFs of 500KB, 2MB, 5MB and 8MB). Here is one of the PDF files I used: [pdf-example-bookmarks.pdf](https://github.com/py-pdf/pypdf/files/11187214/pdf-example-bookmarks.pdf)

The code I tried is the following: https://pypdf.readthedocs.io/en/latest/user/file-size.html#lossless-compression

Thank you and sorry for bothering!

**Comment by pubpub-zz** [comment]
If you look in details the original PDF is 8 294 344 bytes and the "compressed" one is 8 246 341bytes, so slightly less. The `compress_content_streams()` applies a zlib/deflate compression on the text only.  Do not expect an important size reduction.
