### ISSUE TITLE
PDF font garbled

### ISSUE THREAD

**Issue by BriskyGates** [py-pdf/pypdf#1782]
Hi guys, how are you? First of all thank you so much for making and mantaining this amazing library!
I want to extract the watermark text, but I only got the garbled one, I dont konw why

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# Windows-10-10.0.19041-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
pypdf              3.6.0

```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import os

from pypdf import PdfReader

text = ""
try:
    reader = PdfReader('page_1.pdf')
    for page in reader.pages:
        text += page.extract_text()
        text += "\r\n"
except Exception as exc:
    print('failed to extract text from pdf')
finally:
    print(text)

```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

[pdf_font_garbled.pdf](https://github.com/py-pdf/pypdf/files/11190189/pdf_font_garbled.pdf)

## screenshot of  the extracted text
![lQLPJwW7xapf-1LNAbrNAy6wdmIV38JfdiQELCFRCwAuAA_814_442](https://user-images.githubusercontent.com/34669414/230874875-027fd621-2d87-4f10-8118-1d8a5ecf3975.png)

Thank you and sorry for bothering!

**Comment by MartinThoma** [comment]
PyPDF2 is deprecated. Can you please try again with `pypdf` and adjust the code / the traceback (I guess that is not the traceback, but the extracted text?)

**Comment by BriskyGates** [comment]
thank you for responding to me so quickly, I updated the comment just now

**Comment by BriskyGates** [comment]
sorry, my mistakes, I upload the wrong pdf which seems an image of pdf
please see the new pdf file
thank you very much

**Comment by BriskyGates** [comment]
I debug step by step, and found that it couldn't be decoded, the traceback is : unknown encoding: /UniGB-UCS2-H
relevant location of py:  pypdf/_text_extraction/__init__.py, line:223
![image](https://user-images.githubusercontent.com/34669414/231131324-272c7720-0eca-4114-8ff3-2cf06821555b.png)

**Comment by pubpub-zz** [comment]
@BriskyGates 
the issue seems clearly linked with UniGB-UCS2-H encoding. It should be decoded as utf-16-be. I've proposed a PR. Can you confirm it fixes your issue?

**Comment by BriskyGates** [comment]
> @BriskyGates the issue seems clearly linked with UniGB-UCS2-H encoding. It should be decoded as utf-16-be. I've proposed a PR. Can you confirm it fixes your issue?

Thank you for your help earlier. Unfortunately, the issue still persists. The problem is with pypdf's original decoding strategy. If it can't decode UniGB-UCS2-H, it tries to use utf-16-be instead, even if that doesn't work either. I'm currently trying to figure out how pypdf decodes UniGB-UCS2-H, and comparing it to pdfminer's decoding process, which seems to  decode UniGB-UCS2-H successfully

![image](https://user-images.githubusercontent.com/34669414/231337765-5be8a7c6-8d07-4a40-92c3-9c38bb358272.png)

**Comment by BriskyGates** [comment]
> @BriskyGates the issue seems clearly linked with UniGB-UCS2-H encoding. It should be decoded as utf-16-be. I've proposed a PR. Can you confirm it fixes your issue?

thanks a lot, it works well

**Comment by BriskyGates** [comment]
> @BriskyGates the issue seems clearly linked with UniGB-UCS2-H encoding. It should be decoded as utf-16-be. I've proposed a PR. Can you confirm it fixes your issue?
I was wondering that how you could know utf16be can decode unigb-ucs2?

**Comment by pubpub-zz** [comment]
> I was wondering that how you could know utf16be can decode unigb-ucs2?

I found the info here:
https://github.com/adobe-type-tools/cmap-resources/blob/master/README.md
![image](https://user-images.githubusercontent.com/4083478/231789645-c60fd4cc-5785-43c8-9e44-8755098da206.png)

**Comment by MartinThoma** [comment]
The fix by @pubpub-zz was just merged to `main`. It will be part of the `pypdf==3.8.0` release tomorrow

**Comment by MartinThoma** [comment]
@BriskyGates Thank you for sharing this issue. If you want, I would add you as a contributor to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html
