### ISSUE TITLE
Disproportionately large file sizes

### ISSUE THREAD

**Issue by DIvkov575** [py-pdf/pypdf#1786]
when trying to split large pdf's, output file size is disproportionately large.
here is my code 
```
def split(path, file_name=""):
    reader = PdfReader(open(path, 'br'))
    for (i, page) in enumerate(reader.pages):
        reader = PdfReader(open(path, 'br'))
        writer = PdfWriter()
        writer.add_page(reader.pages[i])
        # output= f'{778+j2*i}(right).pdf'
        output= f'{file_name[4:-4]}-{i}(left).pdf'
        with open(join(getcwd(), "downloads/output-scans/left", output), 'wb') as output_file: writer.write(output_file)


dirlist = listdir(join(getcwd(), "downloads/scans/left"))
for file in dirlist:
    dirlist = listdir(join(getcwd(), "downloads/scans/left"))
    split(join(getcwd(), "downloads/scans/left", file), file)
    exit
```

each output file is the same exact size as the input. I have a hunch this is caused by pypdf trying to cram the entire input file contents into each output.

this does not occur with smaller pdfs.

## Environment

zsh
python 3.9.6
pypdf 3.7.1
Aarch M2 Max

**Comment by pubpub-zz** [comment]
Can you please provide the pdf file for analysis

**Comment by pubpub-zz** [comment]
I've just done the analysis using PDF debugger (https://pdfbox.apache.org/1.8/commandline.html) which is listed in https://github.com/py-pdf/awesome-pdf

When you look at the pages they are all using the same resource object (id 2) 
![image](https://user-images.githubusercontent.com/4083478/231532273-1123bbd4-5386-4fd6-a1f6-37d5f570266a.png)

if you crawl deeper, you will find the images of all the pages. So extracting one page only will pull all the images. 
pypdf is doing its job😊, it is just an oddly generated file.

@MartinThoma improving pdfly could be nice but pdf debugger  or pdf vole are already usefull tools

**Comment by pubpub-zz** [comment]
I propose to close the issue. @MartinThoma do you think it worth to create a discussion ?

**Comment by MartinThoma** [comment]
I was thinking about keeping it open until somebody improves the docs: https://pypdf.readthedocs.io/en/latest/user/file-size.html

1. Changing the viewboxes ("cropping") has no impact on file size
2. Removing complete pages only has an impact if the connected resources are also removed

For (2): How does that actually work within pypdf: If a resource has no indirect reference, is it automatically removed? Or could there be objects without references?

@DIvkov575 Do you want to improve the documentation?

**Comment by MartinThoma** [comment]
@pubpub-zz For (2): How does that actually work within pypdf: If a resource has no indirect reference, is it automatically removed? Or could there be objects without references?

**Comment by pubpub-zz** [comment]
> @pubpub-zz For (2): How does that actually work within pypdf: If a resource has no indirect reference, is it automatically removed? Or could there be objects without references?

no it is possible to have objects not referenced but I agree it is unusual.
what exists also is some objects which are referenced but no usable. This is common in incremental updates. and but also with pypdf when appending (with add_page, append or during cloning) all the objects linked are sucked. For example if you have some articles in a page that are chained on other pages, the pages objects are copied but are not referenced in the pages list (and therefore not visible). because of this sucking with add_page, I recommend using append() which has been improved.

**Comment by DIvkov575** [comment]
@MartinThoma sorry about late reply, I would be happy to update docs (if its not too late).

**Comment by MartinThoma** [comment]
It's never too late to improve the docs :-)

Don't worry, we don't have time lines / time pressure. Your exams are more important :-)

**Comment by davidquintana** [comment]
Are there any tools available that let one prune objects which are referenced but not used (or objects not referenced)? Or perhaps if for example every page includes the same background image and fonts, changing all but one to be references as a method of reducing PDF size?

**Comment by pubpub-zz** [comment]
> Are there any tools available that let one prune objects which are referenced but not used (or objects not referenced)? Or perhaps if for example every page includes the same background image and fonts, changing all but one to be references as a method of reducing PDF size?

my opinion:
With pypdf you can do some cleanup easily just with  `pypdf. PdfWriter(clone_from:"doc_path").write("destination")`
however I don't think more can be done automatically
Using the same image for all the backgrounds is possible but it has to be done manually (the background images are not all labeled the same and how to ensure you have the same image content every where): in such case manually you can just use the `.indirect_reference` property of the image to be used everywhere.

**Comment by davidquintana** [comment]
As a follow-up, the update to the chosen SO answer explains very well how to use GhostScript (using -dDetectDuplicateImages=true) to replace duplicate images with references. It worked very well, reducing my 150MB PDFs to about 7MBs: https://stackoverflow.com/questions/10450120/optimize-pdf-files-with-ghostscript-or-other

In my case, I'm merging a bunch of individual 1-page PDFs into a single PDF resulting in the duplicated background image (think individual slides being put together into a slide deck).
