### ISSUE TITLE
Negative Seek Value on some PDFs

### ISSUE THREAD

**Issue by ajmeese7** [py-pdf/pypdf#1791]
I'm running a very simple script to check for the PDF validity of 1000 files for a CTF. With one of the PDFs, I get a negative seek value from the library.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.15.0-69-generic-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf.__version__)"
3.7.0
```

## Code + PDF

```py
import os
from pypdf import PdfReader
from pypdf.errors import PdfReadError

base_filename = "report"
base_path = "Wireshark_Objects"

file_list = []
for i in range(0, 1000):
    file_list.append(base_filename + ("(" + str(i) + ")" if i > 0 else "") + ".pdf")

i = 0
for file in file_list:
    print("File #%s:" % i)
    try:
        PdfReader(os.path.join(base_path, file))
        print("\tVALID!!!!")
    except PdfReadError:
        print("\tNot a real PDF file :(")
    else:
        pass
    i += 1
```

[report(631).pdf](https://github.com/py-pdf/pypdf/files/11240523/report.631.pdf)

## Traceback

This is the complete Traceback I see:

```log
Traceback (most recent call last):
File "/home/aaron/Documents/NCL/2023/Team/check_pdf_validity.py", line 16, in <module>
PdfReader(os.path.join(base_path, file))
File "/home/aaron/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pypdf/_reader.py", line 322, in __init__
self.read(stream)
File "/home/aaron/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pypdf/_reader.py", line 1510, in read
xref_issue_nr = self._get_xref_issues(stream, startxref)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/aaron/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pypdf/_reader.py", line 1874, in _get_xref_issues
stream.seek(startxref - 1, 0)  # -1 to check character before
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: negative seek value -1
```

**Comment by pubpub-zz** [comment]
@ajmeese7, 
have a look at 
https://pypdf.readthedocs.io/en/stable/user/suppress-warnings.html#exceptions

**Comment by MartinThoma** [comment]
When I open the PDF in evince / Atril:

![image](https://user-images.githubusercontent.com/1658117/232337528-381d3276-ad56-44cd-85b7-36e5fd036f35.png)

Same for Chrome.

**Comment by ajmeese7** [comment]
Yeah it's a blank PDF, I'm aware of that, I just think the library should handle that edge case gracefully instead of spitting out an error for the end user to handle. The try-catch should be on the library side in this case IMO

**Comment by MartinThoma** [comment]
It's not a blank PDF, it's an invalid PDF. Upload it to https://www.pdf-online.com/osa/validate.aspx to see for yourself.

If you try `import json; json.loads("invalid")` you will also get an exception.

**Comment by stefan6419846** [comment]
@batterseapower You are always invited to propose a suitable PR to fix it if you consider this a bug/inconsistency.
