### ISSUE TITLE
Simply duplicate fillable pdf but can't get fields() from the new one.

### ISSUE THREAD

**Issue by remove158** [py-pdf/pypdf#1792]
I just simply duplicate fillable pdf form using `PdfWriter.add_page`. After that I  open the new one with `PdfReader`. Now the new pdf return None from `reader.get_fields()`
1. My first fillable form has many fields when I use `reader.get_fields()`
2. The new one return None (or empty dict {} in case I update the old one with `writer.update_page_form_field_values(writer.pages[0], {})` before saving)

## Environment

Which environment were you using when you encountered the problem?

```bash
pypdf2 = "^3.0.1"
python = "^3.11"
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from PyPDF2 import PdfReader, PdfWriter

source =  'tests/jt32.pdf'
out = 'output.pdf'
reader = PdfReader(source)
writer = PdfWriter()

fields = reader.get_fields()
print(fields)
for i in range(len(reader.pages)):
    writer.add_page(reader.pages[i])
    

with open(out, 'wb') as output_file:
    writer.write(output_file)

reader_2 = PdfReader(out)
print(reader_2.get_fields())
```
pdf: https://cdn.discordapp.com/attachments/1082352569973751868/1096945829291503676/jt32.pdf

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete Traceback I see:
Noting error !!

**Comment by MartinThoma** [comment]
PyPDF2 is deprecated. Use pypdf.

**Comment by remove158** [comment]
> PyPDF2 is deprecated. Use pypdf.

Thanks for the quick reply, I've tried both pypdf, pypdf2, it doesn't matter which version. Both versions produce the same results.

**Comment by pubpub-zz** [comment]
fields are part of the PDF structure not pages. try `append()` adding all the pages at once instead of `add_page()`

**Comment by MartinThoma** [comment]
> Thanks for the quick reply, I've tried both pypdf, pypdf2, it doesn't matter which version. Both versions produce the same results.

That is not the point. When you use deprecated software you cannot expect any support. Development will continue with `pypdf`. The project is called `pypdf`, not `PyPDF2`. We don't have the resources to maintain two projects. By directly using the maintained project you will get better results (at least in some cases, see CHANGELOG) and it helps us to spend our time more effectively.

**Comment by neversphere** [comment]
> fields are part of the PDF structure not pages. try `append()` adding all the pages at once instead of `add_page()`

The sample code in the docs doesn't mention this (https://pypdf.readthedocs.io/en/stable/user/forms.html?highlight=Interactions%20with%20PDF%20Forms). Does it need to be updated?

**Comment by MartinThoma** [comment]
Adding some information there is certainly a good idea! Do you want to open a PR @neversphere ? :innocent:

**Comment by neversphere** [comment]
https://github.com/py-pdf/pypdf/pull/1806
