### ISSUE TITLE
Parsing pdf garbled characters

### ISSUE THREAD

**Issue by Ontheroad123** [py-pdf/pypdf#1809]
When i use pypdf2 parse PDF files, some files are output "Multiple definitions in dictionary at byte 0x4c334 for key /MediaBox"  when parsing, and garbled after opening txt.

## Environment

```bash
$ python -m platform
# TODO: Linux-5.15.0-69-generic-x86_64-with-debian-bullseye-sid

$ python -c "import pypdf;print(pypdf.__version__)"
# TODO: 3.0.1
```

## Code + PDF

```python
# TODO: 
`
from PyPDF2 import PdfReader
reader = PdfReader("1.pdf", strict=False)
#print(len(reader.pages))
with open('1.txt', 'w') as text_file:
    for i in range(len(reader.pages)):
        page = reader.pages[i]
        text_file.write(page.extract_text())`
```
PDF file links:
链接: https://pan.baidu.com/s/1lWY6rjEhbg_oTIMFtqfPgQ 提取码: secg 

Processed txt:
'
NJAÖÐ»ªÄÐ¿ÆÑ§ÔÓÖ¾NationalJournalofAndrologyZhonghuaNanKeXueZaZhi2022£¬28(5):462－470http://www．androl．cnStandardization＆Guideline·¹æ·¶ÓëÖ¸ÄÏ·Ç°ÁÐÏÙ´©´Ì»î¼ì×¨¼Ò¹²Ê¶ÖÐ»ªÒ½Ñ§»áÄÐ¿ÆÑ§·Ö»áÇ°ÁÐÏÙ´©´Ì»î¼ì×¨¼Ò¹²Ê¶±àÐ´×é【¹Ø¼ü´Ê】Ç°ÁÐÏÙ;´©´Ì;»î¼ì;×¨¼Ò¹²Ê¶ÖÐÍ¼·ÖÀàºÅ:Ｒ697+．3ÎÄÏ×±êÖ¾Âë:Adoi:10．13263/j．cnki．nja．2022．05．013①½üÄêÀ´£¬ÎÒ¹úÇ°ÁÐÏÙ°©(prostatecancer£¬PCa)µÄ·¢²¡ÂÊ¼°ËÀÍöÂÊ¾ù³Ê¿ìËÙÉÏÉýÇ÷ÊÆ。Ç°ÁÐÏÙÌØÒìÐÔ¿¹Ô­(prostatespecificantigen£¬PSA)、¶à²ÎÊý´Å¹²Õñ(multi-parametricmagneticresonanceimaging£¬mpMＲ
'

**Comment by pubpub-zz** [comment]
@Ontheroad123 
the link you've provided points to a page in chinese not understandable.
please attach the pdf directly within this issue

**Comment by Ontheroad123** [comment]
Thanks for you response, here is the file, @pubpub-zz 
[3.pdf](https://github.com/py-pdf/pypdf/files/11315397/3.pdf),

**Comment by MartinThoma** [comment]
@Ontheroad123 PyPDF2 is deprecated. Use pypdf instead

**Comment by Ontheroad123** [comment]
@MartinThoma, i also use pypdf to parse PDF files, and still appear garbled characters, 
the code like this 
`
from pypdf import PdfReader
reader = PdfReader("3.pdf")
number_of_pages = len(reader.pages)
print(number_of_pages)
page = reader.pages[0]
text = page.extract_text()
print(text)
`
I think it might be a lack of fonts, but i don't know how to slove it.

**Comment by pubpub-zz** [comment]
a new cmap encoding to be considered.
@Ontheroad123  a PR is produced : if you want to try a patch to confirm

**Comment by Ontheroad123** [comment]
> a new cmap encoding to be considered. @Ontheroad123 a PR is produced : if you want to try a patch to confirm

I have add code in "_cmap.py", and it's ok, thank you.

**Comment by stefan6419846** [comment]
@ChanghaoLau Please open a new issue and fill the complete reporting template accordingly.
