### ISSUE TITLE
Text conversion clips a URL that spans over a linebreak

### ISSUE THREAD

**Issue by dpriskorn** [py-pdf/pypdf#1810]
We are trying to extract all URLs from PDFs reliably using PyPDF2.

This is how the link looks in the Firefox pdf reader:
![image](https://user-images.githubusercontent.com/68460690/234083710-5736d097-282d-43ea-8ba1-fdcd6f9cbcdc.png)

## Environment

Which environment were you using when you encountered the problem?

```bash
  $ python -m platform
Linux-6.1.24-1-lts-x86_64-with-glibc2.37

$ python -c "import pypdf;print(pypdf.__version__)"
3.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
# TODO: Your code goes here
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
https://www.foundationforfreedomonline.com/wp-content/uploads/2023/03/FFO-FLASH-REPORT-REV.pdf

## Traceback

This is the complete Traceback I see:

TODO

see https://github.com/internetarchive/iari/issues/753

**Comment by MartinThoma** [comment]
@dpriskorn PyPDF2 is deprecated. Use pypdf.

As long as code or pdf are missing, I'll close it. We can reopen when the necessary information is added
