### ISSUE TITLE
How to skip Tables and Images when parse PDF?

### ISSUE THREAD

**Issue by Ontheroad123** [py-pdf/pypdf#1813]
When i parse PDF files, i want to skip Tables and Images in PDF, because they may disrupt paragraph structure

## Environment
$ python -m platform
# TODO: Linux-5.15.0-69-generic-x86_64-with-debian-bullseye-sid

$ python -c "import pypdf;print(pypdf.__version__)"
# TODO: 3.8.1
```

## Code + PDF

```python
# TODO: 
from pypdf import PdfReader

book_path = '1.pdf'
page_info = []
pdf_reader = PdfReader(book_path)
for i in range(len(pdf_reader.pages)):
    page = pdf_reader.pages[i]
    text = page.extract_text()
    if text.strip():
        page_info.append(text)
with open('1.txt', 'w', encoding='utf-8') as fp:
    fp.writelines(page_info)
    fp.close()
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
[1.pdf](https://github.com/py-pdf/pypdf/files/11328536/1.pdf)

When parse this pdf file causes paragraph structure to break when parsing tables on the third page,
Parse txt : [1.txt](https://github.com/py-pdf/pypdf/files/11328679/1.txt)
The third page of paragraphs is out of order.

**Comment by pubpub-zz** [comment]
@Ontheroad123 
can you simplify your test focusing on one page only : I can not read chinese easily...

**Comment by Ontheroad123** [comment]
@pubpub-zz  Thank you for your response, i have test the PDF file on page 3, 
![2023-04-27 08-07-16 的屏幕截图](https://user-images.githubusercontent.com/31181026/234727975-67d216fd-35d1-4e33-b070-b5ab96b009f2.png)
And the result is, 
![2023-04-27 08-09-04 的屏幕截图](https://user-images.githubusercontent.com/31181026/234728103-a0371826-79d9-469c-95e9-95d4dd282b0c.png)
The complete result is 
[1.txt](https://github.com/py-pdf/pypdf/files/11338263/1.txt)

The problem: The correct order is to parse the left column first, then the right column, but this page parses the right column first and then the left column, and the left column starts with Table 2 and Table 3, and other page parsing is normal. I'm looking forward to your reply.

**Comment by Ontheroad123** [comment]
@pubpub-zz  Thank you for your response, i have test the PDF file on page 3, 
![2023-04-27 08-07-16 的屏幕截图](https://user-images.githubusercontent.com/31181026/234727975-67d216fd-35d1-4e33-b070-b5ab96b009f2.png)
And the result is, 
![2023-04-27 08-09-04 的屏幕截图](https://user-images.githubusercontent.com/31181026/234728103-a0371826-79d9-469c-95e9-95d4dd282b0c.png)
The complete result is 
[1.txt](https://github.com/py-pdf/pypdf/files/11338263/1.txt)

The problem: The correct order is to parse the left column first, then the right column, but this page parses the right column first and then the left column, and the left column starts with Table 2 and Table 3, and other page parsing is normal. I'm looking forward to your reply.
