### ISSUE TITLE
Deprecate PdfMerger

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1824]
I think there is no reason left to use PdfMerger. We should get rid of it, following [the deprecation process](https://pypdf.readthedocs.io/en/latest/dev/deprecations.html).

Looking at how it is used:

* https://stackoverflow.com/search?q=PdfFileMerger+%5Bpython%5D
* https://stackoverflow.com/search?q=PdfMerger+%5Bpython%5D

What does this include:

* Removing it from the docs: https://pypdf.readthedocs.io/en/latest/modules/PdfMerger.html
* It's already removed from the user guide: https://pypdf.readthedocs.io/en/latest/user/merging-pdfs.html

Does anybody have objections?

**Comment by MartinThoma** [comment]
I want this to get started before `pypdf == 4.0.0` so that we can fully remove it in `5.0.0`.

**Comment by pubpub-zz** [comment]
without feedbacks I think we should engage depreciation process.
at first glance just PdfMerger should be identified as depreciated

**Comment by kavdev** [comment]
For future onlookers, migrating _can be_ as simple as changing the class from `PdfMerger` to `PdfWriter` ([docs](https://pypdf.readthedocs.io/en/latest/user/merging-pdfs.html#basic-example)).
