### ISSUE TITLE
Add spaces to page.extract_text() output concatination

### ISSUE THREAD

**Issue by damasch** [py-pdf/pypdf#1830]
If the method `page.extract_text()` is used.
The extracted text has no white spaces.

Actual output from the sample.pdf:
```
Text FormattingInline formattingHere, we demonstrate various types of inline text formatting and the use of embedded fonts.
```

There are missing whitespaces.
```
Text FormattingInline formattingHere, we demonstrate various types of inline text formatting and the use of embedded fonts.
               ^                ^
```

Expecting:
```
Text Formatting 
Inline formatting 
Here, we demonstrate various types of inline text formatting and the use of embedded fonts.
```
Or Minimum:

Expecting:
```
Text Formatting Inline formatting Here, we demonstrate various types of inline text formatting and the use of embedded fonts.
```

## Environment

```bash
$ python -m platform
macOS-13.2.1-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.0.1
```

## Code + PDF

```python
from PyPDF2 import PdfReader

reader = PdfReader("sample.pdf")

for page_num in range(len(reader.pages)):
      page = reader.pages[page_num]
      text = page.extract_text()
```
### Sample

[sample.pdf](https://github.com/py-pdf/pypdf/files/11394072/sample.pdf)

## Solution

In lines:

https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1658
https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1664
https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1696
https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1720
https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1833
https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1854
https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1868

There is a concatination without whitespaces.

```python
output += text 
```

If you change the code into this:

```python
output += " " + text 
```

The new output will be:

```
      Text Formatting   Inline formatting   Here, we demonstrate various types of inline text formatting and the use of    embedded fonts.
```

Maybe change the return value to:

https://github.com/py-pdf/pypdf/blob/23d81ff10a1a1749abff401f2b89b33a12c7da06/pypdf/_page.py#L1871

```python
return output.strip()
```
The text result will be:

```
Text Formatting   Inline formatting   Here, we demonstrate various types of inline text formatting and the use of    embedded fonts.
```

There are allready uneccessary whitespaces but better result as before.

**Comment by pubpub-zz** [comment]
the modification is not so simple because il will add extra space in numerous document. adding space criteria should rely on text width calculation. 
for information ,a bench mark measures the quality of the text extraction

**Comment by pubpub-zz** [comment]
White space are adressed in issue #1507 
I will add the test to group all the possible tests.

**Comment by pubpub-zz** [comment]
@MartinThoma
I propose to close this PR as not planned
