### ISSUE TITLE
ValueError when running PdfReader.outline

### ISSUE THREAD

**Issue by CactusJackFX** [py-pdf/pypdf#1832]
When I go to get the Bookmarks from this PDF I get the following error message: 
ValueError: not enough values to unpack (expected 3, got 1)

I have attached a copy of the code on how I opened up the file along with the error and where numbers on where the errors where it's happening. I can't attach a copy of the PDF yet, but I will work on it.

[ValueError.txt](https://github.com/py-pdf/pypdf/files/11401038/ValueError.txt)

**Comment by pubpub-zz** [comment]
@CactusJackFX 
Can you please precise the version you are using
also if you prefer you can send the document privately to @MartinThoma [info@martin-thoma.de](mailto:info@martin-thoma.de)

**Comment by CactusJackFX** [comment]
I'm currently using version 3.8.1. I just upgraded to that one from version 3.4.0, and I'm still getting the same error. I will work on getting approval to send you one of the two documents that I have that are currently getting that error message.

**Comment by CactusJackFX** [comment]
I'm not able to provide a copy of the PDF due to PII, but I did find this when reviewing the document deeper.

![image](https://github.com/py-pdf/pypdf/assets/29522086/f8df1cc3-d67e-450c-8a60-931b02cad54e)

So it might be the security is causing the issue in not reading the bookmarks.

**Comment by pubpub-zz** [comment]
I cannot come to any conclusion without the pdf
Subsequently I will close this issue

**Comment by xrkk** [comment]
I run into this same problem. check this pdf please: https://github.com/xrkk/tmpppppp/tree/main

PyPDF2 version：3.0.1

**Comment by pubpub-zz** [comment]
please upgrade to pypdf  and to latest update. PyPDF2 is depreciated.

**Comment by CactusJackFX** [comment]
I get the same error message on pypdf version 3.8.1 using the sample PDF that xrkk provided.

PDF Splitter Version: 1.2.3 last changed on: 05/15/2023 using PyPDF version 3.8.1.

not enough values to unpack (expected 3, got 2)
File: C:\Input\2021 ---- book - Security of biquitous Computing Systems.pdf can't read bookmarks from source pdf file.

**Comment by pubpub-zz** [comment]
I've found the issue : the last parameter (zoom) in XYZ destination is optional. The code forgot that. a PR has been produced

**Comment by MartinThoma** [comment]
Thank you @pubpub-zz for taking care of this issue <3

**Comment by MartinThoma** [comment]
The PR was just merged and will be part of pypdf > 3.8.1. I will make the release on Sunday.
