### ISSUE TITLE
Processing PDF file through pypdf breaks all internal links

### ISSUE THREAD

**Issue by controversial** [py-pdf/pypdf#1833]
When I use pypdf to process a PDF exported from Chrome, all the internal links in the document are broken (even links within a single page).

Note that the uploaded file `uncropped.pdf` is full of internal links which link to other parts of the document. After running the script, none of the links in the output PDF `out.pdf` work (tested in Preview on macOS).

I’m trying to use pypdf to crop the pages, but the links break even when no manipulation is performed.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# macOS-13.4-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
# 3.8.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfWriter, PdfReader

reader = PdfReader("uncropped.pdf")
writer = PdfWriter()

for page in reader.pages:
    writer.add_page(page)

with open("out.pdf", "wb") as fp:
    writer.write(fp)
```

**Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!**

[uncropped.pdf](https://github.com/py-pdf/pypdf/files/11401477/uncropped.pdf)
(you’re welcome to add this to tests if it’s helpful)

This PDF is exported from Chrome using Puppeteer, and contains numerous internal links (both within pages and between pages).

**Comment by pubpub-zz** [comment]
PDF links are at least pointing to page objects, or at least uses name destination . adding page per page will not work. You should use `append()` or directly at creating with `PdfWriter(clone_from=...)`:
```
from pypdf import PdfWriter

writer = PdfWriter(clone_from="uncropped.pdf")

writer.write("out.pdf")
```

**Comment by controversial** [comment]
This works! Thank you!
