### ISSUE TITLE
Support UTF-16-LE strings

### ISSUE THREAD

**Issue by adamchainz** [py-pdf/pypdf#1838]
pypdf current decodes UTF-16-BE (big endian) strings automatically: https://github.com/py-pdf/pypdf/blob/6fe1c307c7d19edca34b522ed6912bf4b620289c/pypdf/generic/_utils.py#L147-L150 . However, it does not do UTF-16-LE (little endian) strings. A project I'm working on encountered a PDF "in the wild" with UTF-16-LE strings, which needed extra handling.

The UTF-16-BE handling dates back to the initial commit: https://github.com/py-pdf/pypdf/blob/c59a212a4cda512c184a987312970b464404d17b/PyPDF2/generic.py#L253-L256 . Could it be an oversight that LE is not handled?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -V
Python 3.11.2

$ python -m platform
macOS-13.3.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.8.1
```

## Code + PDF

The PDF came with this byte string in its creator field:

```python
b'\xff\xfeP\x00a\x00p\x00e\x00r\x00P\x00o\x00r\x00t\x00 \x001\x004\x00\x00\x00'
```

In my tests, I could recreate the issue with:

```python
from pypdf import *
from pypdf.generic import *

info = DocumentInformation()
info[NameObject("/Creator")] = create_string_object(
    b'\xff\xfeP\x00a\x00p\x00e\x00r\x00P\x00o\x00r\x00t\x00 \x001\x004\x00\x00\x00'
)
```

I'm afraid I'm unable to share the exact PDF since it contains private information.

## Traceback

n/a - depends on how you read the field with the byte string like `creator_raw`.

**Comment by pubpub-zz** [comment]
Can you please provide the pdf for analysis

**Comment by pubpub-zz** [comment]
If you agree you can send the document privately to @MartinThoma info@martin-thoma.de

**Comment by pubpub-zz** [comment]
The PDF standard states that the string are encoding with UTF-16BE.
You should just need to decode the binary string using `.decode("utf-16")`

**Comment by pubpub-zz** [comment]
@MartinThoma 
I propose to close this PR

**Comment by adamchainz** [comment]
I don’t really understand the contents of the problematic document (it’s in German). I have asked the person responsible at my client if it is okay to share. If they say yes, I will email it to you.

Thanks for clarifying that the PDF standard specifies the endianness. I guess this document may have been generated by a faulty tool. Other tools like macOS preview have no trouble reading it though, so they may support LE…

**Comment by pubpub-zz** [comment]
The point is to not complexify pypdf for a too much specific case. 
Can you send the file to @MartinThoma  info@martin-thoma.de
I will have a quick review about

**Comment by adamchainz** [comment]
I am afraid I don't have permission to send you the PDF, as it contains sensitive data.

**Comment by pubpub-zz** [comment]
Can you try this mod in line pypdf/pypdf/generic/_utils.py(147): 
                if string.startswith(codecs.BOM_UTF16_BE) or string.startswith(codecs.BOM_UTF16_LE):

**Comment by MartinThoma** [comment]
Let's open this again - if you (@adamchainz ) can make the change suggested by  @pubpub-zz + confirm it solves the issue, we might make a PR for it :-)

**Comment by pubpub-zz** [comment]
@adamchainz 
any update?

**Comment by pubpub-zz** [comment]
@adamchainz
any update?

**Comment by adamchainz** [comment]
No sorry - I will be back working with that client next week and can check then. Thank you for your patience.

**Comment by pubpub-zz** [comment]
@adamchainz  +1 ?

**Comment by adamchainz** [comment]
Sorry for the delay again, family issue. It works with the naughty PDF, and I have made PR #1884 with the fix and some tests for `create_string_object`.
