### ISSUE TITLE
invalid pdf header: in adobe pdf

### ISSUE THREAD

**Issue by happyWheel2047** [py-pdf/pypdf#1840]
I have the following bugs when reading this file. What should I do? 

https://www.elegislation.gov.hk/hk/cap622!en.pdf

WARNING:pypdf._reader:invalid pdf header: b'\r\n\r\n\r'
WARNING:pypdf._reader:EOF marker not found

**Comment by MartinThoma** [comment]
Those are warnings, not errors. And certainly this is no bug of pypdf. See https://pypdf.readthedocs.io/en/latest/user/suppress-warnings.html
