### ISSUE TITLE
Where are B's?

### ISSUE THREAD

**Issue by CorinneSP** [py-pdf/pypdf#1862]
I'm using PdfWriter to merge some PDF files:

```python
from pypdf import PdfWriter
merger = PdfWriter()

for name in name:
        merger.append(f'{directory}/{name}.pdf')
        merger.write(f'{directory}/{resultname}')
        merger.close()
```

It all works fine but in the final result there are no B (only capital B): [2023-05-09.pdf](https://github.com/py-pdf/pypdf/files/11578126/2023-05-09.pdf)

Single pdfs are fine, the y-axis shown in them is called "Blood pressure". But in the complete file is "_lood pressure"

**Comment by MasterOdin** [comment]
Are you able to attach a PDF that shows this problem?

**Comment by CorinneSP** [comment]
Here it is! Hoping you could help us.

Il giorno ven 26 mag 2023 alle ore 18:14 Matthew Peveler <
***@***.***> ha scritto:

**Comment by MasterOdin** [comment]
Doesn't look like it got attached? I think you'll need to go through the web UI to do it ([docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)).

**Comment by CorinneSP** [comment]
[2023-05-09.pdf](https://github.com/py-pdf/pypdf/files/11578126/2023-05-09.pdf)
What about now? (Sorry  new i made a bit of mess)

**Comment by MasterOdin** [comment]
Yup, can see the PDF, thanks! 👍

**Comment by CorinneSP** [comment]
Its a parameter, just the name of the final pdf which is the one i provide, so its an output

**Comment by pubpub-zz** [comment]
can you provide the input file(s) then ? is the file you've provided a merge of 2 different files?

**Comment by pubpub-zz** [comment]
@CorinneSP 
Any update?

**Comment by CorinneSP** [comment]
Sorry but I can't give you those files, but I wrote a fake code, just to show the issue, you can run and see the differences!
```
import matplotlib.pyplot as plt
from pypdf import PdfWriter

plt.figure()
plt.axis('off')
plt.text(0.5, 0.5, 'BABBLING BUMBLING BAND OF BABOONS', fontsize=20, ha='center')
plt.savefig('./intro.pdf')
plt.close()

merger = PdfWriter()
merger.append('./intro.pdf')

plt.figure()
plt.xlabel("Time")
plt.ylabel("Blood Pressure [mmhg]")
plt.savefig('./graph.pdf')
plt.close()
merger.append('./graph.pdf')

merger.write('./final.pdf')
merger.close()
```
Anyway I solved using PdfMerger, but I think it's still something you should see

**Comment by pubpub-zz** [comment]
(for test)
the input file: 
[intro.pdf](https://github.com/py-pdf/pypdf/files/11708801/intro.pdf)

**Comment by pubpub-zz** [comment]
@CorinneSP 
thanks for your report and your very good example. The "/B" fields were wrongly ignored during the append() process ("/B" have to be ignored during Page duplication but not below)
B's are back with the mod 😁

**Comment by CorinneSP** [comment]
Perfect! Thank you for everything :)

**Comment by pubpub-zz** [comment]
the issue will be closed automatically when the PR will be merged

**Comment by MartinThoma** [comment]
I've just merged the fix provided by @pubpub-zz. It will be released tomorrow :-)
