### ISSUE TITLE
Documentation: Incorrect/missing example for highlighting text annotations

### ISSUE THREAD

**Issue by jamescrowley** [py-pdf/pypdf#1873]
The code example given for highlighting text as an annotation in the documentation (https://pypdf.readthedocs.io/en/stable/user/adding-pdf-annotations.html#highlighting) is incorrect:

https://github.com/py-pdf/pypdf/blob/1f114bafffe92400c2901741018dd0640df42e51/docs/user/adding-pdf-annotations.md?plain=1#L292-L308

It in fact is an exact copy of the preceding "Polygon" example:

https://github.com/py-pdf/pypdf/blob/1f114bafffe92400c2901741018dd0640df42e51/docs/user/adding-pdf-annotations.md?plain=1#L181-L197

As noted in the documentation, highlighting text is "a bit more complicated as you need to know exactly where the text is." - so it would be great to see a working example if possible!

**Comment by pubpub-zz** [comment]
Thanks for the report however, we have engaged some rework (eg. #1745). The documentation will then be obsolete.
This issue will most probably be closed as not planned

**Comment by pubpub-zz** [comment]
I close this issue then
