### ISSUE TITLE
PyPDF2.errors.PdfReadError: PDF starts with '%-12', but '%PDF-' expected

### ISSUE THREAD

**Issue by jrsweetheartbeats** [py-pdf/pypdf#1882]
## Explanation

I need to retrieve the first page from several PDF files.
But when using pypdf2. reader(), I got an error.
after Google's question, I don't have an answer.
I think it's possible that the file version is incorrect?

Therefore, I opened the error file through WPS, which is a PDF software in Cn, and saved .
yeah, the error disappeared.
I searched for this issue on Baidu, but no one discussed it.

**Comment by pubpub-zz** [comment]
@jrsweetheartbeats 
A) PyPDF2 is obsolete
B) please share the pdf for review

**Comment by jrsweetheartbeats** [comment]
[EA-20221231-13.pdf](https://github.com/py-pdf/pypdf/files/11719364/EA-20221231-13.pdf)
tks for review,

**Comment by jrsweetheartbeats** [comment]
> 

but, i've saw this project url in PyPDF2's code

**Comment by MartinThoma** [comment]
I'm the maintainer of pypdf and PyPDF2.

See https://pypi.org/project/PyPDF2/:

> NOTE: The PyPDF2 project is going back to its roots. PyPDF2==3.0.X will be the last version of PyPDF2. Development will continue with [pypdf==3.1.0](https://pypi.org/project/pyPdf/).

**Comment by MartinThoma** [comment]
I don't see any problem. This seems to work fine:

```
from pypdf import PdfReader

reader = PdfReader("EA-20221231-13.pdf")
print(reader.pages[0])
```

@jrsweetheartbeats Please give a minimal, but complete code example that leads to the issue.

**Comment by pubpub-zz** [comment]
@jrsweetheartbeats 
upgrade to latest pypdf may be the solution

**Comment by pubpub-zz** [comment]
@jrsweetheartbeats  can you confirm results from @MartinThoma ? OK to close this issue ?

**Comment by pubpub-zz** [comment]
I close this issue. feel free to ask for reopening if you have new elements
