### ISSUE TITLE
BUG: Transparency is converted to black

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1895]
If I reduce the image quality for https://www.viessmann.de/content/dam/public-brands/master/products/heat-pump/vitocal-200-g/DB-5368770_Vitocal_200-G.pdf/_jcr_content/renditions/original.media_file.download_attachment.file/DB-5368770_Vitocal_200-G.pdf the image on page 2 becomes mostly black

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-150-generic-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf.__version__)"
3.10.0
```

## Code + PDF

PDF: https://www.viessmann.de/content/dam/public-brands/master/products/heat-pump/vitocal-200-g/DB-5368770_Vitocal_200-G.pdf/_jcr_content/renditions/original.media_file.download_attachment.file/DB-5368770_Vitocal_200-G.pdf

```python
from pypdf import PdfReader, PdfWriter

reader = PdfReader("example.pdf")
writer = PdfWriter()

for page in reader.pages:
    writer.add_page(page)

for page in writer.pages:
    for img in page.images:
        img.replace(img.image, quality=80)

with open("out.pdf", "wb") as f:
    writer.write(f)
```

**Comment by pubpub-zz** [comment]
@MartinThoma 
Can you indicate which version of pillow you are using?

**Comment by MartinThoma** [comment]
```
>>> import PIL
>>> PIL.__version__
'9.5.0'
```

That seems to be the latest one: https://pypi.org/project/Pillow/

**Comment by MartinThoma** [comment]
Do you see different behavior @pubpub-zz ?

**Comment by pubpub-zz** [comment]
I suppose this is due to ICCbase color change : Currently trying to find a way to apply it.

**Comment by pubpub-zz** [comment]
May be the source:
https://github.com/python-pillow/Pillow/issues/4860
to be checked

**Comment by pubpub-zz** [comment]
I've got it!
CMYK requires reverting scale (p243 from pdf 1.7 ref):
![image](https://github.com/py-pdf/pypdf/assets/4083478/7b38de51-35ec-4dcd-81f5-3e31c5eaffea)

now the image is correct:
![cmyk](https://github.com/py-pdf/pypdf/assets/4083478/38c5b92c-cf94-473c-bb57-a51b74fc39be)

@MartinThoma can you change title of the issue to "CMYK image requires color inversion"

**Comment by pubpub-zz** [comment]
pdf:
[DB-5368770_Vitocal_200-G.pdf](https://github.com/py-pdf/pypdf/files/11962229/DB-5368770_Vitocal_200-G.pdf)
