### ISSUE TITLE
File Size Increase from pypdf==3.8.1 to pypdf==3.9.0 when watermarking

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1897]
I've noticed that the watermarking process in my job suddenly produces way bigger PDFs. In a specific example with [this PDF file](https://wiwin.de/wp-content/uploads/2023/03/Anlagebroschure-Vogtland-IV.pdf) I've noticed:

* Base is 3.5 MB
* Watermarking with `pypdf==3.8.1` produces a 3.7 MB file
* Watermarking with `pypdf==3.9.0` produces a 5.2 MB file

I'm not sure if the issue is with 3.8.1 or with 3.9.0.

## Code

```python
from pypdf import PdfReader, PdfWriter
import pypdf
from io import BytesIO
from fpdf import FPDF  # pip install fpdf2


def create_stamp_pdf() -> BytesIO:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(40, 10, "Hello World!")
    byte_string = pdf.output()
    return BytesIO(byte_string)


template = PdfReader(create_stamp_pdf())
template_page = template.pages[0]
reader = PdfReader("template.pdf")

writer = PdfWriter()
for page in reader.pages:
    page.merge_page(template_page)
    writer.add_page(page)

for page in writer.pages:
    page.compress_content_streams()

with open(f"out-{pypdf.__version__}.pdf", "wb") as fp:
    writer.write(fp)
```

## Affected versions

It seems to be https://github.com/py-pdf/pypdf/commit/2d67c15d46a0488e619d3cdf24707feb2d92c224 that causes it. So pypdf>=3.9.0.

**Comment by pubpub-zz** [comment]
@MartinThoma 
can you please provide the test code ?

**Comment by MartinThoma** [comment]
Not so far, but I hope I can do it tomorrow :-) It's part of a larger code base. I tried the simple watermarking from the docs, but that didn't show any difference.

I'm currently trying to find the specific commit that causes the change in behavior

**Comment by MartinThoma** [comment]
It seems to be https://github.com/py-pdf/pypdf/commit/2d67c15d46a0488e619d3cdf24707feb2d92c224

**Comment by MT-Cash** [comment]
I could make a minimal example :tada:

```
from pypdf import PdfReader, PdfWriter
import pypdf
from io import BytesIO
from fpdf import FPDF  # pip install fpdf2


def create_stamp_pdf() -> BytesIO:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(40, 10, "Hello World!")
    byte_string = pdf.output(dest="S")
    return BytesIO(byte_string)


template = PdfReader(create_stamp_pdf())
template_page = template.pages[0]
reader = PdfReader("template.pdf")

writer = PdfWriter()
for page in reader.pages:
    page.merge_page(template_page)
    writer.add_page(page)

for page in writer.pages:
    page.compress_content_streams()

with open(f"out-{pypdf.__version__}.pdf", "wb") as fp:
    writer.write(fp)
```

**Comment by MT-Cash** [comment]
So it seems we somehow broke the compression?

**Comment by MT-Cash** [comment]
@Lucas-C For the `create_stamp_pdf` above I get the warning

> DeprecationWarning: "dest" parameter is deprecated, unused and will soon be removed

How should I write to a BytesIO stream instead? Maybe it would be possible to point users directly to what they should use instead?

**Comment by MT-Cash** [comment]
@pubpub-zz I've added the minimal example in the top :-)

**Comment by Lucas-C** [comment]
> How should I write to a BytesIO stream instead? Would it maybe be possible to point users directly to what they should use instead?

Calling `.output()` is fine, it's just the `dest` parameter that is not necesseray, you can simply get rid of it:
https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.output

**Comment by MartinThoma** [comment]
I just tried to find other files that show the same issue:

* `sample-files/009-pdflatex-geotopo/GeoTopo.pdf`: 5.3 MB
* After adding the overlay: 10.9 MB

**Comment by pubpub-zz** [comment]
> It seems to be [2d67c15](https://github.com/py-pdf/pypdf/commit/2d67c15d46a0488e619d3cdf24707feb2d92c224) that causes it. So pypdf>=3.9.0.
I confirm your analysis.
the core problem is identified. solution under building.

**Comment by MartinThoma** [comment]
This might be a useful test:

```
@pytest.mark.samples()
@pytest.mark.slow()
#@pytest.mark.xfail(reason="Issue 1897")
def test_compression():
    def create_stamp_pdf() -> BytesIO:
        from fpdf import FPDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("helvetica", "B", 16)
        pdf.cell(40, 10, "Hello World!")
        byte_string = pdf.output()
        return BytesIO(byte_string)


    template = PdfReader(create_stamp_pdf())
    template_page = template.pages[0]
    reader = PdfReader(SAMPLE_ROOT / "009-pdflatex-geotopo/GeoTopo.pdf")

    writer = PdfWriter()
    for page in reader.pages:
        page.merge_page(template_page)
        writer.add_page(page)

    for page in writer.pages:
        page.compress_content_streams()

    b = BytesIO()
    writer.write(b)
    b.seek(0)
    output_data = len(b.read())
    assert output_data < 6 * 10**6
```

**Comment by MartinThoma** [comment]
@pubpub-zz I think I will make a release with this fix today. I've just updated the first post with a "Issue Summary". I think I will do the same for all new issues. This way it is easier for people to see if/how long they were affected.
