### ISSUE TITLE
python 3.9 PyPDF3 Output chinese decode string

### ISSUE THREAD

**Issue by scs001** [py-pdf/pypdf#1900]
python 3.9 PyPDF3 Output chinese decode string
## Environment
python 3.9 
PyPDF3 

## Code + PDF
code pice:
  for i in range(current_item_page, next_item_page):
      page = reader.pages[i]
      item_text += page.extract_text()
      print("itme", item_text)

response pice:
r'ͦ፽ʮ̡༟ࣘʿ؇ٰ༟ৃ
ʮ̡ᔊʧ
࿲ᚑၾᆤً
˴ࢩజѓ
၍ଣᄴীሞၾʱؓ
ධͦ฿ᚎ
໨ԫʿ৷ॴ၍ଣᄴᔊʧ
Άุ၍طజѓ
໨ԫึజѓ

by the way , i extract  text from a chinese financial report pdf

here is one of the documents
[荣盛发展 2021年年度报告-20220430.pdf](https://github.com/py-pdf/pypdf/files/11811736/2021.-20220430.pdf)

**Comment by MartinThoma** [comment]
PyPDF3 is not pypdf. Please try again with pypdf and update your post.

For the moment, I close it. I will re-open once you tried with the latest `pypdf`
