### ISSUE TITLE
Missing "Size" info in the trailer

### ISSUE THREAD

**Issue by talcher** [py-pdf/pypdf#1901]
Hi,

I use WeasyPrint to create PDF.
I recently upgraded my libraries to WeasyPrint 59.0 and pypdf 3.10.0.

My aim is to get the trailer of a PDF I created with WeasyPrint. In this trailer, I need the "Size" field, among others.

Previously, I got something like:
```python
{'/Size': 14, '/Root': IndirectObject(3, 0, 140016423632752), '/Info': IndirectObject(2, 0, 140016423632752)}
```
Now, I get something like:
```python
{'/Root': IndirectObject(3, 0, 140470815616880), '/Info': IndirectObject(2, 0, 140470815616880)}
```

If I force WeasyPrint to create a 1.4-versioned PDF, I get the trailer I expect.
However, this is not what I want. It would be much better not to force the 1.4 version.

## Environment

- OS: Debian 11
- Python: 3.9.2
- WeasyPrint: 59.0
- PyPDF: 3.10.0

## Code + PDF

```python
from pypdf import PdfReader

reader = PdfReader("example.pdf")
trailer = reader.trailer.get_object()
```

Here are two PDF samples:
- no version forced : [hello.pdf](https://github.com/py-pdf/pypdf/files/11818298/hello.pdf)
-  1.4 version forced : [hello_1.4.pdf](https://github.com/py-pdf/pypdf/files/11817365/hello_1.4.pdf)

## Suggestion

I have had a look at pypdf source code.
Correct me if I am wrong, but I think my issue is related to the "_read_xref_tables_and_trailers" function of the [reader class](https://pypdf.readthedocs.io/en/stable/_modules/pypdf/_reader.html), where trailer keys are defined that way: "trailer_keys = TK.ROOT, TK.ENCRYPT, TK.INFO, TK.ID"

If you need some more information, I would be glad to provide them.
Thank you for your help.

Alcher

**Comment by pubpub-zz** [comment]
Your analysis looks correct and I agree that TK.SIZE could be added to the list : the value is mandatory, as as part of the list, it will not be overwritten by old trailers.
Can you propose a PR and add a test to check the field is correctly extracted ?

**Comment by talcher** [comment]
Hello,
I just proposed a PR. Automatic checks have been successful.
Is that all you need? Sorry, I am a kind of a noob with GitHub workflows...

**Comment by MartinThoma** [comment]
Thank you for your input @talcher :pray: Yes, this is all we need for the moment :-)
