### ISSUE TITLE
Watermarking pdf: copy TOC/outline from source to destination

### ISSUE THREAD

**Issue by philipaxer** [py-pdf/pypdf#1902]
## Explanation

The documentation gives an example how to watermark a pdf. While this works, the outlines of the original PDF is lost. Usually technical documenation is watermarked and the outlines are quite helpful to navigate the document. How can i carry over the outline from the source PDF to the destination?

**Comment by pubpub-zz** [comment]
you should be able to first load (using `clone_from=` within the PdfWriter constructor) your pdf file or using `.append()`.
Within the PdfWriter you should be able to loop through the page and use https://pypdf.readthedocs.io/en/stable/modules/PageObject.html#pypdf._page.PageObject.merge_page to apply the watermark. 
Can you test this approach?

**Comment by pubpub-zz** [comment]
@philipaxer +1?

**Comment by philipaxer** [comment]
Hi, thanks for the suggestion. That has worked nicely, all meta data is carried over.

**Comment by pubpub-zz** [comment]
Would you be ok to propose a PR to update the documentation to present the solution?

**Comment by pubpub-zz** [comment]
#1952 has updated the documentation. we can close this issue
