### ISSUE TITLE
Error occurred when appending PDF

### ISSUE THREAD

**Issue by b232wang** [py-pdf/pypdf#1905]
Replace this: What happened? What were you trying to achieve?

## Environment

```
$ python -m platform
macOS-13.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
# 3.2.1
```

## Code + PDF

```python

from pypdf import PdfWriter

output = PdfWriter()
output.append(“example.pdf”)

```

`example.pdf`: https://drive.google.com/file/d/1Wn36s-r1OZpe9ZNWMlGgJNUBmT3Ft6pk/view?usp=sharing
## Traceback

```
raise PdfReadError(
pypdf.errors.PdfReadError: Invalid Elementary Object starting with b'>' @52314: b'13 0.11 0.09 0.04 ]\n>> ]\nendobj\n23 0 obj\n[ /ICCBased 24 0 R ]\nendobj\n24 0 obj\n<<'
```

**Comment by pubpub-zz** [comment]
@b232wang,
your file is corrupted on 4th page. and can not be read with Acrobat Reader. 
you still can append other pages:
```
output.append("example.pdf",(0,3))
output.append("example.pdf",(5,15))
```

this is not an issue in pypdf. I close this issue
