### ISSUE TITLE
Collapsed-by-default outline tree

### ISSUE THREAD

**Issue by Mark-SLDE** [py-pdf/pypdf#1922]
## Explanation

The outline tree is expanded by default. Child bookmarks are shown. This isn't preferred....(by me).

## Code Example

I've been using PdfWriter.add_outline_item(). I've had no issues using it but can't find any options to collapse the tree

Explained here: https://stackoverflow.com/a/76567193/3631901

pypdf/generic/_data_structures.py, Class TreeObject, def insert_child
```python
if "/Count" in parent:
                parent[NameObject("/Count")] = NumberObject(
                    cast(int, parent[NameObject("/Count")]) + n
                )
                inc_parent_counter(parent.get("/Parent", None), n)

```

becomes

```python
if "/Count" in parent:
                parent[NameObject("/Count")] = NumberObject(0)
                inc_parent_counter(parent.get("/Parent", None), n)
```

I've done very little testing and I've no idea if this is a preferred implementation. It clearly also needs some arguments to drive the configuration option.
Thanks

**Comment by MartinThoma** [comment]
Interesting. Citing from the docs (Table 152 – Entries in the outline dictionary ; "/Count"):

```
(Required if the document has any open outline entries) Total number
of visible outline items at all levels of the outline. The value cannot be
negative.
This entry shall be omitted if there are no open outline items.
``

**Comment by MartinThoma** [comment]
I can see that some people might want to modify this.

Adding an option to easily switch if an outline item is open or closed might be the best way to go. Maybe we could just add an "is_open" property to the `TreeObject`? By default it's set to "True" (current behavior; I believe most people want this). But people could descend the outline tree and change the behavior per-node without having to know PDF specifics.

By the way, I'm rather certain you could achieve the same with user code without modifying pypdf. But I can see that changing this would be beneficial.

**Comment by MartinThoma** [comment]
PyMuPDF has "is_open": https://pymupdf.readthedocs.io/en/latest/outline.html#Outline.is_open

**Comment by Mark-SLDE** [comment]
Thanks for taking a look at this.
Can't work out if `TreeObject` is the object returned by `add_outline_item()`.....what's the `IndirectObject`? A copy of the `TreeObject`?

My preference would be an optional argument in `add_outline_item()` or perhaps some manipulation of the returned `IndirectObject` that I could do on the following line.

**Comment by pubpub-zz** [comment]
> Thanks for taking a look at this. Can't work out if `TreeObject` is the object returned by `add_outline_item()`.....what's the `IndirectObject`? A copy of the `TreeObject`?

IndirectObject is a "pointer" to the object : to access the TreeObject just use `.get_object()`


> My preference would be an optional argument in `add_outline_item()` or perhaps some manipulation of the returned `IndirectObject` that I could do on the following line.

this will have to be appended at the end of parameters:
```
    def add_outline_item(
        self,
        title: str,
        page_number: Union[None, PageObject, IndirectObject, int],
        parent: Union[None, TreeObject, IndirectObject] = None,
        before: Union[None, TreeObject, IndirectObject] = None,
        color: Optional[Union[Tuple[float, float, float], str]] = None,
        bold: bool = False,
        italic: bool = False,
        fit: Fit = PAGE_FIT,
        collapsed: bool = False,               #    <--------- 
        pagenum: Optional[int] = None,  # deprecated
    ) -> IndirectObject:
```

I propose also to complete the API with a new function to modify existing outlines

```
# for all parameters None means unchanged
def set_outline(self, outline: Union[TreeObject, IndirectObject], 
                              title: optional[str] = None, 
                              color: Union[None, ArrayObject, Tuple[int, int, int]] =None,  
                              bold: Optional[bool] = False, 
                              italic: Optional[bool]=False, 
                              dest_or_action : Union[None, DictionaryObject, IndirectObject, DestinationObject]  = None,  
                              collapsed : Optional[bool] = None,
                        ) -> IndirectObject:                           
```

@MartinThoma  your opinion ?

**Comment by MartinThoma** [comment]
For the moment, I would prefer to only modify `add_outline_item` to become:

```python
    def add_outline_item(
        self,
        title: str,
        page_number: Union[None, PageObject, IndirectObject, int],
        parent: Union[None, TreeObject, IndirectObject] = None,
        before: Union[None, TreeObject, IndirectObject] = None,
        color: Optional[Union[Tuple[float, float, float], str]] = None,
        bold: bool = False,
        italic: bool = False,
        fit: Fit = PAGE_FIT,
        pagenum: Optional[int] = None,  # deprecated
        *,  # make the following keyword-only:
        is_open: bool = True,
    ) -> IndirectObject:
```

I would accept/merge such an extension pretty quickly.

## Future stuff that needs more discussion

Regarding the `set_outline` I don't quite understand yet how that should work / where that should be. Should it be directly on PdfWriter?

On the long run, I would prefer a property `outline` on the PdfWriter and PdfReader. It should be a list-like object. Every entry should be an OutlineItem with a `is_open` property (and other stuff).

On a first thought that sounds like the best user experience.
