### ISSUE TITLE
null / blank data while extracting text from pdf

### ISSUE THREAD

**Issue by edingha** [py-pdf/pypdf#1937]
Replace this: What happened? What were you trying to achieve?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# python -m platform

$ python -c "import pypdf;print(pypdf.__version__)"
# 3.11.1
```

## Code + PDF
import pypdf

pdf_path = "~/file.pdf"

with open(pdf_path, "rb") as file:
    pdf_reader = pypdf.PdfReader(file)
    page = pdf_reader.pages[5]  # Extract text from the first page

    extracted_text = page.extract_text()
    print(extracted_text)
   
[1.pdf](https://github.com/py-pdf/pypdf/files/11929986/1.pdf)

This is a minimal, complete example that shows the issue:

```python
# TODO: Your code goes here
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete Traceback I see:

TODO

**Comment by pubpub-zz** [comment]
This PDF is an image, and does not contains text. the only option is to use an OCR such as `pytesseract`

**Comment by MartinThoma** [comment]
https://pypdf.readthedocs.io/en/latest/user/extract-text.html#ocr-vs-text-extraction
