### ISSUE TITLE
Need to run code twice to see filled fields.

### ISSUE THREAD

**Issue by kubaPod** [py-pdf/pypdf#1944]
Field values are no displayed unless I run the code twice. 
By twice I mean run the code once, verify empty .pdf (fields. /V are set though), then ran again from the comment marker, now fields are filled.

This happens for that specific file, I was able to fill another form in a single run.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.19045-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.12.0
```

I am running this code via jupyterlab notebook:

```
Version 3.6.3
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
reader = PdfReader("./visa-form.pdf")

# start second run from here
writer = PdfWriter()
writer.append(reader)

writer.update_page_form_field_values(
    reader.pages[0],
    {"1 Surname" : "TEST"},
    auto_regenerate = False # this is irrelevant to the issue
)

with open("filled-out-visa.pdf", "wb") as output_stream:
    writer.write(output_stream) 

```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

[visa-form.pdf](https://github.com/py-pdf/pypdf/files/11955250/visa-form.pdf)

## Traceback

This is the complete Traceback I see:

no traceback

TODO

**Comment by pubpub-zz** [comment]
your code shows a mistake: you should refer the page from the writer not from the reader ; try this (I've also added other proposal to simplify the code)
```
# start second run from here
writer = PdfWriter()
writer.append("./visa-form.pdf")

writer.update_page_form_field_values(
    writer.pages[0],                # <- source of the issue for me
    {"1 Surname" : "TEST"},
    auto_regenerate = False 
)

writer.write("filled-out-visa.pdf") 
```

**Comment by kubaPod** [comment]
@pubpub-zz thank you! And sorry for that issue.
