### ISSUE TITLE
Differences in the method extract_text between the latest version v3.12.1 and the old v1.28.6 version

### ISSUE THREAD

**Issue by visomi-dev** [py-pdf/pypdf#1966]
I have two issues with the version of the library 3.1. With version 1.28 the script I made works correctly but if I migrate the code to the latest version my program not working because the text I get from the extract_text function is different from v1.28, with the previous version the footer and header were ignored automatically, and the format of the text I obtained corresponded to the sections that can be observed. Now with the version 3.1 the extract_text method returns the header, footer and the text have an erroneous format that can be seen.

## Environment

Which environment where you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

$ python -c "import pypdf;print(pypdf.__version__)"
3.12.1
```

## Code + PDF

This is my working code with the 1.28.6 version.

```python
import os
import re
import pandas as pd
from PyPDF2 import PdfFileReader

assets_dir_path = os.path.join(os.path.dirname(
    os.path.realpath(__file__)), 'assets',
)

unwanted_text_start = """
Detalle de Movimientos Realizados
FECHA
SALDO
OPER
LIQ
DESCRIPCION
REFERENCIA
CARGOS
ABONOS
OPERACION
LIQUIDACION
"""
unwanted_text_end = """
Total de Movimientos
TOTAL IMPORTE CARGOS
"""

regex = r"(\d{2}/[A-Z]{3}\n\d{2}/[A-Z]{3}\n.*?)(?=\d{2}/[A-Z]{3}\n\d{2}/[A-Z]{3}\n|$)"


def extract_text_from_pdf(file_name):
    with open(os.path.join(assets_dir_path, file_name + '.pdf'), "rb") as file:
        pdf_reader = PdfFileReader(file)
        text = ""

        for page in range(pdf_reader.getNumPages()):
            text += pdf_reader.getPage(page).extractText()

        with open(os.path.join(assets_dir_path, file_name + '.txt'), 'w') as f:
            f.write(text)

    return text


def extract_hour(row):
    match = re.search(r'\b(\d{2}:\d{2})\b', row['Details'])
    return match.group(1) if match else ""


def convert_amount(row):
    amount = float(row['Amount'].replace(',', ''))

    if "retiro" in row['Operation'].lower() or "rfc" in row['Details'].lower() or row['Operation'] == "RECARGAS Y PAQUETES BMOV" or "SPEI ENVIADO" in row['Operation']:
        return -abs(amount)
    else:
        return amount


def extract_data(file_name):
    text_content = extract_text_from_pdf(file_name)
    clean_text = text_content.split(
        unwanted_text_start, 1)[-1].split(unwanted_text_end, 1)[0]
    matches = re.findall(regex, clean_text, re.DOTALL)
    dates, operations, amounts, details = [], [], [], []

    for match in matches:
        lines = match.split("\n")
        dates.append(lines[0])
        operations.append(lines[2])
        amounts.append(lines[3])
        details.append(" ".join(lines[4:]).strip())

    df = pd.DataFrame({
        "Date": dates,
        "Operation": operations,
        "Amount": amounts,
        "Details": details,
    })

    df['Hour'] = df.apply(extract_hour, axis=1)
    df['Date'] = df['Date'] + " " + df['Hour']
    df = df.drop(columns=['Hour'])

    df['Amount'] = df.apply(convert_amount, axis=1)

    df.to_csv(os.path.join(assets_dir_path, file_name + '.csv'), index=False)

    return df


extract_data('bank_account_statement')
```

This is the new code:

```python
import os
import re
import pandas as pd
from pypdf import PdfReader

assets_dir_path = os.path.join(os.path.dirname(
    os.path.realpath(__file__)), 'assets',
)

unwanted_text_start = "FECHA SALDO OPER LIQ DESCRIPCION REFERENCIA CARGOS ABONOS OPERACION LIQUIDACION"
unwanted_text_end = "TOTAL IMPORTE CARGOS"

regex = r"(\d{2}/[A-Z]{3}\n\d{2}/[A-Z]{3}\n.*?)(?=\d{2}/[A-Z]{3}\n\d{2}/[A-Z]{3}\n|$)"


def extract_text_from_pdf(file_name):
    with open(os.path.join(assets_dir_path, file_name + '.pdf'), "rb") as file:
        pdf_reader = PdfReader(file)
        text = ""

        for page in range(len(pdf_reader.pages)):
            text += pdf_reader.pages[page].extract_text()

        with open(os.path.join(assets_dir_path, file_name + '.txt'), 'w') as f:
            f.write(text)

    return text


def extract_hour(row):
    match = re.search(r'\b(\d{2}:\d{2})\b', row['Details'])
    return match.group(1) if match else ""


def convert_amount(row):
    amount = float(row['Amount'].replace(',', ''))

    if "retiro" in row['Operation'].lower() or "rfc" in row['Details'].lower() or row['Operation'] == "RECARGAS Y PAQUETES BMOV" or "SPEI ENVIADO" in row['Operation']:
        return -abs(amount)
    else:
        return amount


def extract_data(file_name):
    text_content = extract_text_from_pdf(file_name)
    clean_text = text_content.split(
        unwanted_text_start, 1)[-1].split(unwanted_text_end, 1)[0]
    matches = re.findall(regex, clean_text, re.DOTALL)
    dates, operations, amounts, details = [], [], [], []

    for match in matches:
        lines = match.split("\n")
        dates.append(lines[0])
        operations.append(lines[2])
        amounts.append(lines[3])
        details.append(" ".join(lines[4:]).strip())

    df = pd.DataFrame({
        "Date": dates,
        "Operation": operations,
        "Amount": amounts,
        "Details": details,
    })

    df['Hour'] = df.apply(extract_hour, axis=1)
    df['Date'] = df['Date'] + " " + df['Hour']
    df = df.drop(columns=['Hour'])

    df['Amount'] = df.apply(convert_amount, axis=1)

    df.to_csv(os.path.join(assets_dir_path, file_name + '.csv'), index=False)

    return df


extract_data('bank_account_statement')
```

I cannot upload the PDF because it is a bank account statement, if you like send a PM and share it to a member

## Traceback

Most of the problems are because now it parses differently and I get the text in a different format than the v1, for example before with v1.28 omits by default the header and footers, now not and when I try to remove them with the function visitor_text does not work as expected, the detection of the texts does not match. Other of the problems are with the text parse, when I previously get a text like this:

Detalle de Movimientos Realizados
FECHA
SALDO
OPER
LIQ
DESCRIPCION
REFERENCIA
CARGOS
ABONOS
OPERACION
LIQUIDACION

Now I get the text:

FECHA SALDO OPER LIQ DESCRIPCION REFERENCIA CARGOS ABONOS OPERACION LIQUIDACION

With this I do not have much problem, but everything begins to complicate when previously I had texts like this: 

05/JUN
05/JUN
STRIPE*UBER TRIP
40.13
XXX
ZZZZZZZ
YYYY
05/JUN
05/JUN
STRIPE*UBER TRIP
41.13
ZZZZZZZ

YYYY

And now the text is:

05/JUN 05/JUN STRIPE*UBER TRIP 40.13 XXXX

Sometimes the transactions showing like this:

05/JUN 05/JUN STRIPE*UBER TRIP 40.13XXXX ZZZ

Somethings showing like this:

05/JUN 05/JUN STRIPE*UBER TRIP 40.13 XXXX
    ZZZ

But before always are in the same format:

05/JUN
05/JUN
STRIPE*UBER TRIP
40.13
XXX
ZZZZZZZ
YYYY
05/JUN
05/JUN
STRIPE*UBER TRIP
41.13
ZZZZZZZ

Also, with version 1.28 I did not get the headers or footers of the document but now if I return them.

I don't find in the documentation some reason this occurs.
Can you help me guide me in the right path?

**Comment by MartinThoma** [comment]
> before with v1.28 omits by default the header and footers

That was a coincidence as text extraction was pretty bad back then.

Do I understand you correctly that "Nothing works" means "I get can extract text, but not the way I want"?

**Comment by visomi-dev** [comment]
yes sorry yellow journalism, I changed it, in effect I meant that I get the text, but not in the way I did in version 1.28 and I would like to be able to get the text of my PDF in the same way I did before in the most recent version.

**Comment by visomi-dev** [comment]
Thanks to the comment of @MartinThoma made me realize that now with the functionality of visitor_text I can customize my code even more to obtain the desired result, it will take more work on my part but if it is the right way I will make the modifications in my code
