### ISSUE TITLE
Extract subscripts / superscripts

### ISSUE THREAD

**Issue by malinphy** [py-pdf/pypdf#1976]
PyPDF loader is a great tool. However, I am having a problem extracting the chemical formulas with subscripts. For example 
H<sub>2</sub>O is extracted as \nHO \2. Is there any way to fix this issue? (Maybe with visitor functions) Thanks in advance.
Best regards

**Comment by malinphy** [comment]
> PDF is a electronic printing format where "glyphs" are printed at defined positions with defined size. subscripts are not always printed in the good order. You can try with visitors, but it may be tricky.

Thanks for the advice. Do you have any idea what should be changed, which parameters should be tricked?

**Comment by pubpub-zz** [comment]
no ideas...😞

**Comment by MartinThoma** [comment]
I'm closing this issue, because I don't know how we could tackle this. It's a good question and a desirable result, but I don't see this happening in the next years. I've added it to https://github.com/py-pdf/pypdf/discussions/1181 just in case somebody has an idea.
