### ISSUE TITLE
page_mode/page_layout

### ISSUE THREAD

**Issue by malinphy** [py-pdf/pypdf#1978]
pypdf is very succeesful on extracting the text from pdf files. Even works for the double columns. Is there any way to extract the if the pdf file is a single column or double column?  Any other indicator that shows the pdf is a double column would be useful.

```
from PyPDF2 import PdfReader
from pprint import pprint

reader = PdfReader('ind/ac2012653.pdf')
page = reader.pages[0]
x = page.extract_text()
print(reader.page_layout())
```
for the  following code page_layout() and page_mode() gives TypeError: 'NoneType' object is not callable.

Thanks in advance.

**Comment by MartinThoma** [comment]
See https://pypdf.readthedocs.io/en/latest/user/extract-text.html?#why-text-extraction-is-hard
