### ISSUE TITLE
AttributeError: 'ArrayObject' object has no attribute 'get'

### ISSUE THREAD

**Issue by mnmtz** [py-pdf/pypdf#1979]
When extracting images from the following PDF, this error is raised:

## Error

`AttributeError: 'ArrayObject' object has no attribute 'get`

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.22621-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.12.2
```

## Code + PDF

This is a minimal example that shows the issue:

```python

reader = PdfReader(file, strict=False)
writer = PdfWriter()

writer.clone_document_from_reader(reader)

for page in writer.pages:

     for img_obj in page.images:
          img_count += 1
```

Sample PDF:
[example_121.pdf](https://github.com/py-pdf/pypdf/files/12080338/example_121.pdf)

**Comment by pubpub-zz** [comment]
image extracted for test:
![tt](https://github.com/py-pdf/pypdf/assets/4083478/42df4949-1557-4f2d-acca-6be6e8de1122)
