### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isspace'

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [py-pdf/pypdf#1983]
Tried to extract text from attached PDF.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-13.4.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.12.1
```

## Code + PDF
The code is [here](https://github.com/michelcrypt4d4mus/clown_sort/blob/main/clown_sort/files/pdf_file.py#L50)

PDF is attached. It's public and can be used for tests etc.
[New Jersey Coinbase staking securities charges 2023-0606_Coinbase-Penalty-and-C-D.pdf](https://github.com/py-pdf/pypdf/files/12090692/New.Jersey.Coinbase.staking.securities.charges.2023-0606_Coinbase-Penalty-and-C-D.pdf)

## Traceback

```
Traceback (most recent call last):
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/bin/sort_screenshots", line 6, in <module>
    sys.exit(sort_screenshots())
             ^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/workspace/clown_sort/clown_sort/__init__.py", line 43, in sort_screenshots
    file_to_sort.sort_file()
  File "/Users/uzor/workspace/clown_sort/clown_sort/files/sortable_file.py", line 60, in sort_file
    search_text = self.basename_without_ext + ' ' + (self.extracted_text() or '')
                                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/workspace/clown_sort/clown_sort/files/pdf_file.py", line 50, in extracted_text
    for image_number, image in enumerate(page.images, start=1):
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/_page.py", line 2603, in __iter__
    for i in range(len(self)):
                   ^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/_page.py", line 2565, in __len__
    return len(self.ids_function())
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/_page.py", line 479, in _get_ids_image
    self.inline_images = self._get_inline_images()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/_page.py", line 662, in _get_inline_images
    extension, byte_stream, img = _xobj_to_image(ii["object"])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/filters.py", line 814, in _xobj_to_image
    data = x_object_obj.get_data()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/generic/_data_structures.py", line 919, in get_data
    decoded._data = decode_stream_data(self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/filters.py", line 613, in decode_stream_data
    data = ASCIIHexDecode.decode(data)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/site-packages/pypdf/filters.py", line 280, in decode
    elif char.isspace():
         ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isspace'
```

**Comment by pubpub-zz** [comment]
@michelcrypt4d4mus 
Please provide code a simple code (focusing on failed page / image) to ease the analysis.

**Comment by MartinThoma** [comment]
Hm, interesting. That works fine: 

```
from pypdf import PdfReader, __version__

print(f"pypdf=={__version__}")

reader = PdfReader("New.Jersey.Coinbase.staking.securities.charges.2023-0606_Coinbase-Penalty-and-C-D.pdf")

for page in reader.pages:
    print(page.extract_text())
```

**Comment by MartinThoma** [comment]
I think the missing feature #1989 might be the issue here. It's just a bit hidden.

**Comment by pubpub-zz** [comment]
got something else behind too on page 10

**Comment by michelcrypt4d4mus** [comment]
> @michelcrypt4d4mus Please provide code a simple code (focusing on failed page / image) to ease the analysis.

i linked to [this code](https://github.com/michelcrypt4d4mus/clown_sort/blob/main/clown_sort/files/pdf_file.py#L41-L71) in my package; let me know if that's not enough. it's simple - just iterate over all pages + all images and extract text.

**Comment by pubpub-zz** [comment]
> > @michelcrypt4d4mus Please provide code a simple code (focusing on failed page / image) to ease the analysis.
> 
> i linked to [this code](https://github.com/michelcrypt4d4mus/clown_sort/blob/main/clown_sort/files/pdf_file.py#L41-L71) in my package; let me know if that's not enough. it's simple - just iterate over all pages + all images and extract text.
> 
> **edit:** the [actual extraction is done with `pytesseract`](https://github.com/michelcrypt4d4mus/clown_sort/blob/main/clown_sort/files/image_file.py#L79-L86) but the code doesn't get that far bc it fails to iterate on the images in the image in `pypdf` as per my link in the original issue.

What I would like is a standalone code, focusing directly on the page and image which is producing the error. It simplify our analysis not checking everything

**Comment by pubpub-zz** [comment]
I've finally found the issue. PR is proposed

**Comment by AfifaYousaf** [comment]
if line.is_space():
AttributeError: 'int' object has no attribute 'is_space'


Please let me know how to fix it

**Comment by pubpub-zz** [comment]
@AfifaYousaf 
we can not help you with so limited information: Open a new issue, attach your code and pdf for analysis.

**Comment by AfifaYousaf** [comment]
import numpy as np

with open('runjob.out', 'r') as fd:
    lines = fd.readlines()

fnbo = -1
for line in range(len(lines)):
    if 'NBO Fock Matrix:' in lines[line]:
        fnbo = line
        break

#if fnbo == -1:
 #   print("Error: NBO Fock matrix not found")
  #  exit()

names = []
# Extract orbital names, starting 4 lines after 'NBO Fock Matrix'
for line in range(fnbo+4,len(lines)):
    if line.is_space():
        break
     # Collecting names
    names.append(lines[line][6:14])

n = len(names)
# Initialize the Fock matrix
F = np.zeros((n,n))

# Number of blocks
nblocks = (n + 7) // 8
for block in range(nblocks):
    ncol = min(8, n - 8*block)
    for i in range(n):
        # Access the correct line in the block
        line = fnbo + (n+3)*block + 4
        data = map(float, line[14:].split())
        assert(len(data) == ncol)
        # Fill the Fock matrix
        for j0 in range(ncol):
            F[i,j0+block*8] = data[j0]
print("Fock Matrix:\n", F)
