### ISSUE TITLE
remove_text() do not work

### ISSUE THREAD

**Issue by kangbaoxing** [py-pdf/pypdf#1988]
when LTfigre in pdfpage，text in LTFigure can not be delete by remove_text();  LTFigure is the class in pdfminer. "LTFigure" in pypdf2, shows as (pageObject->resource->Ojbects->"fm0")

**Comment by pubpub-zz** [comment]
@kangbaoxing 
please provide code, pdf, and versions. without those we will have to close this issue as no analysis is possible

**Comment by MartinThoma** [comment]
I'll re-open once we have helpful information. At the moment, this looks like it should be on the pdfminer issue tracker
