### ISSUE TITLE
PdfMerger adds custom outline at the top instead of at the bottom

### ISSUE THREAD

**Issue by uy-rrodriguez** [py-pdf/pypdf#1990]
Trying to merge several PDFs and add custom outlines in order. The idea is to have bookmarks with all the pages of the initial PDF at the beginning, and a custom bookmark grouping all extra PDFs at the end.

`PdfMerger` adds the custom outline at the top (when `merger.add_outline_item('Attachments'...)` is reached), and only processes outlines for the pages of the initial PDF at the end (when `merger.write` is executed), which creates outlines for its pages at the bottom.

## Environment

- Win 10
- Python 3.10.7
- pypdf 3.12.2

## Code

```python
# Create merger
merger = pypdf.PdfMerger()

# Add the base PDF
base_reader = pypdf.PdfReader('example.pdf')
merger.append(base_reader)

# Add bookmark parent for attachments
last_page = len(base_reader.pages)
att_parent = merger.add_outline_item('Attachments', last_page)

# Add attachments as nested bookmarks
att = 'attachment.pdf'
merger.append(att, import_outline=False)
merger.add_outline_item('Nested attachment', last_page, att_parent)

# Write output
merger.write('final.pdf')
```

## Output

Bookmarks are created as follows:

- Attachments
  - Nested attachment
- Initial doc first page
- Initial doc second page

Expected output is:

- Initial doc first page
- Initial doc second page
- Attachments
  - Nested attachment

> This works as expected with PyPDF2 1.26.0 (last version used before upgrade), not sure of the equivalent in "pypdf", though.

## Workaround

The workaround I've found is to create bookmarks for the pages of the initial file before creating the custom "Attachments".

```python
# ...
# After merger.append(base_reader)
merger.outline = []
for o in base_reader.outline:
    page_nbr = base_reader.get_destination_page_number(o)
    merger.add_outline_item(o.title, page_nbr)

# Then, add bookmark parent for attachments as in the example above
# ...
```

> Note: Without the line `merger.outline = []`, my manual outlines for the initial PDF pages are created on top (as expected) but also added by pypdf after "Attachments".

**Comment by pubpub-zz** [comment]
PdfMerger is obsolete. please retry with PdfWriter
Also consider using parent and before parameters to set the position of the outlines

**Comment by uy-rrodriguez** [comment]
Sorry, I was unaware of `PdfMerger` being obsolete.
Using `PdfWriter` instead without manually creating outlines for pages of the initial document (first code example) works as expected. There was no need to specify `before` or `parent`.
Thank you!
