### ISSUE TITLE
Unwanted Space between the letters of a word

### ISSUE THREAD

**Issue by mrbahrani** [py-pdf/pypdf#1993]
I used the library to extract the text from a pdf file. There are some words which have been broken to two parts by an unwanted space.

Text from PDF:
![image](https://github.com/py-pdf/pypdf/assets/16466767/c15fe589-8c28-4170-bd24-e03df7625462)
Text from text file:
![image](https://github.com/py-pdf/pypdf/assets/16466767/0e949b28-0a19-41e7-838d-d0e10ae5d380)

## Environment

OS: Windows 10
Python: 3.11
PyPDF: the latest

## Code + PDF

This is the way I used the library

```python
def convert_pdf_to_text(file_name):
    out = ""
    pdf_file_obj = open(file_name, 'rb')
    pdf_reader = PyPDF2.PdfReader(pdf_file_obj, strict=True)
    for page in pdf_reader.pages:
        text = page.extract_text()
        out += text
    return out
```

The PDF is confidential data.
I tested that on multiple confidential PDF data

## Traceback
This is the subpart of the (operation, operator) tuples that I printed to track.
![image](https://github.com/py-pdf/pypdf/assets/16466767/f384858d-b522-4d76-930a-3b7979f4c992)
The Tm tag causes a call of `orientation` function that adds the unwanted space. I have briefly reviewed the pdf specification 1.7. Yet, I do not know what `Tm` tag exactly does. 

Having the space adding sections of orientation removed, the text was extracted perfectly.

**Comment by pubpub-zz** [comment]
https://pypdf.readthedocs.io/en/stable/user/extract-text.html#why-text-extraction-is-hard
Tm does a change in scale/translation of the text / images. Without heavy page reconstruction the Tm can only be interpreted as a section separated with " " or "\n"
