### ISSUE TITLE
KeyError: /DA inupdate_page_form_field_values

### ISSUE THREAD

**Issue by martzro** [py-pdf/pypdf#1997]
Trying to update writer using update_page_form_field_values and getting KeyError: /DA

## Environment

Which environment were you using when you encountered the problem?

$ python -m platform
Windows-10-10.0.19041-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.12.2

## Code + PDF
from io import BytesIO
from pypdf import PdfReader, PdfWriter
import requests

url = "https://discover.pbcgov.org/pzb/building/Forms/Building%20Division%20Permit%20Application.pdf"

reader = PdfReader(BytesIO(requests.get(url).content))
fields = reader.get_form_text_fields()
fields["PCN-1"] = "0"
writer.update_page_form_field_values(
        writer.pages[0], fields
    )

## Traceback

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-94-095b5545cb3c> in <module>
      4 fields = reader.get_form_text_fields()
      5 fields["PCN-1"] = "0"
----> 6 writer.update_page_form_field_values(
      7         writer.pages[0], fields
      8     )

~\anaconda3\lib\site-packages\pypdf\_writer.py in update_page_form_field_values(self, page, fields, flags, auto_regenerate)
    969                     ):
    970                         # textbox
--> 971                         self._update_text_field(writer_annot)
    972                     elif writer_annot.get(FA.FT) == "/Sig":
    973                         # signature

~\anaconda3\lib\site-packages\pypdf\_writer.py in _update_text_field(self, field)
    838         # Extract font information
    839         font_properties: Any = (
--> 840             cast(str, field[AA.DA]).replace("\n", " ").replace("\r", " ").split(" ")
    841         )
    842         font_name = font_properties[font_properties.index("Tf") - 2]

~\anaconda3\lib\site-packages\pypdf\generic\_data_structures.py in __getitem__(self, key)
    307 
    308     def __getitem__(self, key: Any) -> PdfObject:
--> 309         return dict.__getitem__(self, key).get_object()
    310 
    311     @property

KeyError: '/DA'

**Comment by martzro** [comment]
UPDATE:

The PDF i sent lacks the /DA in the pdf so to fix this I added the following lines to _writer.py:

font = TextStringObject('/Helv 11 Tf 0 g')
name = NameObject(AA.DA)
if name not in field.keys():
    field[name] = font

This checks if /DA is not in the field keys and adds the fond to it.

Is there a way to do this without changing the original _writer.py file?

Closing as this is not a bug.

**Comment by pubpub-zz** [comment]
"/DA" is an optional field as stated in pdf 1.7 reference p673.
I reopen it as it can be considered as a bug. I keep in mind your idea

**Comment by pubpub-zz** [comment]
local copy of the pdf for test:
[Building Division Permit Application.pdf](https://github.com/py-pdf/pypdf/files/12136285/Building.Division.Permit.Application.pdf)

**Comment by pubpub-zz** [comment]
the PR to fix the issue is pending merging.
