### ISSUE TITLE
Consider migrating to Cryptography 

### ISSUE THREAD

**Issue by scdub** [py-pdf/pypdf#1998]
## Explanation

I help maintain a large Python distribution, which would like to use `pypdf` for reading encrypted PDFs, but would prefer not to include the additional dependency of PyCryptodome as we already include [Cryptography](https://cryptography.io/) for numerous other dependencies. Cryptography includes the same cryptographic primitives used in `pypdf` (AES and RC4), but is typically a smaller and more secure installation as it calls well vetted implementations rather than implementing them directly. It also is a dependency of `requests` via `urllib3`, and is [widely deployed](https://piptrends.com/compare/pycrypto-vs-pycryptodome-vs-cryptography). A quick check of conda-forge packages showed that PyCryptodome / PyCryptodomeEx was used in 25 packages versus 135 for Cryptography, and other packages such the [`pdfminer.six`](https://pdfminersix.readthedocs.io) have [made this migration earlier](https://github.com/pdfminer/pdfminer.six/pull/456).

If this is something that seems worthwhile, I can work on creating a PR for this effort. 

cc @exiledkingcc

**Comment by michelcrypt4d4mus** [comment]
+1 the `pycryptodome` dependency occasionally trips up `pip`

**Comment by exiledkingcc** [comment]
good suggestion! i will try to add support for Cryptography. whats your opinion? @MartinThoma

**Comment by pubpub-zz** [comment]
for me,
@exiledkingcc, you are the one dealing the best with the crypto part of pypdf and who will do the job 😁
I just have a remark : currently pypdf is compatible with python down to 3.6 but appearantly `cryptography` is limited to 3.7+. 
python 3.6 is still the default for RH8 (still active)
Personally I have no religion 🙂

**Comment by exiledkingcc** [comment]
sure, personally i prefer not to replace PyCryptodome by cryptography, add just support using cryptography to do encryptioin/decryption when no PyCryptodome installed. i just write a PR #2000 for it.
and, it's flexible to support any other crypto libraries if needed.

**Comment by MartinThoma** [comment]
Thank you @scdub for pointing this out. It helps me a lot to know that [requests uses cryptography](https://github.com/psf/requests/blob/cdbc2e271529f467b278b2760f12ee0b5d6930d3/requests/help.py#L30). I need to check [the cryptography project](https://pypi.org/project/cryptography/) a little bit more, bit I tend to agree that this is a good idea.

@exiledkingcc Thank you for providing a PR that swift :heart: I guess it will take at least this week. I don't want to rush with security-related changes

**Comment by MartinThoma** [comment]
> I help maintain a large Python distribution

@scdub Now I'm curious :smile: In case you don't want to elaborate publicly, but are free to speak about it in private: info@martin-thoma.de

**Comment by MartinThoma** [comment]
> personally i prefer not to replace PyCryptodome by cryptography, add just support using cryptography to do encryptioin/decryption when no PyCryptodome installed

As I don't want to break backwards compatibility, I also prefer that approach :+1: Was that also the (only) reason why you don't want to change it? If that is the case, we **could** plan deprecating PyCryptodome for `pypdf>=4.0.0`

**Comment by MartinThoma** [comment]
Regarding the support of Python versions: https://github.com/py-pdf/pypdf/discussions/2005 - currently, I tend to keep Python 3.6 support. I feel like it doesn't cost us that much + a lot of people (sadly) still need it.

**Comment by exiledkingcc** [comment]
personally, i would prefer python standard libraries to have cryptographic functions, which not happens yet :disappointed: . 
for now i think we can keep both as well as they are in good maintation.

**Comment by MartinThoma** [comment]
@scdub I've merged the excellent PR by @exiledkingcc . The  `cryptography` fallback will be part of `pypdf > 3.13.0` which I will release latest on Sunday (30th of July).

**Comment by scdub** [comment]
> > I help maintain a large Python distribution
> 
> @scdub Now I'm curious 😄 In case you don't want to elaborate publicly, but are free to speak about it in private: [info@martin-thoma.de](mailto:info@martin-thoma.de)

Thanks much for this change! I really appreciate it. The Python distribution I had mentioned [is what we distribute](https://pro.arcgis.com/en/pro-app/latest/arcpy/get-started/available-python-libraries.htm) as part of ArcGIS Pro, a Geographic Information System program. We use your great `pypdf` package (and earlier PyPDF2) to allow users to [create PDFs of their maps](https://pro.arcgis.com/en/pro-app/latest/arcpy/mapping/introduction-to-arcpy-mp.htm) from Python.

**Comment by pubpub-zz** [comment]
@scdub 
Thanks for your comments appreciated.
In order to support pypdf dev, Can you give your opinion about supporting(https://github.com/py-pdf/pypdf/discussions/1660)? the idea is really to have some capability to buy documentation and other support means to extend pypdf.

**Comment by scdub** [comment]
@pubpub-zz For sure, I can contribute on a personal basis, and left some thoughts on approaches to support on that discussion.

**Comment by scdub** [comment]
@pubpub-zz specifically on the PDF 2.0 specification, have you seen https://www.pdfa.org/sponsored-standards/ ? It still requires accepting a EULA, but does provide free access to ISO 32000-2 and some of its supplements.

**Comment by pubpub-zz** [comment]
> @pubpub-zz specifically on the PDF 2.0 specification, have you seen https://www.pdfa.org/sponsored-standards/ ? It still requires accepting a EULA, but does provide free access to ISO 32000-2 and some of its supplements.

Thanks, already loaded.😉

**Comment by MartinThoma** [comment]
The PDF 2.0 specifications became available after I've opened #1660
