### ISSUE TITLE
Formatting and calculations not applying in form fields

### ISSUE THREAD

**Issue by b-dawes** [py-pdf/pypdf#2015]
I have a form I'm trying to fill out that has some basic formatting for currency and calculations in it. When I open the output pdf, the values entered into fields formatted as currency just show up as plain numbers. The calculated values are also not updated. If I update one of the fields, it is then formatted properly and any calculations involving the field are also updated.

Updating the fields with something like "$3.00" does work except the values in the field should just be numbers that are displayed with the proper formatting.

I designed a simple test pdf with Adobe Acrobat to show this. It has 3 fields, all formatted as currency. The third field is simply the sum of the first two fields. Below is code that updates the first two values. Attached are the input/output pdfs. Also attached are screenshots of the formatting and calculation settings for the fields in Acrobat.

## Environment

```bash
$ python -m platform
Windows-10-10.0.19041-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.13.0
```

## Code + PDF

```python
from pypdf import PdfReader, PdfWriter

reader = PdfReader("test.pdf")
writer = PdfWriter()

writer.append(reader)

new_data = {
    "Price1": 5,
    "Price2": 2
}

writer.update_page_form_field_values(
    writer.pages[0], new_data
)

with open("test_out.pdf", "wb") as output_stream:
    writer.write(output_stream)
```

[test.pdf](https://github.com/py-pdf/pypdf/files/12164904/test.pdf)
[test_out.pdf](https://github.com/py-pdf/pypdf/files/12164905/test_out.pdf)

![image](https://github.com/py-pdf/pypdf/assets/27304478/faceaedd-67b6-42d1-8f1d-d7c7d7c92d21)
![image](https://github.com/py-pdf/pypdf/assets/27304478/d697b6a2-383c-4af5-835e-b820eb4e12af)

**Comment by pubpub-zz** [comment]
the mechanism behind the calculation relies on JavaScript. The fields in the PDF are only text and pypdf is just here to fill up the fields. Formatting and calculations have to be done by your program

**Comment by pubpub-zz** [comment]
closing this issue as out of scope
