### ISSUE TITLE
Checkboxes, update_page_form_field_values, encoding and german characters.

### ISSUE THREAD

**Issue by kubaPod** [py-pdf/pypdf#2021]
I am filling a form with text and checkbox fields. Text values may contain german characters.
If a checkbox is programmatically selected then subsequent fields are corrupted.
It might not be a `pypdf` fault, see viewers comparison in caveats below.

![image](https://github.com/py-pdf/pypdf/assets/15227576/189b6c78-dac1-41da-8df9-3ceaf1c0be87) vs. ![image](https://github.com/py-pdf/pypdf/assets/15227576/75c6989c-e815-44ce-b42b-68c879d411a1)

### Caveats:

- if the corrupted field gets focus the displayed text is correct ( back to incorrect when the focus is lost):
![image](https://github.com/py-pdf/pypdf/assets/15227576/de9a66d6-bbfd-450d-91f6-bd54c718918d)

- case reproduced in Adobe Acrobat Reader
- Chrome viewer shows correct characters:
![image](https://github.com/py-pdf/pypdf/assets/15227576/7da8a3de-ad2a-4b06-b13f-3d712b646a9c)
- Firefox viewer shows incorrect characters (even in the first field) regardless of checkbox:
![image](https://github.com/py-pdf/pypdf/assets/15227576/76604f25-45fc-4916-a12f-611bc3c639b9)

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.19045-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.12.2
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python

from pypdf import PdfWriter

writer = PdfWriter()
writer.append("./visa-form.pdf")

writer.update_page_form_field_values(
    writer.pages[0],
    {
        '1 Surname': 'Zürich', 
    #    'Check Box 9.1': '/Ja',  # skip or not
        '9': 'Zürich'
    }    
)

with open("./zurich-test.pdf", "wb") as output_stream:
    writer.write(output_stream)
    output_stream.close()

```

[visa-form.pdf](https://github.com/py-pdf/pypdf/files/12170119/visa-form.pdf)
[zurich-test-no-checkbox.pdf](https://github.com/py-pdf/pypdf/files/12170293/zurich-test-no-checkbox.pdf)
[zurich-test-with-checkbox.pdf](https://github.com/py-pdf/pypdf/files/12170295/zurich-test-with-checkbox.pdf)

## Traceback

---

TODO

**Comment by pubpub-zz** [comment]
@kubaPod, 
the issue deals with the encoding 
I've proposed a PR if you want to try.
