### ISSUE TITLE
Permission to integrate Pypdf into OSS-Fuzz

### ISSUE THREAD

**Issue by bluemarco** [py-pdf/pypdf#2031]
Hi @MartinThoma, May I request your approval/permission to integrate py-pdf into OSS-Fuzz?  Thanks
https://github.com/google/oss-fuzz/pull/10670

**Comment by MartinThoma** [comment]
I've answered directly there :-)

**Comment by MartinThoma** [comment]
I think I'll remove pypdf from OSS-Fuzz again. Something doesn't work and I don't see the value + don't have the energy to fix it.

**Comment by bluemarco** [comment]
What types of bugs did it find? I found an Out-of-Memory bugs last time I checked my fuzzer.
