### ISSUE TITLE
Crossreferences lost during merge

### ISSUE THREAD

**Issue by peluho** [py-pdf/pypdf#2032]
## Explanation

When I merge several pdfs with bookmarks, don't know why the crossreferences break, therefore in the output file they dont work.

## This a very simple code to merge 2 items.

```python
from pypdf import PdfReader, PdfWriter

def merge_pdfs2(folder_path, filename1, filename2):

    merger = PdfMerger()
    merger.append(PdfReader(os.path.join(folder_path, filename1 + '.pdf'), 'rb'), import_outline=True)
    merger.append(PdfReader(os.path.join(folder_path, filename2 + '.pdf'), 'rb'), import_outline=True)

    merger.write(os.path.join(folder_path,"document-output.pdf"))

...  # your new feature in action!
```
I think maybe is something I'm doing wrong. 

I'll appreciate any advice onto this. Thank you ver much,

**Comment by pubpub-zz** [comment]
a) PdfMerger is obsolete use PdfWriter instead
b) can you clarify what you mean by "crossreferences"

**Comment by pubpub-zz** [comment]
@peluho 
without feed backs I close this issue. We can reopen it when you will have new inputs
