### ISSUE TITLE
KeyError: '/Info'

### ISSUE THREAD

**Issue by mnmtz** [py-pdf/pypdf#2049]
KeyError raised when reading PDF file. It seems that the file is missing the /Info key, but file is correctly displayed using Acrobat Reader, Chrome or qpdf. I could not find a clear definition in the PDF reference, but as far as I know, the /Info key is recommended, but not required in a PDF document.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.22621-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.14.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
reader = PdfReader(file, strict=False)
writer = PdfWriter()

writer.clone_document_from_reader(reader)

for page in writer.pages:

     for img_obj in page.images:
          img_count += 1
```

[example_024.pdf](https://github.com/py-pdf/pypdf/files/12212590/example_024.pdf)

## Traceback

This is the truncated Traceback I see:

  File "C:\Users\\-----\AppData\Local\Programs\Python\Python311\Lib\site-packages\pypdf\_writer.py", line 1129, in clone_document_from_reader
    self._info = reader.trailer[TK.INFO].clone(self).indirect_reference  # type: ignore
                 ~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\\-----\AppData\Local\Programs\Python\Python311\Lib\site-packages\pypdf\generic\_data_structures.py", line 320, in __getitem__
    return dict.__getitem__(self, key).get_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '/Info'

**Comment by pubpub-zz** [comment]
can you retry with this startup:
```
writer = PdfWriter(clone_from=file)
(...)
```

**Comment by pubpub-zz** [comment]
This looks like a robustness issue when the Info does not exists...
Can you propose a PR ?

**Comment by pubpub-zz** [comment]
It will make you as an active contributor 😀

**Comment by MartinThoma** [comment]
The fix was just merged into `main` and will be released on Sunday (6th of August) with `pypdf > 3.14.0`
