### ISSUE TITLE
DOC: Add deprecation banner to PyPDF2 docs

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#2051]
The documentation on read the docs is confusing, as it looks very similar to pypdf. Also in the URL. This leads to such issues: https://github.com/py-pdf/pypdf/issues/2050

I would like to add a notice/banner on the top of every page of https://pypdf2.readthedocs.io/ saying something like:

> This page is about PyPDF2. PyPDF2 is deprecated, please [use pypdf](https://pypdf.readthedocs.io/en/latest/)

Does anybody know how to do this with Sphinx?

**Comment by stefan6419846** [comment]
As far as I am aware, the easiest way is to add an `rst_epilog` definition to the configuration file with some admonition directive: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives The alternative would be to mess with the theme files itself to get more control over how everything is being displayed, but this might impose more work.

**Comment by kryskool** [comment]
Some Sphinx theme like Furo have an announcement banner

https://pradyunsg.me/furo/customisation/announcement/

**Comment by eshellman** [comment]
Also, needs to make clear somewhere (in the migrating section) that you need to import from pypdf, not from PyPDF2

**Comment by stefan6419846** [comment]
You are of course invited to send a corresponding PR to make this clearer.

**Comment by stefan6419846** [comment]
Has been fixed in #2565.
