### ISSUE TITLE
Transparent images not correctly replaced

### ISSUE THREAD

**Issue by mnmtz** [py-pdf/pypdf#2056]
The alpha channel is not correctly saved when replacing an image using `ImageFile.replace()`. Below a trivial example that replaces the original image by itself. When saving the PDF file, the transparency is lost. This also happens, when the original image is replaced by another transparent image.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.22621-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.14.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
reader = PdfReader("example_130.pdf")

writer = PdfWriter(clone_from=reader)

for page in writer.pages:

    for img_obj in page.images:
        img_obj.replace(img_obj.image)

with open("example_130_output.pdf", 'wb') as f:
    writer.write(f)

```

The example PDF file below contains a transparent image for testing:

[example_130.pdf](https://github.com/py-pdf/pypdf/files/12227212/example_130.pdf)

**Comment by pubpub-zz** [comment]
this is an issue in pillow . issue raised there:
https://github.com/python-pillow/Pillow/issues/7312

**Comment by pubpub-zz** [comment]
with Pillow 10.1.0 the transparency is OK but the output is slightly different from original
original PDF
![image](https://github.com/py-pdf/pypdf/assets/4083478/371bfbd4-91c6-4d1c-b3c8-9db1d807e4ce)
"replaced image
![image](https://github.com/py-pdf/pypdf/assets/4083478/266de3c0-67b1-4b6b-921c-2d4bdc530f3c)

I will create a new PR about it
first analysis leads to image extraction
test file:
https://github.com/py-pdf/pypdf/files/12227212/example_130.pdf
test code:
```
import pypdf
writer = pypdf.PdfWriter(clone_from="example_130.pdf")
for page in writer.pages:
    for img_obj in page.images:
        img_obj.replace(img_obj.image)
writer.write("example_130_out.pdf")
```
