### ISSUE TITLE
Iterating through images stuck without error

### ISSUE THREAD

**Issue by mnmtz** [py-pdf/pypdf#2077]
When iterating through all images of a certain page, the process is stuck and hangs infinitely (manually aborted after >1h) without any exception or error.
**This is most likely because the example PDF is somehow malformed (but correctly viewable), nevertheless, an exception should be thrown.**

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.22621-SP0  /  macOS-13.4.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.15.0
```

## Code + PDF

This is a minimal example that shows the issue:

```python
reader = PdfReader(file, strict=False)
writer = PdfWriter()

writer.clone_document_from_reader(reader)

img_count = 0

for page in writer.pages:

     for img_obj in page.images:
          img_count += 1
```

[example_134.pdf](https://github.com/py-pdf/pypdf/files/12309492/example_134.pdf)
(The file is just an excerpt of the original PDF, but still shows the behavior described above)

Here is the rich table output from pdfalyzer:
[pdfalyzed_example_134.pdf](https://github.com/py-pdf/pypdf/files/12309607/pdfalyzed_example_134.pdf)

**Comment by pubpub-zz** [comment]
your Pdf is tricky! you have loops in the resources which should not exists.
However @MartinThoma may consider that as a "security" issue and it is anyway a reliability issue.

**Comment by MartinThoma** [comment]
Yes! I consider anything that can lead to an infinite loop a security issue as it potentially harms the availability of a service.
