### ISSUE TITLE
visitor_text method of extract_text method could be given each word separately

### ISSUE THREAD

**Issue by rkiddy** [py-pdf/pypdf#2094]
I am trying to pull the text out of a very precisely structured table. I will attach a page from the pdf below.

The only way that I think that I can do the interpretation is to have the x,y values for every word in the text. As of now, the strings handed to the visitor_text method are words that are determined to be "close enough" to each other to be strings. But this is not deterministic enough to be helpful.

In the pdf, you will see on the 1st and 3rd line:

     170     81   __         Am      570   __   489           Ad
     271   1179   __  23:67  Am      571   __   489           Ad

But the text you will be give is:

     "170 81 __ Am 570 __ 489 Ad"
     "271 1179 __ 23:67 Am 571 __ 489 Ad"

There is no indication that the first one has a blank value for the 4th column.

Maybe I am asking pypdf for something that it cannot really do, or something that it is not designed for,

But looking at the example above, you can see that if I can pass a flag into the visitor_text method and I get the x and y values of each word, I would be able to tell that the 4th column is empty in the first line.

I will look in the code and see if this is even possible, we will see.

**Comment by pubpub-zz** [comment]
@troethe 
3 visitors functions call be called:
>visitor_operand_before – function to be called before processing an operation. It has four arguments: operator, operand-arguments, current transformation matrix and text matrix.
>visitor_operand_after – function to be called after processing an operation. It has four arguments: operator, operand-arguments, current transformation matrix and text matrix.
>visitor_text – function to be called when extracting some text at some position. It has five arguments: text, current transformation matrix, text matrix, font-dictionary and font-size. The font-dictionary may be None in case of unknown fonts. If not None it may e.g. contain key “/BaseFont” with value “/Arial,Bold

if you use visitor_operand_before  you will be able to process only Tj operands

as the original request can not be processed I close this issue
