### ISSUE TITLE
For some pdfs spaces are interpreted as line breaks

### ISSUE THREAD

**Issue by termsofserving** [py-pdf/pypdf#2095]
Replace this: What happened? What were you trying to achieve?

When printing certain PDFs, spaces are printed as line breaks

## Environment

Which environment were you using when you encountered the problem?

Windows-10-10.0.19045-SP0

3.0.1

## Code + PDF

import PyPDF2
    def get_info(path):
      pdf = open("text.pdf", "rb")
      pdfReader = PyPDF2.PdfReader(pdf)
      page = pdfReader.pages[0]
      ok = page.extract_text()
      print(ok)

if __name__ == '__main__':
    path = 'Untitled document.pdf'
    get_info(path)
```
Output from text.pdf:
Hello
World.
This
is
a
sample
PDF
with
2
pages.
This
is
the
first
page.

PDFs:
[Untitled document.pdf](https://github.com/py-pdf/pypdf/files/12375238/Untitled.document.pdf)
[text.pdf](https://github.com/py-pdf/pypdf/files/12375239/text.pdf)

Both were imported from Google Docs. 

No traceback error

**Comment by MartinThoma** [comment]
Please note that we have lots of open https://github.com/py-pdf/pypdf/labels/whitespace issues. Without a new PDF that highlights the issue in detail, I'm closing this as a duplicate
