### ISSUE TITLE
Some images in pdf can not be removed using 'remove_images()'

### ISSUE THREAD

**Issue by animebing** [py-pdf/pypdf#2103]
Some images in pdf can not be removed using the method metioned [here](https://pypdf.readthedocs.io/en/latest/user/file-size.html#removing-images). There is only one page in the pdf and the output of 'len(page.images)' is 32, When I do 'remove_images()', they are still in the new created pdf.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# Windows-10-10.0.22621-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
# 3.15.2
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import os
import sys

from pypdf import PdfReader, PdfWriter


src_pdf_path = sys.argv[1]
dst_pdf_path = os.path.splitext(src_pdf_path)[0] + '_no_images.pdf'

reader = PdfReader(src_pdf_path)
writer = PdfWriter()

for page in reader.pages:
    writer.add_page(page)

writer.remove_images()
with open(dst_pdf_path, "wb") as f:
    writer.write(f)
```
[2210.03142-1.pdf](https://github.com/py-pdf/pypdf/files/12394781/2210.03142-1.pdf)

**Comment by pubpub-zz** [comment]
the images are in a XObject/Form within an XObject/Form
I've modified the code to cope with such situations for all remove_xxx functions

**Comment by MartinThoma** [comment]
The bugfix by @pubpub-zz was just merged and will be released on 3rd of September in `pypdf > 3.15.4`

**Comment by MartinThoma** [comment]
@animebing Thank you for reporting the issue :pray: If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by animebing** [comment]
@MartinThoma Thanks for solving the problem.
