### ISSUE TITLE
PageObject.extract_text raises TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [py-pdf/pypdf#2111]
I expected to be able to extract the text without a weird exception.

Took a while to figure out why this happens, but I tracked down the issue to `pypdf.filters.decode_stream_data` which claims that it should always return bytes, however the function it calls for `FT.LZW_DECODE` returns a `str` object without converting it back to bytes in any way. The call is filters.py line 698 in the function `decode_stream_data`, and it calls `LZWDecode.decode`. Checking the type information on that function confirms that it is supposed to return a `str` object.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.19045-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
3.15.2
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import pypdf

pdf = pypdf.PdfReader('T-REC-X.25-199610-I!!PDF-E.pdf')
text = [x.extract_text() for x in pdf.pages]
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

This isn't my PDF, but it is publicly available. Don't know if that means you can use it in your tests. It can be found [here](https://www.itu.int/rec/T-REC-X.25-199610-I/en) but I've also uploaded it below.

[T-REC-X.25-199610-I!!PDF-E.pdf](https://github.com/py-pdf/pypdf/files/12423313/T-REC-X.25-199610-I.PDF-E.pdf)

## Traceback
 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\pypdf\_page.py", line 2268, in extract_text
    return self._extract_text(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pypdf\_page.py", line 1927, in _extract_text
    content = ContentStream(content, pdf, "bytes")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pypdf\generic\_data_structures.py", line 999, in __init__
    data += s.get_object().get_data()
TypeError: can't concat str to bytes
```

**Comment by MartinThoma** [comment]
Oh damn, I think I know where this came from: https://github.com/py-pdf/pypdf/pull/2100

I'll check this weekend and fix it. At the very least I'll add this as a test to prevent this from happening again.

**Comment by MartinThoma** [comment]
Thank you for reporting the issue!

If you want, I can add you as a contributor: https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by TheElementalOfDestruction** [comment]
Thanks for the quick response. If you'd like to add me then sure, but I don't think it's necessary. Discovering it was a complete accident since I didn't even mean to run my code on that particular file, lol.

**Comment by MartinThoma** [comment]
I've introduced the error with https://github.com/py-pdf/pypdf/pull/2100

The error is fixed via https://github.com/py-pdf/pypdf/pull/2114

Once the CI succeeds I will merge. I will release `pypdf>3.15.2` latest on Sunday to PyPI.
