### ISSUE TITLE
pdfWriter keeps writing the same page

### ISSUE THREAD

**Issue by annalise3456** [py-pdf/pypdf#2118]
Hello everyone, 

I was using an old version of pypdf2 and everything was fine. Last week I switched to the new pypdf and now when I use pdfWriter to write my final pdf some pages are repeated in a random way (no pattern detected). 
For example I have page 1, page 2, page 3, page2 again, page 5, page 6, page 7, page 3 again and so on..
The interesting thing is that when these mismatches happens the pages displayed are wrong but if I try to catch the text I can retrieve the one related to the corrected pages.

**Comment by stefan6419846** [comment]
Please provide the corresponding reproducing code as well as a PDF which shows this issue.

**Comment by annalise3456** [comment]
The code is very simple and went really well for years, but I cannot share the PDF which is causing me troubles.
  pdf_writer = PdfWriter()
...
  pdf_writer.add_page(original_pdf.pages[page-1])

  with open(f"{path}{basename}.pdf", 'wb') as export_file:
        pdf_writer.write(export_file)

**Comment by stefan6419846** [comment]
Please provide some complete code example, not just snippets with undefined variables etc. If you cannot upload your PDF file here, you might be able to send it to @MartinThoma by e-mail directly.

**Comment by MartinThoma** [comment]
@annalise3456 this has way to little information. If you want help, please use the bug issue template
