### ISSUE TITLE
Investigate options to automate the contributors list

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#2119]
This is a reminder to me to look into https://github.com/all-contributors/all-contributors

https://github.com/py-pdf/fpdf2/tree/master uses this in the README. While I don't want it directly there, I would like to have something similar in a dedicated page.

**Comment by pubpub-zz** [comment]
It would be great if you were able to add the authors in the release note as you were doing manually 😁

**Comment by MartinThoma** [comment]
Yes, I noticed that this is a shortcoming of the current script :+1: 

From the git commits, I can get:

* Stefan <96178532+stefan6419846@users.noreply.github.com>
* Lucas Cimon <925560+Lucas-C@users.noreply.github.com>
* pubpub-zz <4083478+pubpub-zz@users.noreply.github.com>

What I would like to get is:

* @stefan6419846 
* @Lucas-C 
* @pubpub-zz 

Maybe I can use the Github API to get the authors Github username :thinking:

**Comment by MartinThoma** [comment]
Also, I thought that the format of the release notes and the CHANGELOG might be slightly different:

* CHANGELOG: Keep it short. Only the important stuff. For readability, it might make sense to skip the authors. Still point to the PR so that people know where to get details.
* Release notes + git tag: Add the authors. Maybe also more changes (DOC, MAINT, STY, ...)

The reasoning is that people who read the CHANGELOG likely just want to see if there is a breaking change or a good reason to upgrade. They might currently update a ton of other packages as well and rather be happy if the relevant information is very condensed. 

People who read release notes likely are more curious. They are maybe interested in a brief summary as well (sometimes I do that if there are several related changes or if something outstanding was done, e.g. @pubpub-zz text textraction and @exiledkingcc additions of cryptography support).

What's your opinion on that @pubpub-zz ?

**Comment by MartinThoma** [comment]
In any case, I first need to see how I can get it automatically at all :smile:

I want to make as much of the release process automatic so that we can easily switch maintainers. The idea is that we could make make this as a rotating role, e.g. for a year or two once. Especially once we slow down a bit / do more minor improvements than in the past year. That seems more sustainable on the long run than a single maintainer. At the same time, we need to ensure consistency ... which means that we first need to be consistent with a single maintainer / the current code base :smile:

**Comment by pubpub-zz** [comment]
Your proposal sounds good. I agree with your approach to keep it automatic. Just having authors at the end of the change sounds good.
switching maintainers sounds reasonable but you will be difficult to replace 😊
at least we could reduce releases every 2 weeks.

**Comment by pubpub-zz** [comment]
@MartinThoma 
shouldn't we close this issue ?

**Comment by MartinThoma** [comment]
Yes.

I'm still open to automating adding contributors via a bot, but the all-contributors bot seems too opinionated / complex. It's pretty easy to add them directly.
