### ISSUE TITLE
proposal:  set `line_length=120` for all tools

### ISSUE THREAD

**Issue by exiledkingcc** [py-pdf/pypdf#2132]
in pyproject.tml
```
[tool.isort]
line_length = 79

[tool.ruff]
line-length = 120
```
and for `black`, it's default value is 88 since no explicit value set for it.

personal opinion, 88 is small for `black`, which makes `if / else` statements have many brackets and lines.
not good for readability.

**Comment by MartinThoma** [comment]
I'd rather have 79 characters consistently than 120. I read diffs online a lot and I hate it if there is a line wrap.

**Comment by MartinThoma** [comment]
https://softwareengineering.stackexchange.com/a/222998/25699 phrases my opinion on this topic pretty well.

If there are specific lines which you want to make shorter / seem currently unreadable, let me know :-)

As long as this is just personal preference, I'd rather not open this can of worms again :smile:  Everybody has an opinion on this topic, but there is no widely accepted standard. The three camps I've seen are:

* 79/80/88 characters: Reading ergonmics, if it's too long it becomes hard to read. Also 3-way merges or diffs on small-ish screens and web interfaces become harder to read. I fall in that camp.
* 120 characters: I haven't seen clear arguments for that specific length, although it pops up once in a while
* 140/180/more characters: "I have high resolution screen, so I don't understand why others want line length limits"

As long as this is just personal preference, I'd rather not open this can of worms again :smile: For this reason, I'll close it now.
