### ISSUE TITLE
Some PDF files cannot be merged

### ISSUE THREAD

**Issue by JIMhackKING** [py-pdf/pypdf#2166]
I try to merge some pdf and it raise an error, the fails pdf file can open by others pdf reader software or Chrome.
I attempting to merge some PDFs, but it raised an error while executing the `merger.append`, and the PDF files that caused the error can be opened by the PDF reader software or Chrome.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# Windows-10-10.0.17763-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
# pypdf==3.15.5, crypt_provider=('cryptography', '41.0.2'), PIL=9.4.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfMerger
output_pdf_merger = PdfMerger()
with open("a.pdf", 'rb') as f:
    output_pdf_merger.append(f)
```

The pdf file: [Error pdf](https://drive.google.com/file/d/1gupU7r-2M8ZYi4gLEP9JGi0YaQsx6y6y/view?usp=drive_link)

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Python37\lib\site-packages\pypdf\_utils.py", line 468, in wrapper
    return func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pypdf\_merger.py", line 308, in append
    self.merge(len(self.pages), fileobj, outline_item, pages, import_outline)
  File "C:\Python37\lib\site-packages\pypdf\_utils.py", line 468, in wrapper
    return func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pypdf\_merger.py", line 208, in merge
    outline = reader.outline
  File "C:\Python37\lib\site-packages\pypdf\_reader.py", line 830, in outline
    return self._get_outline()
  File "C:\Python37\lib\site-packages\pypdf\_reader.py", line 866, in _get_outline
    outline_obj = self._build_outline_item(node)
  File "C:\Python37\lib\site-packages\pypdf\_reader.py", line 1040, in _build_outline_item
    outline_item = self._build_destination(title, dest)
  File "C:\Python37\lib\site-packages\pypdf\_reader.py", line 1004, in _build_destination
    return Destination(title, page, Fit(fit_type=typ, fit_args=array))  # type: ignore
  File "C:\Python37\lib\site-packages\pypdf\generic\_data_structures.py", line 1490, in __init__
    ) = args
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by pubpub-zz** [comment]
PdfMerger is obsolete, please use PdfWriter (using same syntax)

**Comment by JIMhackKING** [comment]
> PdfMerger is obsolete, please use PdfWriter (using same syntax)

It raise the same error.

**Comment by pubpub-zz** [comment]
the issue is due to destinations in the outlines which are of XYZ type but without parameter. Looking at the pdf spec, xyz is expected with 2 or 3 arguments normally, however acrobat accepts no arguments (and then jump to the center of the page)
I've robustified to accept no arguments for all destination types

**Comment by MartinThoma** [comment]
Thanks for raising the issue @JIMhackKING ! If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

The issue should be fixed in the latest version of pypdf :-)

**Comment by JIMhackKING** [comment]
> Thanks for raising the issue @JIMhackKING ! If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html
> 
> The issue should be fixed in the latest version of pypdf :-)

First of all, thank you for handling this issue so quickly : ). I feel very honored and grateful for your kindness in joining the contributors, but I only reported an issue and did not make a great contribution, so there is no need to add me to the contributors. Thank you again.
