### ISSUE TITLE
Variable declared and override in same file

### ISSUE THREAD

**Issue by Piloudev** [py-pdf/pypdf#2181]
A variable is override in the source code.

## Code

Is it normal that "/.notdef" is declared (first link) and override in the same file later (second link) :

https://github.com/py-pdf/pypdf/blob/main/pypdf/_codecs/adobe_glyphs.py#L51
https://github.com/py-pdf/pypdf/blob/main/pypdf/_codecs/adobe_glyphs.py#L13968

**Comment by pubpub-zz** [comment]
From my analysis/Memories,
on L51, it was a default value originally defined, but later (in time) it seemed more clever to have a square (more visual) for the character (L13968).

This character is here just "in case", but I don't think this definition has ever been used.

Any way, I agree L51 could be removed. 
Can you prepare a PR ?

**Comment by Piloudev** [comment]
But why it has been replaced ?
If it's not present in this repo (https://github.com/adobe-type-tools/agl-aglfn/tree/master), does "/.notdef" should be removed at all ?

**Comment by pubpub-zz** [comment]
What I mean just remove the entry in L51 😉 : there will be only the good one

**Comment by pubpub-zz** [comment]
@Piloudev, was I clear enough? I'd rather you do the PR as you did a good analysis.😊

**Comment by Piloudev** [comment]
I let you fix it, no problem. I not really have the time :)

**Comment by pubpub-zz** [comment]
@Piloudev 
3 mins job 😉
