### ISSUE TITLE
Understand function b_

### ISSUE THREAD

**Issue by Piloudev** [py-pdf/pypdf#2187]
I just wanted to understand this function "b_" and know why this is necessary.
Maybe a possibility to improve it : 

https://github.com/py-pdf/pypdf/blob/fb3548538a90ce8cb0773a62131801631ba28276/pypdf/_utils.py#L330

**Comment by stefan6419846** [comment]
This basically is an optimized version of a conversion function from strings to bytes, employing a lookup dictionary for speed improvements.

This has been introduced in 2012 in an effort to ensure compatibility of PyPDF with both Python 2 and 3: https://github.com/py-pdf/pypdf/commit/bcafcff11374e11abaaf6608eb5715bc9a7dff59#diff-8516c4bbb48f9fc4c464f9fae6dc4b84a0943f56e5159a0723d867fb366abfffR135-R166 The caching has been added in https://github.com/py-pdf/pypdf/commit/38417347e86f2ca5ceb650a50a5a6200bfd97340

What improvements do you have in mind?

**Comment by Piloudev** [comment]
How the cache works ?

Here we have a variable
```python
B_CACHE: Dict[Union[str, bytes], bytes] = {}
```

Here is the initialization (or copy) but B_CACHE is not used anymore after ? No data seems to be add in B_CACHE (in the cache dictionary)
```python
bc = B_CACHE
```

Tell me if I'm wrong

**Comment by pubpub-zz** [comment]
remember that `bc = B_CACHE` makes just bc points at B_CACHE memory (it creates a synonym to access the same object in memory)
all "additions" to the dictionary in lines 339 and 344 are modifying B_CACHE
> https://github.com/py-pdf/pypdf/blob/fb3548538a90ce8cb0773a62131801631ba28276/pypdf/_utils.py#L330-L345

**Comment by Piloudev** [comment]
Alright thanks! 
When does the B_CACHE will be reset ? If I create multiple PdfReader does it will be reset between each PdfReader or not ? :)

**Comment by pubpub-zz** [comment]
B_CACHE is never reset as it is a global variable. It's normally not growing a lot
to see How I did just select the whole text in my thread, select "quote" and you will see the "code" I've used 😉

OK to close this thread ?
