### ISSUE TITLE
BUG: text position detection works worse than in PyPDF2

### ISSUE THREAD

**Issue by vors** [py-pdf/pypdf#2200]
I'm trying to add a highlighting annotation to the doc using the text visitor to identify the coordinates to add it.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-13.5.2-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.16.1, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

repro repo https://github.com/vors/pypdf-highlighting-repro

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

You can add them to your tests.

## Visuals

![image](https://github.com/py-pdf/pypdf/assets/816680/8f65b414-9864-4cc6-b6ba-118b46a9cc4e)

**Comment by pubpub-zz** [comment]
this is a regression that seems to be due to #2060 
Under analysis to find the fix

**Comment by MartinThoma** [comment]
I think we might need a rendered image for testing.

**Comment by pubpub-zz** [comment]
> I think we might need a rendered image for testing.

Can you clarify which image you are talking about?

**Comment by pubpub-zz** [comment]
test file:
[page_178.pdf](https://github.com/py-pdf/pypdf/files/12675974/page_178.pdf)

**Comment by stefan6419846** [comment]
> > I think we might need a rendered image for testing.
> 
> Can you clarify which image you are talking about?

This probably still needs to be generated. Similar to the watermarking tests, render an image from the page with the corresponding highlighting as in the original issue description and check that it matches the expected position.

Nevertheless, I am not sure whether this really is required to detect such issues, as a plain text position test with a set of words/text snippets and their positions should do the same while not requiring any outside rendering.

**Comment by pubpub-zz** [comment]
> Nevertheless, I am not sure whether this really is required to detect such issues, as a plain text position test with a set of words/text snippets and their positions should do the same while not requiring any outside rendering.

I've been able to check the position through pdf inline content analysis and confirmed with PDF-XChange Editor which provides the coordinate of the cursor.

**Comment by MartinThoma** [comment]
I meant an image which doesn't exist so far. Something similar to the merge page rendering tests.
