### ISSUE TITLE
Update copyright info in documentation footer?

### ISSUE THREAD

**Issue by marcstober** [py-pdf/pypdf#2204]
The footer of each page in the [documentation](https://pypdf.readthedocs.io/en/latest/meta/history.html#pypdf-back-to-the-roots-2023-today) says: `© Copyright 2006 - 2008, Mathieu Fenniak.`

With gratitude to Mathieu for early work on this project, I wonder if this should be updated. Perhaps: `© Copyright 2006 - 2023, Mathieu Fenniak and pypdf contributors.`

The code that controls this appears to be here: https://github.com/py-pdf/pypdf/blob/main/docs/conf.py#L28

## Environment

N/A

## Code + PDF

N/A

## Traceback

N/A

**Comment by pubpub-zz** [comment]
This sound good. Can you propose a PR as you've found the good way to do it ?

**Comment by MartinThoma** [comment]
Thank you for updating it :-)
