### ISSUE TITLE
ENH: Remove only raster graphics

### ISSUE THREAD

**Issue by pbrus** [py-pdf/pypdf#2208]
The documentation contains two examples regarding image extraction:

- [images extraction](https://pypdf.readthedocs.io/en/stable/user/extract-images.html)
- [removing images](https://pypdf.readthedocs.io/en/stable/user/file-size.html?#removing-images)

This works as expected for pages containing embedded raster graphics. For example:

```python
from pypdf import PdfReader, PdfWriter


# PDF: https://github.com/py-pdf/pypdf/blob/main/resources/GeoBase_NHNC1_Data_Model_UML_EN.pdf
reader = PdfReader("GeoBase_NHNC1_Data_Model_UML_EN.pdf")

page = reader.pages[0]
count = 0

for image_file_object in page.images:
	with open(str(count) + image_file_object.name, "wb") as fp:
		fp.write(image_file_object.data)
		count += 1

writer = PdfWriter()
writer.add_page(page)
writer.remove_images()

with open("out.pdf", "wb") as f:
	writer.write(f)
```
As a result we get two images and a new PDF document without these images. When we change the page from 0 to the last one:
```python
page = reader.pages[18]
```
We get only reduced PDF document:

![image](https://github.com/py-pdf/pypdf/assets/19304263/e3fd66fe-b790-4939-9c3e-3867f2e6cc8f)

Some background images have disappeared (they look like vector graphics) and they are not store in separate files.

This might look like a bug but I suppose that you are aware of that (that's the reason to request a new feature instead of a bug). Nevertheless, it could be great to have a feature allowing to extract only raster graphics to separate files and don't touch vector graphics (or extract them but also with text which might be very hard as I guess).

**Comment by pubpub-zz** [comment]
`remove_images()` is designed to remove all images(and drawings)
This is a new feature. Feasability under analysis

**Comment by pubpub-zz** [comment]
@MartinThoma 
I would like your opinion:
a) looking deeper in the code I've observed that inline images are not deleted with `remove_images()` does not remove inline images. This does not sound normal to me
b) I would propose the following prototype:
```
XOBJECT_IMAGES = 1
INLINE_IMAGES = 2
DRAWING_IMAGES  = 4
ALL_IMAGES = 7
def remove_images(self, image_type:int = ALL_IMAGES;ignore_byte_string_object: Optional[bool] = None) -> None:
```
your opinion

**Comment by MartinThoma** [comment]
> a) looking deeper in the code I've observed that inline images are not deleted with remove_images() does not remove inline images. This does not sound normal to me

Yes, that is a bug. It should delete inline images (I vaguely remember that this was also documented somewhere)

**Comment by pubpub-zz** [comment]
> b) I would propose the following prototype:
> 
> ```
> XOBJECT_IMAGES = 1
> INLINE_IMAGES = 2
> DRAWING_IMAGES  = 4
> ALL_IMAGES = 7
> def remove_images(self, image_type:int = ALL_IMAGES;ignore_byte_string_object: Optional[bool] = None) -> None:
> ```

your opinion?

**Comment by MartinThoma** [comment]
Making it more flexible is a similar issue as with https://github.com/py-pdf/pypdf/pull/1831 .

The solution proposed there is to add a function which gets metadata about the annotation and returns True (delete) or False (don't delete).

That is for sure the more flexible design and allows easier extension.

I'm currently writing a proposal going in that direction :-) Give me a few minutes xD You're too fast xD

**Comment by MartinThoma** [comment]
What do you think about the following:

```
class ImageType(Enum):
    XOBJECT_IMAGES = auto()
    INLINE_IMAGES = auto()
    DRAWING_IMAGES  = auto()

@dataclass
class ImageData:
    image_type: ImageType
    ... # potentially more information, e.g. the name, the size, the encoding, position in the page, reference to the image object, ...

def constant_true(image_data: ImageData) -> bool:
    return True

def remove_images(self, ignore_byte_string_object: Optional[bool] = None, to_delete: Callable[[ImageData], bool] = constant_true) -> None: ...
```

**Comment by MartinThoma** [comment]
I'm looking for similar functions:

* Python built-in `filter`
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html : No callable, just single parameters
* https://numpy.org/doc/stable/reference/generated/numpy.delete.html : No callable, just indices that should be deleted: That is actually pretty nice. Then we have a very clean `remove_images(..., delete_indices=None)` where `None` means all. And if anybody wants something more complex, they need to iterate over the images first and give us the ones that should be removed.
* https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.filter.html : The parameter is called "condition", but that sounds not super clear to me in our context.

**Comment by MartinThoma** [comment]
Weird little finding: I thought `None` might be a bad default as it doesn't sound like "all". The ellipsis `...` might be clearer, but I have only seen it as a placeholder so far. Turns out, one can use it:

```
def mul(a, b=...):
    if b == ...:
        return "all indices"
    return a*b

print(mul(2))
```

I'm not sure if that is a good idea though :sweat_smile:

**Comment by pubpub-zz** [comment]
> ```python
> class ImageType(Enum):
>     XOBJECT_IMAGES = auto()
>     INLINE_IMAGES = auto()
>     DRAWING_IMAGES  = auto()
> 
> @dataclass
> class ImageData:
>     image_type: ImageType
>     ... # potentially more information, e.g. the name, the size, the encoding, position in the page, reference to the image object, ...
> 
> def constant_true(image_data: ImageData) -> bool:
>     return True
> 
> def remove_images(
>     self,
>     ignore_byte_string_object: Optional[bool] = None,
>     to_delete: Callable[[ImageData], bool] = constant_true
> ) -> None: ...
> ```

`ignore_byte_string_object` is deprecating and I'm pretty sure rarely used. I would rather put to_delete in second pos. 
with the type we can identify if to_delete has been forgotten.

**Comment by pubpub-zz** [comment]
> Weird little finding: I thought `None` might be a bad default as it doesn't sound like "all". The ellipsis `...` might be clearer, but I have only seen it as a placeholder so far. Turns out, one can use it:
> 
> ```
> def mul(a, b=...):
>     if b == ...:
>         return "all indices"
>     return a*b
> 
> print(mul(2))
> ```
> 
> I'm not sure if that is a good idea though 😅

None is more common for me.

**Comment by MartinThoma** [comment]
> also I Propose to have class ImageType(Flag)

Sounds good :+1: 

> None is more common for me.

Also good :+1: 

> ignore_byte_string_object is deprecating and I'm pretty sure rarely used. I would rather put to_delete in second pos.
**with the type we can identify if to_delete has been forgotten.**

Then it's fine to me :+1: 

What do you think about using the `delete_indices` solution?
