### ISSUE TITLE
Stamp is scaled

### ISSUE THREAD

**Issue by Mark0ne** [py-pdf/pypdf#2221]
When using `page.merge_page(wmPage, over=True)` to apply a stamp, the stamp is scaled

## Environment

Windows 10 x64, Python 3.10 x64

```bash
$ python -m platform
Windows-10-10.0.19045-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.16.2, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=9.0.1
```

## Code

```python
from pypdf import PdfWriter, PdfReader, Transformation
from os import remove as fileDelete
import os.path

OUT_PATH = r"TMP_OUT.pdf" #Path
SRC_PAGE = r"PAGE.pdf"
WM_PAGE = r"PDF_WATERMARK.pdf"

if __name__=="__main__":
    pdfOut = PdfWriter() #Blank writer
    pdfOut.append(SRC_PAGE)
    
    wmPage = PdfReader(WM_PAGE).pages[0]
    for page in pdfOut.pages:
        page.merge_page(wmPage, over=True) #False (watermark does not seem to mirror.)

    if os.path.exists(OUT_PATH):
            fileDelete(OUT_PATH)
    pdfOut.write(OUT_PATH)
    pdfOut.close()
```

## Problems

I've not fully diagnosed, but it looks like if the `WM_PAGE` is a different resolution (DPI) then it appears at a different scaling. This is perhaps less of an issue, but would appreciate some tips to correct it.

**Comment by stefan6419846** [comment]
* Please check whether 3.16.2 fixes this, as there has been a recent change.
* You might want to call `page.transfer_rotation_to_content` before the merge as documented. Do you still see this behavior?

If both approaches do not work, please provide corresponding PDF files for further analysis.

**Comment by Mark0ne** [comment]
Thanks.
3.16.2 **does fix the mirror issue**.  I'm still left with the scaling issue. I'm pretty sure this is related to document resolution mismatch.....I'll spend some more time debugging and report my findings.

**Comment by Mark0ne** [comment]
Scaling issue solved with 
```Python
pageRect = pdfOut.pages[0].mediabox
wmPage.scale_to(pageRect.width,pageRect.height)
```

Many thanks all solved and no issue.

**Comment by MartinThoma** [comment]
I've edited the title and the top post as the mirroring-issue is already fixed and documented via #2191 and fixed via #2203  in `pypdf>=3.16.2`

**Comment by MartinThoma** [comment]
Oh, nice!

So was it related to different resultions?

**Comment by Mark0ne** [comment]
I believe it was:
- two pages from the same source will appear at the same scale (when one is stamped over the other). 
- the watermark page I'm using was created in GIMP for windows. It has reduced resolution DPI (72 or 100...can't recall right now).

_So fast_ compared to the previous version of pypdf I was using. Some huge improvements! Many thanks
