### ISSUE TITLE
Wrong contributor list/mentions

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#2245]
The contributor list of tagged releases is wrong when the display name and username do not match.

Let's take https://github.com/py-pdf/pypdf/releases/tag/3.16.3 for example:

* I am attributed to https://github.com/Stefan
* #2232 is attributed to https://github.com/markpfeifle

I think this is undesired as it attributes the wrong persons and might even notify the wrong users for stuff they did never touch.

When using the GitHub website, an automated/corrected changelog would probably be generated (there is a button for auto-generating it).

**Comment by MartinThoma** [comment]
I'm sorry. I fixed it manually. However, we need to make sure its automatically correct.

**Comment by MartinThoma** [comment]
The problem is that I'm interpreting that line as the author: https://github.com/py-pdf/pypdf/blob/main/make_release.py#L286

**Comment by MartinThoma** [comment]
For you @stefan6419846 it is `Stefan <96178532+stefan6419846@users.noreply.github.com>` py-pdf/pypdf/pull/2241.patch ). I don't know where the `Stefan` comes from.  Can you check the `git config --list` (probably user.name)?

If you adjust that to `stefan6419846` you would automatically get the right result.

It would still be desirable that we connect the right users with their contributions, even if their git config doesn't match with their GitHub username.

**Comment by stefan6419846** [comment]
I did most of my changes on GitHub directly through their UI, as you can see on the commits of #2241 ("Verified" badges, clicking on them states "This commit was created on GitHub.com and signed with GitHub’s verified signature.") "Stefan" is the full/nice name I have set for display on GitHub itself.

**Comment by MartinThoma** [comment]
I guess then there is no way around using the Github API. As I don't know when I have the time to do so, I will likely add a work-around for you before (as you're contributing regularly).

**Comment by stefan6419846** [comment]
Using the GitHub API for this is rather easy in theory, but especially the rate limits might be something to care about.

The easiest way would be to call https://api.github.com/repos/py-pdf/pypdf/commits/552c8e0 for each commit hash and retrieve the value `result["author"]["login"]`. Unfortunately, this would only allow 60 commits per release due to the rate limits. Thus, I would probably rather settle with https://api.github.com/repos/py-pdf/pypdf/commits (maybe even with the maximum of 100 results per page instead of the default 30) and match the commit hashes manually. This reduces the number of queries and avoids hitting the rate limit too quickly.

If desired, I might submit a corresponding PR for updating the `make_release.py` script accordingly.
