### ISSUE TITLE
请问，扫描件的pdf文件是无法提取文本的吗

### ISSUE THREAD

**Issue by honghuayoutiao** [py-pdf/pypdf#2255]
Replace this: What happened? What were you trying to achieve?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# TODO: Your output goes here

$ python -c "import pypdf;print(pypdf._debug_versions)"
# TODO: Your output goes here
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
# TODO: Your code goes here
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete Traceback I see:

```
# TODO: Your Traceback goes here (if applicable)
```

**Comment by pubpub-zz** [comment]
@honghuayoutiao 
please provide issues in english. like this we will have to close it

**Comment by stefan6419846** [comment]
There are multiple things about this issue which should be fixed:

* Please report in English only.
* Please fill the complete issue template and do not leave it blank.

Regarding the request itself:

> Excuse me, is it impossible to extract text from scanned pdf files?

This should rather be a discussion if it is still unclear after reading the docs: https://pypdf.readthedocs.io/en/latest/user/extract-text.html There is a corresponding section about scanned PDF files as well. To summarize it: In general no, although if you or your scanning device add a (valid) text layer beforehand (using OCR or similar), you can of course extract it.
