### ISSUE TITLE
Import/Export annotations to FDF/JSON format

### ISSUE THREAD

**Issue by mah-emad** [py-pdf/pypdf#2291]
Support importing/exporting annotations to FDF format or json format.

**Comment by stefan6419846** [comment]
For me this sounds like something which is better suited in https://github.com/py-pdf/pdfly.

**Comment by MartinThoma** [comment]
We could already export annotations in JSON format.

For FDF, we would need the basis in pypdf.

**Comment by MartinThoma** [comment]
FDF was already mentioned here: https://github.com/py-pdf/pypdf/discussions/1181

I'm closing this issue as there is nothing to do in pypdf.

**Comment by MartinThoma** [comment]
@mah-emad Would adding the import/export feature to [pdfly](https://pypi.org/project/pdfly/) solve your issue?

**Comment by mah-emad** [comment]
@MartinThoma Yes, I can use pdfly for import/export. does pdfly support exporting annotations/signatures to JSON already?

**Comment by MartinThoma** [comment]
Not so far, but we can add that :-) 

At the moment, this is possible:

![image](https://github.com/py-pdf/pypdf/assets/1658117/744be016-27b5-4206-b6d4-89654ab1e62a)

Let's continue the discussion at https://github.com/py-pdf/pdfly/issues/37 :-) Please let us know what your requirements are and also a bit of the background (what do you want to do/why do you want to do that/what have you tried before and why didn't that work for you)
