### ISSUE TITLE
Watermark (Underlay) with Google Doc PDFs Not Working

### ISSUE THREAD

**Issue by alaksana96** [py-pdf/pypdf#2292]
Hey team, 

I'm debugging an issue where a watermark we are trying to add to our documents isn't working properly. 

I've narrowed it down to the fact that the document we are trying to watermark was generated in Google Docs.

**When trying to add an underlay to a PDF generated in Google Docs, the underlay does not appear at all.**

To be sure, I used the following documents from the [pypdf Sample Files](https://github.com/py-pdf/sample-files) for testing:

- https://github.com/py-pdf/sample-files/blob/main/001-trivial/minimal-document.pdf
- https://github.com/py-pdf/sample-files/blob/main/011-google-doc-document/google-doc-document.pdf

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-14.0-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.0, crypt_provider=('cryptography', '41.0.5'), PIL=10.0.0
```

## Code + PDF

The issue occurs when we set `over=False` and attempt to underlay the `watermark.pdf` on the `google-doc-document.pdf`.

The watermark does not appear in the top right corner.

```python
import pypdf
stamp = pypdf.PdfReader("watermark.pdf").pages[0]
document = pypdf.PdfReader("google-doc-document.pdf")
writer = pypdf.PdfWriter()

page_indices = list(range(0, len(document.pages)))
for index in page_indices:
    content_page = document.pages[index]
    content_page.merge_transformed_page(
        stamp,
        pypdf.Transformation()
        .scale(0.25)
        .translate(content_page.mediabox[2] * 0.8, content_page.mediabox[3] * 0.85),
        over=False, #True
    )
    writer.add_page(content_page)

writer.write("results/google-doc-document-stamped-over-false.pdf")
```

I've attached the necessary files to replicate below (using the `google-doc-document.pdf`):
[watermark.pdf](https://github.com/py-pdf/pypdf/files/13326314/watermark.pdf)
[google-doc-document-stamped-over-true.pdf](https://github.com/py-pdf/pypdf/files/13326315/google-doc-document-stamped-over-true.pdf)
[google-doc-document-stamped-over-false.pdf](https://github.com/py-pdf/pypdf/files/13326316/google-doc-document-stamped-over-false.pdf)

As a sanity check, I also ran the same code against the `minimal-document.pdf`
[minimal-document-stamped-over-false.pdf](https://github.com/py-pdf/pypdf/files/13326333/minimal-document-stamped-over-false.pdf)
[minimal-document-stamped-over-true.pdf](https://github.com/py-pdf/pypdf/files/13326334/minimal-document-stamped-over-true.pdf)

**We can see for the `minimal-document-stamped-over-false.pdf`, the underlay works fine with `over=False`, whereas with the the `google-doc-document-stamped-over-false.pdf`, the underlay is not visible at all.**

#### `google-doc-document-stamped-over-true.pdf`
![Screenshot 2023-11-11 at 19 25 56](https://github.com/py-pdf/pypdf/assets/17803005/a2891a7d-f1de-4261-8e21-6770b04fc029)

#### `google-doc-document-stamped-over-false.pdf`
![Screenshot 2023-11-11 at 19 26 25](https://github.com/py-pdf/pypdf/assets/17803005/55d5c85f-3e52-4c40-8d82-1c8539f4bca7)

#### `minimal-document-stamped-over-false.pdf`
![Screenshot 2023-11-11 at 19 30 12](https://github.com/py-pdf/pypdf/assets/17803005/97c3d634-5f1b-483c-98e6-e9545a4a1bf3)

#### `minimal-document-stamped-over-true.pdf`
![Screenshot 2023-11-11 at 19 30 49](https://github.com/py-pdf/pypdf/assets/17803005/5f458add-1f4c-4139-9f3f-8ab724728ccc)

**Comment by pubpub-zz** [comment]
your pdf contains some instructions to create a white back ground:
if you look at page1 content of https://github.com/py-pdf/pypdf/files/13326315/google-doc-document-stamped-over-true.pdf
you will see
```
q
  1 0 0 -1 0 842 cm
  q
    0.75 0 0 0.75 0 0 cm
    1 1 1 RG
    1 1 1 rg
    /G3 gs
    0 0 794 1123 re
    f
  Q
```
which - unless I'm wrong - creates a white area threrefore it hides the stamping. the stamp is an image which is RGB only without any mask : it hides also the text  in [minimal-document-stamped-over-true.pdf](https://github.com/py-pdf/pypdf/files/13326334/minimal-document-stamped-over-true.pdf)

The behavior is in accordance with expectation.

**Comment by alaksana96** [comment]
You are right, it does have a white background on it. I had tried using a transparent PNG as a base image and converting that to a PDF, but it caused rendering issues in Firefox

![Screenshot 2023-11-12 at 14 22 31](https://github.com/py-pdf/pypdf/assets/17803005/9f09e80c-33c8-4de0-9120-a2abea8deb7e)

However, I don't fully understand why in [minimal-document-stamped-over-false](https://github.com/py-pdf/pypdf/files/13326333/minimal-document-stamped-over-false.pdf) the stamp is completele visible, despite being under the page content, but in [google-doc-document-stamped-over-false](https://github.com/py-pdf/pypdf/files/13326316/google-doc-document-stamped-over-false.pdf), the stamp is completely not visible?

**Comment by pubpub-zz** [comment]
about your issue, check with other reader if the PDF is good or not. If not you should report a bug in pdf.js project within github.
also try to use Pillow to convert your transparent image it should work (load as an image and save it as a pdf)

about [google-doc-document-stamped-over-false](https://github.com/py-pdf/pypdf/files/13326316/google-doc-document-stamped-over-false.pdf) I've not check but pretty sure there is not this white background added

**Comment by alaksana96** [comment]
I checked for you in [google-doc-document-stamped-over-false]() and for the same block, you get the following, so there is no white background added.
```
/image Do
Q
Q
```

That still doesn't explain why the stamp is not visible at all in that document? The fact that it appears in ([minimal-document-stamped-over-false](https://github.com/py-pdf/pypdf/files/13326333/minimal-document-stamped-over-false.pdf))[] should suggest that it should appear on all PDF documents when `over=False`?

**Comment by pubpub-zz** [comment]
With more details:
https://github.com/py-pdf/pypdf/files/13326333/minimal-document-stamped-over-false.pdf
![image](https://github.com/py-pdf/pypdf/assets/4083478/08c3a100-ff1d-4e2a-a8b5-4984e692bebe)

https://github.com/py-pdf/pypdf/files/13326316/google-doc-document-stamped-over-false.pdf
![image](https://github.com/py-pdf/pypdf/assets/4083478/ea9307f8-4b19-4667-a9a5-f0d78aab9d8f)

**Comment by alaksana96** [comment]
Thank you! Thats a very clear explanation!

Thats quite interesting behaviour, seeing as we run the same code snippet for both files (besides changing the input files). 

It makes me think that perhaps Google Docs PDFs always have that white background set by default?

Might be worth moving this issue to a discussion instead

**Comment by pubpub-zz** [comment]
I close this issue as non relevant to pypdf
