### ISSUE TITLE
Problem with forms written by pypdf4

### ISSUE THREAD

**Issue by eyesonly13** [py-pdf/pypdf#2293]
Hello, forms written by pypdf don't show directly on acrobat reader. When I clicked on the field, the text show but when I clicked on other parts of padf, the text show off

import PyPDF2

reader = PyPDF2.PdfReader("kenzi.pdf")
writer = PyPDF2.PdfWriter()

for page in reader.pages:
    writer.add_page(page)

fields = reader.get_fields()

writer.update_page_form_field_values(writer.pages[0],{"Nom ou raison sociale":"zain"})

with open("zain.pdf.pdf","wb") as pdf:
    writer.write(pdf)

**Comment by MartinThoma** [comment]
pypdf4 is a different project
