### ISSUE TITLE
Text form is so big

### ISSUE THREAD

**Issue by eyesonly13** [py-pdf/pypdf#2294]
Hello, the text of form is very big

![Capture](https://github.com/py-pdf/pypdf/assets/100468986/6e193973-2005-4e2b-856d-b1e7f97b9e28)

```
class Pdf:
    def __init__(self, filename):
        self.reader = pypdf.PdfReader(filename)
        self.writer = pypdf.PdfWriter()

        
        if "/AcroForm" in self.reader.trailer["/Root"]:
            self.writer._root_object.update({
                pypdf.generic.NameObject("/AcroForm"): self.reader.trailer["/Root"]["/AcroForm"]
            })

        for page in self.reader.pages:
            self.writer.add_page(page)

    def get_checkbox(self, dictionnary, filename_save):
        self.writer.update_page_form_field_values(self.writer.pages[0], dictionnary)
        with open(filename_save, "wb") as pdf:
            self.writer.write(pdf)
```

**Comment by pubpub-zz** [comment]
a) please prefer to use the standard form to provide all the data: actually the PDF file is missing to be able to perform analysis
b) you are using add_page and update independantly. but you are then  loosing acroform links between each others: use `self.writer = pypdf.PdfWriter(clone_from=self.reader)`

**Comment by eyesonly13** [comment]
I don't understand this sentence : a) please prefer to use the standard form to provide all the data: actually the PDF file is missing to be able to perform analysis

Thanks to help :)

**Comment by pubpub-zz** [comment]
> I don't understand this sentence : a) please prefer to use the standard form to provide all the data: actually the PDF file is missing to be able to perform analysis
> 
> Thanks to help :)

use the github bug form/template proposed

**Comment by pubpub-zz** [comment]
@eyesonly13 can you provide update?

**Comment by MartinThoma** [comment]
I'm closing this issue for the moment. If we receive an update, we can re-open.
