### ISSUE TITLE
How to modify text in existing pdf file?

### ISSUE THREAD

**Issue by danilyef** [py-pdf/pypdf#2298]
I want to modify text in existing pdf file and rewrite it. I didn't find any tutorial on github and apologize, if I missed it

## Code

```
input_pdf = PdfReader(r"my_pdf.pdf")
output_pdf = PdfWriter()
# read pdf file
passwords = {"pwd", "password", "passwort", "kennwort",'pw'}

for num_page,page in enumerate(input_pdf.pages):
    page_text = page.extract_text()
    splited_lines = page_text.splitlines()
    for i,line in enumerate(splited_lines):

        #delete password
        splited_lines[i] = remove_passwords(line)

    page_text = '\n'.join(splited_lines)
```

in this code I modified text and I want to insert it back. 
How can I do it?

**Comment by pubpub-zz** [comment]
Changing a text is a very tough subject as there is many way to write down a text. Pypdf can't propose a function to do that. Sorry

**Comment by MartinThoma** [comment]
See https://stackoverflow.com/q/31703037/562769
