### ISSUE TITLE
Unable to process pdf converted to bytes

### ISSUE THREAD

**Issue by BrianMwas** [py-pdf/pypdf#2299]
I have just installed the package and tried uploading a file using form data, passing the file to PdfReader gives an error, 

> path should be string, bytes, os.PathLike or integer, not FileStorage"

Not sure why it is doing so, but I have tried changing it to byte data and using temp file but still getting the same issue, here's my code

## Environment

```bash
$ python -m platform
macOS-13.2.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.1, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
try:
        # Check if we have files in the request otherwise sent the warning
        if 'document' not in request.files:
            return jsonify(status='No file found in request'), 400
        
        file = request.files['document']

        if file.filename == '' or not __allowed_file(file.filename):
            return jsonify(status='Invalid file type'), 400
        
        if os.path.getsize(file) > MAX_FILE_SIZE:
            return jsonify(status='File too large'), 400
        
        file_data = file.read()
        logging.info(f"file data {file_data}")

        with io.BytesIO(file_data) as file_buffer:
            byte_data = file_buffer.getvalue()
            # Extract the text from the file
            reader = PdfReader(byte_data)
            page = reader.pages[0]
            text = page.extractText()
            print(f"Text content: {text}")

        return jsonify(status='OK', text=text), 200
    except Exception as e:
        print(f"Error extracting text from pdf: {e}")
        return jsonify(status=f'Error processing file {e}'), 500
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests! I am using postman, so any pdf will do

## Traceback

This is the complete Traceback I see:

```
Am just getting the error, stat: path should be string, bytes, os.PathLike or integer, not FileStorage
```

**Comment by stefan6419846** [comment]
Please always provide complete code which could be executed - you are missing the *pypdf* imports. Additionally, where is the `FileStorage` class coming from?

```
file_data = file.read()
with io.BytesIO(file_data) as file_buffer:
    byte_data = file_buffer.getvalue()
    reader = PdfReader(byte_data)
```

is the same as just doing `reader = PdfReader(file_data)`. You probably want `reader = PdfReader(file_buffer)`, given that `file_data` contains byte data. This still will not solve the issue with the type of `file`/`file_data`, but this unclear from your code and does not look like an issue with *pypdf*, but in the way you use the other third-party library which provides the PDF data.

By the way: `page.extractText()` has been replaced by `page.extract_text()`.

**Comment by stefan6419846** [comment]
As already mentioned, I do not think there is something wrong on the *pypdf* side, but rather with how you retrieve the PDF file from Flask.

Which type do `file` and `file_data` have? Looking at the *FileStorage* class probably used by Flask, it does not have a `.read()` method and you might want to pass the `.stream` attribute into *pypdf*: https://github.com/pallets/werkzeug/blob/main/src/werkzeug/datastructures/file_storage.py

**Comment by MartinThoma** [comment]
This is clearly a flask usage error. Neither a bug in flask nor in pypdf. For this reason I'm closing the issue.

Feel free to still comment, but this is likely better suited in Stackoverflow. Something like "how do I get form data as bytes instead of FileStorage in flask?"
