### ISSUE TITLE
PNG image data is mishandled during extraction

### ISSUE THREAD

**Issue by syntax-surgeon** [py-pdf/pypdf#2318]
Hi all

I have been wanting to exract all images in a PDF file as separate image files. The process seems to be causing errors during the extraction of PNG images, however, the JPEG images seem to be working just fine. The script I am using is as follows:

```
import pypdf
from PIL import Image
import io

doc = pypdf.PdfReader("data/big_lorem_multipic.pdf")

for page in doc.pages:
    for image in page.images:
        #Approach 1
        # with open(f"data/{image.name}", "wb") as file:
        #     file.write(image.data)

        # Approach 2
        # image_bytes = io.BytesIO(image.data)
        # pil_image = Image.open(image_bytes)
        # pil_image.save(f"data/{image.name}")

        # Approach 3
        # image.image.save(f"data/{image.name}")
```

All the three approaches produce the same issue in which the JPEG image is saved perfectly, but the PNG images are not. What seems to be the issue here? I can see that a related bug fix (https://github.com/py-pdf/pypdf/pull/1834) was recently made but I still cannot identify the cause of this issue.

For reference I am attaching the PDF below. Thank you
[big_lorem_multipic.pdf](https://github.com/py-pdf/pypdf/files/13489277/big_lorem_multipic.pdf)

**Comment by stefan6419846** [comment]
It seems like the images masks are omitted during extraction.

**Comment by pubpub-zz** [comment]
with latest (dev) release, Images are properly readable. png are RGBA and I can not find any special
@stefan6419846 / @syntax-surgeon, can you confirm that the problem is now solved. 

I will close this PR as solved within 3 days for cleanup

**Comment by stefan6419846** [comment]
I have confirmed that it seems to work now.
