### ISSUE TITLE
index out of bounds in pypdf._text_extraction.handle_tj

### ISSUE THREAD

**Issue by rgwood-rely** [py-pdf/pypdf#2320]
On decoding a pdf in the second line:

    if orientation in orientations:
        if isinstance(operands[0], str):

len(operands) == 0 and it raises an ex.

Should change it to:

    if orientation in orientations and len(operands) > 0:

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-14.1.1-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.1, crypt_provider=('cryptography', '3.3.2'), PIL=10.1.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
# sorry; PDF is confidential
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete traceback I see:

```
<our software>
    page_text = page_obj.extract_text()
  File "/Users/rgwood/mambaforge/envs/e_16730_w3/lib/python3.9/site-packages/pypdf/_page.py", line 2279, in extract_text
    return self._extract_text(
  File "/Users/rgwood/mambaforge/envs/e_16730_w3/lib/python3.9/site-packages/pypdf/_page.py", line 2115, in _extract_text
    process_operation(b"Tj", operands)
  File "/Users/rgwood/mambaforge/envs/e_16730_w3/lib/python3.9/site-packages/pypdf/_page.py", line 2075, in process_operation
    text, rtl_dir = handle_tj(
  File "/Users/rgwood/mambaforge/envs/e_16730_w3/lib/python3.9/site-packages/pypdf/_text_extraction/__init__.py", line 220, in handle_tj
    if isinstance(operands[0], str):
IndexError: list index out of range
```

**Comment by pubpub-zz** [comment]
Without the PDF we can not analyse anything. If you agree email it privately with @MartinThoma
We will not disclose it

**Comment by pubpub-zz** [comment]
try:
```
import pypdf
w = pypdf.PdfWriter()
w.append("pdf_to_read.pdf",[0,2,5])  # the list
w.write("output.pdf")
```

**Comment by rgwood-rely** [comment]
That worked!

**Comment by rgwood-rely** [comment]
I sent a redacted pdf page to the above email instead of attaching here out of an abundance of caution.

**Comment by rgwood-rely** [comment]
Link to code position: https://github.com/py-pdf/pypdf/blob/38795f5cb23f1950c65a2928763747230db84374/pypdf/_text_extraction/__init__.py#L220

**Comment by stefan6419846** [comment]
Have you considered submitting a corresponding PR for this (the offending line has already been part of your initial traceback)? I cannot debug this without a PDF file, but it looks like we can have an early return due to an empty operands list here.

**Comment by rgwood-rely** [comment]
Hi Stefan. I've sent a PDF to info@martin-thoma.de as requested and yes this should be an easy fix. Will try and create a PR if I find a moment.

**Comment by rgwood-rely** [comment]
PR: rgwood-rely:rgwood/2320_fix_index_out_of_bounds_in_handle_tj
