### ISSUE TITLE
The read width and height of the page are the opposite of the actual

### ISSUE THREAD

**Issue by yangyunlv** [py-pdf/pypdf#2340]
Replace this: What happened? What were you trying to achieve?

When reading the size of some PDF pages, the "width" and "height" values are reversed, and the horizontal image is read as a vertical image, and sometimes the vertical image is read as a horizontal image.

Which environment were you using when you encountered the problem?

```bash
Windows-10-10.0.19044-SP0
python 3.8.10

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.1, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=9.5.0

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
width = page.mediabox[2]
height = page.mediabox[3]
```

[cs.pdf](https://github.com/py-pdf/pypdf/files/13649797/cs.pdf)

**Comment by stefan6419846** [comment]
The page is rotated, but the rotation has not been fully applied to the page:

```python3
from pypdf import PdfReader

file_path = 'cs.pdf'
page_idx = 0

reader = PdfReader(file_path)
page = reader.pages[page_idx]
print(page.mediabox.height, page.mediabox.width, page.rotation)
page.transfer_rotation_to_content()
print(page.mediabox.height, page.mediabox.width, page.rotation)
```
will display:

```
593 420 90
419.99999999999994 593.0 0
```

Thus, for such cases where the page geometry is flaky or the page is considered rotated, you probably want to fix the content rotation beforehand or account for the rotation yourself.

**Comment by yangyunlv** [comment]
So that's it,thank you.
