### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [py-pdf/pypdf#2349]
## Explanation

My name is McKenna Dallmeyer and I would like to submit pypdf to OSS-Fuzz. If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software. In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you!

**Comment by MartinThoma** [comment]
Thank you for thinking about pypdf :heart: 

I'm fine with adding pypdf to OSS-Fuzz. The process was already started: https://github.com/py-pdf/pypdf/issues/2031

I'm closing this as a duplicate

**Comment by MartinThoma** [comment]
I think I'll remove pypdf from OSS-Fuzz again. Something doesn't work and I don't see the value + don't have the energy to fix it.
