### ISSUE TITLE
Inconsistent usage of warnings

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#2354]
`warnings.warn` is currently not being used in a consistent manner:

* There is `pypdf._utils.deprecate` and `pypdf._utils.deprecation`, but some places use plain `warnings.warn` with the `DeprecationWarning` category.
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L274-L278
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L1286-L1290
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L1305-L1311
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L1745-L1751
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L2038-L2044
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L2083-L2089
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L2321-L2325
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L2363-L2367
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_writer.py#L2405-L2409
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_page.py#L361-L367
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_page.py#L375-L381
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_page.py#L2281-L2284
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_merger.py#L163-L169
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_merger.py#L702-L708
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_merger.py#L809-L815
* There are some plain `warnings.warn` with a different category. I am not sure whether they are eligble for converting them to `logger_warning` instead as there is not much which can be done on the user side anyway (besides submitting a PR to implement it ;)):
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_cmap.py#L183-L186
  * https://github.com/py-pdf/pypdf/blob/908797f8ff13f6c45a5faeff67db02d924a447dd/pypdf/_cmap.py#L192-L195

I would like to see this harmonized and I am open to submit a corresponding PR for this.

**Comment by MartinThoma** [comment]
My suggestion would be to wait two more weeks (until next year). Then we will remove quite a bit of deprecated code.

This will make it easier to find inconsistencies - which we should fix before the release!
I'll mark this issue so that we tackle this in the pypdf==4.0.0 release :-)

**Comment by MartinThoma** [comment]
I've just merged https://github.com/py-pdf/pypdf/pull/2367

The remaining warnings are:

https://github.com/py-pdf/pypdf/blob/main/pypdf/_cmap.py#L183-L186

https://github.com/py-pdf/pypdf/blob/main/pypdf/_cmap.py#L192-L195

**Comment by MartinThoma** [comment]
The `Advanced encoding {enc} not implemented yet` is not avoidable for the user, so warnings.warn is wrong (see [docs](https://pypdf.readthedocs.io/en/latest/user/suppress-warnings.html)).

@stefan6419846 In https://github.com/py-pdf/pypdf/issues/2356 you mention that warning. Do you think an Exception would have been better? I guess the effect was that a part of the text was not extracted, right?

**Comment by stefan6419846** [comment]
I personally do not have a strong opinion about whether this should be an exception or not. For my use case (basically identifying empty PDF files), `warnings.warn` or `logger_warning` are indeed more suitable than an error, as I usually have Latin texts only and the other cases tend to be invalid (spam, wrong OCR) anyway, but yes, the extracted text probably is incomplete.

The use-case or criticality of the error most likely  differs for other locales and use-cases, although I would argue that `warnings.warn` or `logger_warning` are sufficient to at least extract the extractable text, while indicating that something might be wrong/incomplete indeed.

**Comment by MartinThoma** [comment]
Maybe that would even be a good case for logging.Error:

* Avoiding an exception, as we might have extracted a part of the important stuff
* Indicating (maybe with a different message) that there might be something missing.
