### ISSUE TITLE
 UnicodeEncodeError: 'charmap' codec can't encode character '\u25b6' in position 0:   character maps to <undefined>

### ISSUE THREAD

**Issue by sunaarun** [py-pdf/pypdf#2368]
I am new to Python and I am developing a program that takes a PDF file as input and converts it into text, I am using Python3 and tried both (PyPDF2 and PDFMiner.six) packages. for first pdf file it convert well and print it on console, but when I use another pdf file which contains some empty pages, it prints out the text, and when it reach the empty page , these error appears,

Please help me, I am new to Python and I appreciate your help Here is the code: PyPDF2

```
import PyPDF2


def extract_txt_pdf(pdf_file: str) -> [str]:
    with open(pdf_file, "rb") as pdf:
        reader = PyPDF2.PdfReader(pdf, strict=False)
        pdf_text = []
    for page in reader.pages:
        content = page.extract_text()
        pdf_text.append(content)
    return pdf_text
```

for PDFMiner.six

> from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from io import StringIO

def convert_pdf_to_txt(path):
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    codec = 'utf-8'
    laparams = LAParams()
    device = TextConverter(rsrcmgr, retstr, codec=codec, laparams=laparams)
    fp = open(path, 'rb')
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    password = ""
    maxpages = 0
    caching = True
    pagenos=set()
  
   for page in PDFPage.get_pages(fp, pagenos, maxpages=maxpages, 
      password=password,caching=caching, check_extractable=True):
    interpreter.process_page(page)

    text = retstr.getvalue()

fp.close()
device.close()
retstr.close()
return text

and  Here is the error for both code

`  print(t)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode  return codecs.charmap_encode(input,self.errors,encoding_table)[0]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  UnicodeEncodeError: 'charmap' codec can't encode character '\u25b6' in position 0: 
 character maps to <undefined>`

**Comment by MartinThoma** [comment]
Hey,

congratulations for your first step into software development!

I'm closing this issue, because:

1. PyPDF2 is deprecated and we don't handle issues in pdfminer (that is a different project)
2. You didn't use the error template and your description is lacking important information such as the PDF that causes the bug

Additionally, please check your formatting. At the end of the text input box there is a note "Markdown is supported". For example, you can make code blocks.
