### ISSUE TITLE
DEV: Improve contributing docs

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#2374]
At the moment, https://github.com/py-pdf/pypdf/blob/main/CONTRIBUTING.md tends to be quite sparse and does not link to the developer information inside the docs for example: https://pypdf.readthedocs.io/en/latest/dev/intro.html

We probably want improve this.

Background: PRs from new contributors tend to not use our desired naming scheme/prefixes. Ideally, we would add a corresponding check to the PR CI (either as part of the existing codestyle job or inside a separate one), but this requires that this is clear for contributors to avoid confusion. GitHub usually shows/links the `CONTRIBUTING.md` file when creating an issue or PR, especially for firs-timers.

**Comment by MartinThoma** [comment]
I'm open to suggestions how to change the CONTRIBUTING.md.

> PRs from new contributors tend to not use our desired naming scheme/prefixes. Ideally, we would add a corresponding check to the PR CI

Sounds like it might be something easy to implement (in CI) with a very clear error message, thus easy to fix for the contributor. It sounds also like something that would make my life easier :+1: 

We should make clear that we can support there. Something like: "If you don't know which one to choose or if multiple apply, make a best guess. Nobody will complain if it doesn't quite fit :-)"

**Comment by MartinThoma** [comment]
https://stackoverflow.com/a/71692835/562769 : 

```
on:
  push:
  pull_request:
   types: [opened, synchronize]

  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Title of PR
      run: echo The Title of your PR is ${{ github.event.pull_request.title }}
```

**Comment by stefan6419846** [comment]
I am going to see if I am able to create corresponding PRs tomorrow to improve this.
