### ISSUE TITLE
Tag image or attachment position in readtext

### ISSUE THREAD

**Issue by patrickitts** [py-pdf/pypdf#2392]
## Explanation

To be able to reconstruct a document (like an HTML page), it would be necessary to add a tag like [tagimage]1[/tagimage] in the extracted text at the place the image was found.
In the exemaple 1 is the place of the images in page.images

## Code Example

How would your feature be used? (Remove this if it is not applicable.)

```python
from pypdf import PdfReader, PdfWriter

...  # your new feature in action!
print(page.extract_text(withTags=1))

```
results :

some text
[tagimage]0[/tagimage]
other text
[tagimage]1[/tagimage]

**Comment by MartinThoma** [comment]
What is your use-case for which you would need this?

It sounds as if you wanted to convert a PDF to a HTML. There are tools for that; have you tried them?

**Comment by pubpub-zz** [comment]
the images are placed as floating objects. The proposal from Martin seems adequate. I propose to close it.
