### ISSUE TITLE
MAINT: Introduce a PdfReader property 'user_access_permissions'

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#2399]
As a user, I want to have a well-defined way how to read and write user access permissions in the context of the Standard Encryption Dictionary (Section 7.6.3.2 in 1.7 specs; also "Table 21 – Additional encryption dictionary entries for the standard security handler").

The user access permissions ("Table 22 – User access permissions" of the 1.7 specs) should be exposed as a property with the value `constants.UserAccessPermissions` on the reader. In that context, the `decode_permissions` should get deprecated.

See #2391.

**Comment by eabase** [comment]
This is not working!
See #2581
