### ISSUE TITLE
pypdf 3.17.4 (and many previous versions) add_uri doesn't work: incorrect "/TYPE"

### ISSUE THREAD

**Issue by pmiller66** [py-pdf/pypdf#2403]
Line 2448 of _writer.py:
                    NameObject(AA.Type): NameObject(PG.ANNOTS),

should read like this to make add_uri work:
                   NameObject(AA.Type): NameObject("/Annot"),

BTW, the pypdf is a wonderful capability and we have done amazing things with it.

**Comment by stefan6419846** [comment]
Could you please provide the missing details from the issue template, id est some complete code for reproduction, the complete stacktrace and an example PDF file?

**Comment by pmiller66** [comment]
import sys
print ('os', sys.platform)
print ('python', sys.version)
import pypdf
print ('pypdf', pypdf.__version__)
print (pypdf.__file__)

# create a blank page with a full-page link to cnn.com
writer = pypdf.PdfWriter()
writer.add_blank_page(width=500, height=500)
writer.add_uri(0, 'https://cnn.com', [0, 0, 499, 499])
print ('writing demo.pdf')
writer.write('demo.pdf')

# the demo.pdf has no link
# with the fix of the original post, click anywhere on demo.pdf to see the link work

**Comment by stefan6419846** [comment]
Do you want to submit a corresponding PR to fix this with an appropriate test?

**Comment by pmiller66** [comment]
If you know how to do it, please do so.  All of the info is in that thread.


Otherwise, I will figure out how to write a PR.

Thanks,
P

**Comment by stefan6419846** [comment]
We always appreciate new contributors, especially when there already is an apparently easy fix available. Your reports and PRs ensure that *pypdf* stays/becomes the tool you want to use for handling PDF files. So feel free to give it a try yourself by submitting a corresponding PR. (Being an active contributor, submitting a PR myself would work, but I always try to encourage new contributors to start familiarizing theirselves with the usual processes to ensure the FOSS ecosystem works in the long run.)

**Comment by pmiller66** [comment]
Got it. It’s a great product and I’ll do the PR.

—P

**Comment by pmiller66** [comment]
Ready to get to work.  Is "bug report" same as "PR"?   Couldn't find a link for PR.   Is the problem that I didn't respond to all of the prompts in my "bug report" above?

**Comment by stefan6419846** [comment]
No, issue and PR are two separate items. To create a PR, do the following:

* Go to https://github.com/py-pdf/pypdf and click "Fork" in the upper right corner.
* Go to the forked repository in your account.
* Make the corresponding changes there, usually into a dedicated branch.
* Commit and push your changes to your fork.
* Go to https://github.com/py-pdf/pypdf again - GitHub should show you a new message box and suggest you to merge your changes.
* Create a corresponding PR with the button inside this box.

**Comment by pmiller66** [comment]
Made it thru step 4 (perhaps).  On step five I couldn't find anything on 
the page about merging.  Sorry, just not a gihub guy.  Please help.

--P



Phil Miller
11 Coventry Close
Avondale, GA 30002
***@***.***
404.296.1221


------ Original Message ------
From "Stefan" ***@***.***>
To "py-pdf/pypdf" ***@***.***>
Cc "pmiller66" ***@***.***>; "Author" ***@***.***>
Date 1/12/2024 3:00:56 AM
Subject Re: [py-pdf/pypdf] pypdf 3.17.4 (and many previous versions) 
add_uri doesn't work: incorrect "/TYPE" (Issue #2403)

**Comment by stefan6419846** [comment]
From https://github.com/pmiller66/pypdf/tree/pmiller66-patch-1, clicking on "1 commit ahead of" leads to https://github.com/py-pdf/pypdf/compare/main...pmiller66:pypdf:pmiller66-patch-1 There you should have a green button saying "Create pull request".
