### ISSUE TITLE
Skip test if fpdf is not available

### ISSUE THREAD

**Issue by kitterma** [py-pdf/pypdf#2408]
Trying to run the tests in a constrained environment

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.10.0-27-amd64-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.4, crypt_provider=('pycryptodome', '3.20.0'), PIL=10.1.0
```

The fpdf module is not available in all environments.  It would be nice if the one test that uses is could be skipped if it's not available.  See the patch below.

Scott K

```
diff --git a/tests/test_writer.py b/tests/test_writer.py
index 281232c..22aa8b3 100644
--- a/tests/test_writer.py
+++ b/tests/test_writer.py
@@ -1973,6 +1973,7 @@ REFERENCES 76"""
         bookmarks.append(new_bookmark)


+pytest.importorskip("fpdf")
 def test_merging_many_temporary_files():
     def create_number_pdf(n) -> BytesIO:
         from fpdf import FPDF
```

**Comment by stefan6419846** [comment]
Thanks for the report. Do you want to submit a PR as you already have generated a patch anyway?

**Comment by kitterma** [comment]
Done.  https://github.com/py-pdf/pypdf/pull/2412

**Comment by kitterma** [comment]
This change did not get incorporated in the final version of #2412.

I understand that for open environments, fpdf is easily available and so this wouldn't be needed.  In Debian we test in a closed environment and fpdf is not available.  I'd rather just skip the test than package the module, which I think is a reasonable thing to do in restricted environments.  If you don't want the patch upstream, it's no problem to keep it as a Debian only patch.

**Comment by MartinThoma** [comment]
> In Debian we test in a closed environment

Oh, interesting! I think that is something I didn't/don't understand. Could you please explain that?
Why can you install pypdf and the other dependencies, but not fpdf?

**Comment by stefan6419846** [comment]
Probably because *fpdf* currently is not built by downstream and thus running these tests there does not make much sense from the packaging perspective.

**Comment by kitterma** [comment]
That's correct.  In Debian there is a requirement that it be possible to build any package in Debian using only packaged software, so we have packages for things like flit, pytest, and pil.  We have a [CI environment](https://ci.debian.net/packages/p/pypdf/) that runs tests for all packages that are configured to do so.  For these tests, they are also constrained to packages from the Debian archive.  We don't install software directly from external sources for package build, installation, or test.  For fpdf, it's not packaged and it is really not worth the work to do so in order to run one more test.

**Comment by MartinThoma** [comment]
Thanks for the explanation!

**Comment by kitterma** [comment]
Thanks,

Scott K
