### ISSUE TITLE
Font names cannot contain bracket characters even when encoded using #5D #5D.

### ISSUE THREAD

**Issue by spendres** [py-pdf/pypdf#2409]
I am merging a file that has embedded fonts named following the Adobe PDF 1.7 standard:

496 0 obj
<</BaseFont/FSGZQQ+Courier#20New#20#5BBold#5D/DescendantFonts[498 0 R]/Encoding/Identity-H/Subtype/Type0/ToUnicode 494 0 R/Type/Font>>
endobj

## Environment

```bash
$ python -m platform
# macOS-14.2.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
# pypdf==3.17.4, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=9.5.0
```
File to be merged:

[184.small.bracket-in-font-name.pdf](https://github.com/py-pdf/pypdf/files/13933330/184.small.bracket-in-font-name.pdf)
[184.small.spaces-for-brackets-in-font-name.pdf](https://github.com/py-pdf/pypdf/files/13933331/184.small.spaces-for-brackets-in-font-name.pdf)

## Code + PDF

This is a minimal, complete example that shows the issue:

```
from pypdf import PdfReader, PdfWriter
import sys
import os

work_around = r'./source-pdfs/184.small.spaces-for-brackets-in-font-name.pdf'
test_case = r'./source-pdfs/184.small.bracket-in-font-name.pdf'
print(os.path.exists(test_case))
test = test_case
reader = PdfReader(test)
number_of_pages = len(reader.pages)
print(number_of_pages)

writer = PdfWriter()
for page in reader.pages:
    writer.add_page(page)

outfile = r'184.out.pdf'
print(f"Saving as {outfile}")
with open(outfile, 'wb') as out:
    writer.write(out)
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

When reading and then writing the original file there is no output error or warning message, but the file contents contain errors for the header and bolded text. When I try to merge the file, I get a PdfReadError as follows:

PdfReadError("Invalid Elementary Object starting with b'B' @145186168: b'MY+Courier#20New#20[Bold]\\n/DescendantFonts [ 5081 0 R ]\\n/Encoding /Identity-H\\n/S'")
PdfReadError("Invalid Elementary Object starting with b'B' @145329169: b'WV+Courier#20New#20[Bold]\\n/DescendantFonts [ 5093 0 R ]\\n/Encoding /Identity-H\\n/S'")
PdfReadError("Invalid Elementary Object starting with b'I' @149420585: b'ND+Courier#20New#20[Italic]\\n/DescendantFonts [ 5247 0 R ]\\n/Encoding /Identity-H\\n'")

Notice that the #5B and #D are decoded to '[' and ']' respectively, while the #20 (space) is still encoded. 

## Workaround
So I hex-edited the pdf file to replace each #5B and each #5D with #20 and then all the fonts come through okay. See two example outputs below. The second one has all the fonts and no missing glyphs with only the eitis to the source pdf.

[184.out.bad.pdf](https://github.com/py-pdf/pypdf/files/13933353/184.out.bad.pdf)
[184.out.good.pdf](https://github.com/py-pdf/pypdf/files/13933354/184.out.good.pdf)

The font name should support brackets and some other special characters, as it does the (#20, ' ', space) character. So, this looks like a special case where the parser is treating the [Bold] as the start and end of an array object, rather than a string.

**Comment by pubpub-zz** [comment]
@spendres 
I've checked under the latest release (4.1.0) without issue
please upgrade and retry
I close this issue meanwhile. Feel free to ask to reopen it if required
