### ISSUE TITLE
extract_text produces hexadecimal output

### ISSUE THREAD

**Issue by staff0rd** [py-pdf/pypdf#2413]
The below code results in what looks like a bunch of hexadecimal. The first page of the pdf is displayed below, I note that I can copy/paste text normally from it (via Google Chrome).

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.4, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=none
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader
pdfreader = PdfReader('kia-stonic-owners-manual-my23.pdf')
# read text from pdf
raw_text = ''
for i, page in enumerate(pdfreader.pages):
    content = page.extract_text()
    if content:
        raw_text += content

# write text to file
with open('text.txt', 'w') as f:
    f.write(raw_text)
```

Share here the PDF file(s) that cause the issue:
[kia-stonic-owners-manual-my23.pdf](https://www.kia.com/content/dam/kwcms/au/en/files/owners-manual/stonic/kia-stonic-owners-manual-my23.pdf)

## First page of pdf
![image](https://github.com/py-pdf/pypdf/assets/6289998/0c96edd8-ae16-4a37-aba8-05c608a476b1)

## top of `text.txt`

![image](https://github.com/py-pdf/pypdf/assets/6289998/203be68a-b3c9-4261-9713-c952f07c5c90)

**Comment by IshmamR** [comment]
Did you find a workaround for this?

**Comment by pubpub-zz** [comment]
the fonts in the PDF have no tounicode mapping which is the standard way to get translation for text extraction. without such information pypdf uses the codes. Personally, I've not been able yet to identify a way to get a unicode from the font

**Comment by pubpub-zz** [comment]
Without feedbacks I close this issue as out of pypdf capabilities
