### ISSUE TITLE
Choice fields

### ISSUE THREAD

**Issue by orokusaki** [py-pdf/pypdf#2425]
## Environment

  - MacOS Ventura 13.6.4
  - Python 3.11
  - pypdf==4.0.0

## Problem

Given the following field (the street direction field near the top of [this PDF](https://github.com/py-pdf/pypdf/files/14031491/Form_Structure_v50.pdf)):

```python
{'/T': 'StreetDirection',
 '/FT': '/Ch',
 '/Ff': 71434240,
 '/Opt': [' ',
  ['N', 'N'],
  ['S', 'S'],
  ['E', 'E'],
  ['W', 'W'],
  ['NE', 'NE'],
  ['NW', 'NW'],
  ['SE', 'SE'],
  ['SW', 'SW']],
 '/_States_': [' ',
  ['N', 'N'],
  ['S', 'S'],
  ['E', 'E'],
  ['W', 'W'],
  ['NE', 'NE'],
  ['NW', 'NW'],
  ['SE', 'SE'],
  ['SW', 'SW']]}
```

Using `update_page_form_field_values` to set a value results in the previous choice being selected. For example:

```python
writer.update_page_form_field_values(page, {'StreetDirection': 'NW'}, auto_regenerate=False)
``` 

That resulted in the `NE` choice being selected. I was able to confirm this occured with any choice that was selected.

**Comment by stefan6419846** [comment]
Please provide some complete example code with all the necessary imports etc.

**Comment by jordiba90** [comment]
The issue on the form is that the field is too small to show the choice selected but it's selected indeed. Try it manually :)

**Comment by pubpub-zz** [comment]
@orokusaki 
as requested by @stefan6419846, Please provide full test code

**Comment by pubpub-zz** [comment]
@orokusaki 
I did the test and the returned value is correct
![image](https://github.com/py-pdf/pypdf/assets/4083478/2fa384a3-d579-4ec1-9a12-bf342e6ef6b5)
