### ISSUE TITLE
Trim extraneous spaces from PDF

### ISSUE THREAD

**Issue by Siddhartha90** [py-pdf/pypdf#2446]
## Explanation

I'm on the latest release 4.0.0.  The extract method used on a PDF resume ends up with something like:

```
Experience NOTION                                                                           ,  SENIOR ENGINEER, CORE PRODUCT       •text text text.  APPLE INC.                                                                     ,  TECH LEAD, APPLE                   AUG ’17 - OCT ’21 text text •Lead and subject matter
```

I believe it's just following the spatial spaces seen in the PDF, and the [documentation](https://pypdf.readthedocs.io/en/latest/user/extract-text.html) acknowledges whitespace trickiness:

>Whitespace characters: How many new lines should be extracted for 3cm of vertical whitespace? How many spaces should be extracted if there is 3cm of horizontal whitespace? When would you extract tabs and when spaces?

We can try do some manual trimming here for when we encounter more than one whitespace in succession, but wondering if PyPDF has plans on doing it out of the box. So given a PDF, get text back as you would naturally read it without preserving spaces/newlines etc.

## Code Example

How would your feature be used? (Remove this if it is not applicable.)

```python
    pdf_stream = BytesIO(document_bytes)
    pdf_reader = PdfReader(pdf_stream)
    document_text = str()

    for page in pdf_reader.pages:
        document_text += page.extract_text(trim_whitespace=True)

```

**Comment by stefan6419846** [comment]
Does the new layout mode change anything for you? Some discussions about general text extraction improvements have been done in #2038, where some post-processing like for handling ligatures have been proposed, which might be applicable for duplicate whitespace as well.

**Comment by pubpub-zz** [comment]
@Siddhartha90 
any update on @stefan6419846's comment ?

**Comment by pubpub-zz** [comment]
without any more information I consider the issue is closed. feel free to provide update if you want to reopen it
