### ISSUE TITLE
Create form fields,  javascript action handlers and Optional Content Groups (OCGs)?

### ISSUE THREAD

**Issue by stefaneidelloth** [py-pdf/pypdf#2461]
## Explanation

Does pypdf allow to create form fields (combo box) and attach java script to handle change actions? 

I would like to create an interactive pdf that allows to select from several charts/images to be displayed. 

According to some sources this should be possible in principle. See for example:

https://www.youtube.com/watch?v=Z5bdBeFwNCU

https://docs.reportlab.com/reportlab/userguide/ch4_pdffeatures/#choice-usage

https://acrobatusers.com/tutorials/print/create_use_layers/

https://github.com/pymupdf/PyMuPDF/issues/3180

**Comment by stefan6419846** [comment]
No, OCGs are not supported. See #92 and #1181.

**Comment by stefaneidelloth** [comment]
Thank you for clarification.
