### ISSUE TITLE
IndirectObject encountered in fonts /W width definitions in layout mode text extraction

### ISSUE THREAD

**Issue by johnwcchau** [py-pdf/pypdf#2465]
In some PDF document, page.extract_text(extraction_mode='layout') will raise "TypeError: 'IndirectObject' object is not iterable" 

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.19044-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.0.2, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.2.0
```

## Code + PDF
I cannot share PDF due to NDA, however this bug occurs because /DescendantFonts/W is indirectObject, resolving the IndirectObject fixed the problem
The code fix is adding the following lines at _text_extraction/_layout_mode/_font.py:60
```python
while isinstance(_w, IndirectObject):
     _w = _w.get_object()
```
## Traceback

This is the complete traceback I see:

```
File \venv\lib\site-packages\pypdf\_text_extraction\_layout_mode\_font.py:60, in Font.__post_init__(self)
     59 _w = d_font.get("/W", [])
---> 60 for idx, w_entry in enumerate(_w):
     61     if skip_count:
     62         skip_count -= 1

TypeError: 'IndirectObject' object is not iterable
```

**Comment by pubpub-zz** [comment]
PR #2464 may solve this issue can you try it

**Comment by pubpub-zz** [comment]
@johnwcchau 
any feedbacks?

**Comment by johnwcchau** [comment]
hi @pubpub-zz, yes I tried the #2464 and it did solved the problem, thank you!
