### ISSUE TITLE
Maximum open file limit reached with PdfMerger and path arguments

### ISSUE THREAD

**Issue by tareksander** [py-pdf/pypdf#2470]
After appending more than 1024 pdfs in a merger via the path, the open file limit for the process is reached, because the file objects never get closed. I worked around this by passing the file object myself and closing them after, but it's unexpected the library doesn't close the files again.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-6.1.0-18-amd64-x86_64-with-glibc2.36

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.1.0
```

**Comment by stefan6419846** [comment]
Thanks for the report. Please provide complete example code. Additionally, `PdfMerger` is deprecated in favor of `PdfWriter`, so please try again with the new way.

**Comment by tareksander** [comment]
Works correctly with PdfWriter
