### ISSUE TITLE
Documentation build is no longer automatically triggered on ReadTheDocs

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#2484]
Read the Docs currently seems to ship the docs for version 4.0.1 at the moment, although 4.0.2 has been released in the meantime.

I initially stumbled upon this due to the incomplete changelog at https://pypdf.readthedocs.io/en/latest/meta/CHANGELOG.html According to the build history, version 4.0.2 has never been triggered at all: https://readthedocs.org/projects/pypdf/builds/

**Comment by stefan6419846** [comment]
@MartinThoma Do you have an idea why the last release apparently did not trigger the docs build?

**Comment by Evan0000000000** [comment]
Related to https://github.com/py-pdf/py-pdf.github.io/issues/5 I'd guess

**Comment by stefan6419846** [comment]
I do not think so - the linked issue is about the GitHub Pages deployment, this issue about the RTD builds.

**Comment by Evan0000000000** [comment]
Oh yeah you're right of course, oops! Completely confused the two domains

**Comment by j-t-1** [comment]
Is it possible that as pypdf has grown it now times out the process? Are there any log files produced?

**Comment by MasterOdin** [comment]
From the https://readthedocs.org/projects/pypdf/builds/ link, it would seem that RTD was being regularly triggered on any commit to `main` as well as new tags until the 4.0.1 release (https://github.com/py-pdf/pypdf/commit/757932944f54ba661b89e0629ed3fc9d8345dbab), at which point no builds were triggered going forward.

I wonder if @MartinThoma had revoked something in RTD that made it no longer able to pick up new commits to the repo and build the appropriate `latest` or `stable` tags.

**Comment by MartinThoma** [comment]
I only noticed this ticket. Sorry for the delay. I'll have a look today.

**Comment by MartinThoma** [comment]
> I wonder if @MartinThoma had revoked something in RTD that made it no longer able to pick up new commits to the repo and build the appropriate latest or stable tags.

I didn't touch RTD for quite a while

**Comment by MartinThoma** [comment]
![image](https://github.com/py-pdf/pypdf/assets/1658117/fd9156b5-d231-484f-9aa7-4768b67cebba)

**Comment by MartinThoma** [comment]
I've re-connected / gave the permissions, but RTD still claims that it does not have access. I manually triggered the build now.

**Comment by MartinThoma** [comment]
https://blog.readthedocs.com/security-update-on-incoming-webhooks/ seems related

**Comment by MartinThoma** [comment]
Ok, I think things look good now. Hever, I still see the error message on RTD from above:

> Could not send GitHub build status report for "pypdf". Make sure you have the correct GitHub repository permissions and your [GitHub account](https://readthedocs.org/accounts/social/connections/) is connected to Read the Docs.

**Comment by MartinThoma** [comment]
![image](https://github.com/py-pdf/pypdf/assets/1658117/2012e944-0b9a-4003-8ba5-f3bbd0ba08a9)

Seems to work, though

**Comment by stefan6419846** [comment]
Thanks, it seems to be running again, although more often than before? In the past, we would only update the docs on a release/tag, now it seems like even PRs get a dedicated rendered page and each commit to the `main` branch triggers an up-to-date build. This should not really hurt, I just happened to stumble upon this when looking at my latest PR ;)

**Comment by pubpub-zz** [comment]
> Thanks, it seems to be running again, although more often than before? In the past, we would only update the docs on a release/tag, now it seems like even PRs get a dedicated rendered page and each commit to the `main` branch triggers an up-to-date build. This should not really hurt, I just happened to stumble upon this when looking at my latest PR ;)

I've seen the same. From an ecological point of view this is not so good. What about checking if the title starts with REL: to engage the process ?

**Comment by MartinThoma** [comment]
I was started the run a couple of times manually. Maybe you have seen that?

However, we did run it for every single PR as well since many months. The reason is that we can check changes in the docs before we merge it.
