### ISSUE TITLE
Support for ISO-8859-1 Encoding

### ISSUE THREAD

**Issue by sirexeclp** [py-pdf/pypdf#2490]
## Explanation

Currently PDFs with text encoded using ISO-8859-1 can not properly be decoded.
(Don't ask why people still use ISO-8859-1, but thats what I have to deal with.)
I could not find a way to specify a custom encoding to be used for text extraction.

It would be nice if users could specify an encoding.

## Code Example

```python
from pypdf import PdfReader, PdfWriter
reader = PdfReader("file.pdf", encoding="ISO-8859-1")
```

**Comment by stefan6419846** [comment]
Please provide a corresponding example file and the corresponding code which shows your issue.
