### ISSUE TITLE
Watermark overlay not showing in MacOS preview

### ISSUE THREAD

**Issue by wabiloo** [py-pdf/pypdf#2552]
I am trying to add footer/headers onto PDF pages exported by a tool (Notion in this case).
I have an A4 PDF with those overlays, and simply trying to merge it on top of every page of the source PDF.

The code runs, but the overlays are not showing in the MacOS preview. Nor are they showing in Acrobat Reader, and an error is raised instead

## Environment

```bash
$ python -m platform
macOS-14.3-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.1.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.2.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader, PdfWriter
from pypdf.annotations import FreeText

def add_watermark(source_pdf_path, watermark_pdf_path, output_pdf_path):
    watermark_pdf = PdfReader(watermark_pdf_path)
    watermark_page = watermark_pdf.pages[0]

    writer = PdfWriter(clone_from=source_pdf_path)

    # Iterate through source PDF and merge watermark onto each page
    for i, page in enumerate(writer.pages):
        page.merge_page(watermark_page, over=True)

    # add a page number
    writer.add_annotation(
        page_number=0,
        annotation=FreeText(
            text="Hello world",
            rect=(50, 550, 150, 650),
            font="Arial",
            font_size="20pt",
            font_color="00ff00",
            border_color="0000ff",
            background_color="cdcdcd",
        ),
    )

    writer.write(output_pdf_path)


if __name__ == "__main__":

    # Specify the paths to your documents and images here
    add_watermark(
        source_pdf_path="input_document.pdf",
        watermark_pdf_path="template_page.pdf",
        output_pdf_path="output_document.pdf",
    )

```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

[input_document.pdf](https://github.com/py-pdf/pypdf/files/14795109/input_document.pdf)
[template_page.pdf](https://github.com/py-pdf/pypdf/files/14795111/template_page.pdf)

**Comment by pubpub-zz** [comment]
@wabiloo 
retry with `page.merge_page(watermark_page, expand=True, over=True)`

if still not good please provide the output file

**Comment by stefan6419846** [comment]
Please be more specific and do not mix up different cases: In your example, you add both a watermark and an annotation. Are you able to pinpoint this to one of them?

**Comment by pubpub-zz** [comment]
> @wabiloo retry with `page.merge_page(watermark_page, expand=True, over=True)`
> 
> if still not good please provide the output file

any update ? else I will close this issue

**Comment by pubpub-zz** [comment]
without update I close this issue. fell free to provide update to reopen it.
