### ISSUE TITLE
PDF writing not filling the Dropdown

### ISSUE THREAD

**Issue by visstxg** [py-pdf/pypdf#2611]
I am working on updating the editable PDF value using pypdf 4.2.0.
I am able to fill all the text fields . Having trouble filling the dropdown field.

Any specific method to do it?

**Comment by stefan6419846** [comment]
Please provide the details the issue template requests from you, especially the code you used and a PDF for further analysis.

**Comment by visstxg** [comment]
The pdf write command I used is as follows.

import getdata
from pypdf import PdfReader,PdfWriter
import argparse
import os

reader = PdfReader(input_pdf)
    writer = PdfWriter()
    page = reader.pages[0]
    writer.append(reader)
    writer.update_page_form_field_values(
    writer.pages[0],
    {
    "State": 'MN'
}
    )


the result from dictionary = reader.get_fields()

'State': {'/T': 'State', '/FT': '/Ch', '/TU': 'State', '/Ff': 655360, '/V': 'AL', '/DV': ' ', '/Opt': [' ', ['AK', 'AK'], ['IL', 'IL'], ['IN', 'IN'], ['LA', 'LA'], ['MD', 'MD'], ['ME', 'ME'], ['MI', 'MI'], ['MN', 'MN'], ['NJ', 'NJ'], ['NY', 'NY'], ['VT', 'VT']], '/_States_': [' ', ['AK', 'AK'], ['IL', 'IL'], ['IN', 'IN'], ['LA', 'LA'], ['MD', 'MD'], ['ME', 'ME'], ['MI', 'MI'], ['MN', 'MN'], ['NJ', 'NJ'], ['NY', 'NY'], ['VT', 'VT']]}

Thanks

**Comment by pubpub-zz** [comment]
can you also share the PDF please

**Comment by visstxg** [comment]
https://railroads.dot.gov/sites/fra.dot.gov/files/2023-12/FRA%20F%206180.150.pdf

**Comment by pubpub-zz** [comment]
Writer is the modified document, with the fields updated. Reader is the original one : there is no link between
look in `writer.get_fields()` 😉

**Comment by visstxg** [comment]
> Writer is the modified document, with the fields updated. Reader is the original one : there is no link between look in `writer.get_fields()` 😉

I didn't get exactly what you meant. If you can provide little bit more explanation, it will be great. Thanks

**Comment by pubpub-zz** [comment]
the updated field is part of writer:
```writer.get_fields()["State"]```
returns:
{'/T': 'State', '/FT': '/Ch', '/TU': 'State', '/Ff': 655360, '/V': '**MN**', '/DV': ' ', '/Opt': [' ', ['AK', 'AK'], ['AL', 'AL'], ['AR', 'AR'], ['AZ', 'AZ'], ['CA', 'CA'], ['CO', 'CO'], ['CT', 'CT'], ['DC', 'DC'], ['DE', 'DE'], ['FL', 'FL'], ['GA', 'GA'], ['HI', 'HI'], ['IA', 'IA'], ['ID', 'ID'], ['IL', 'IL'], ['IN', 'IN'], ['KS', 'KS'], ['KY', 'KY'], ['LA', 'LA'], ['MA', 'MA'], ['MD', 'MD'], ['ME', 'ME'], ['MI', 'MI'], ['MN', 'MN'], ['MO', 'MO'], ['MS', 'MS'], ['MT', 'MT'], ['NC', 'NC'], ['ND', 'ND'], ['NE', 'NE'], ['NH', 'NH'], ['NJ', 'NJ'], ['NM', 'NM'], ['NV', 'NV'], ['NY', 'NY'], ['OH', 'OH'], ['OK', 'OK'], ['OR', 'OR'], ['PA', 'PA'], ['RI', 'RI'], ['SC', 'SC'], ['SD', 'SD'], ['TN', 'TN'], ['TX', 'TX'], ['UT', 'UT'], ['VA', 'VA'], ['VT', 'VT'], ['WA', 'WA'], ['WI', 'WI'], ['WV', 'WV'], ['WY', 'WY']], '/_States_': [' ', ['AK', 'AK'], ['AL', 'AL'], ['AR', 'AR'], ['AZ', 'AZ'], ['CA', 'CA'], ['CO', 'CO'], ['CT', 'CT'], ['DC', 'DC'], ['DE', 'DE'], ['FL', 'FL'], ['GA', 'GA'], ['HI', 'HI'], ['IA', 'IA'], ['ID', 'ID'], ['IL', 'IL'], ['IN', 'IN'], ['KS', 'KS'], ['KY', 'KY'], ['LA', 'LA'], ['MA', 'MA'], ['MD', 'MD'], ['ME', 'ME'], ['MI', 'MI'], ['MN', 'MN'], ['MO', 'MO'], ['MS', 'MS'], ['MT', 'MT'], ['NC', 'NC'], ['ND', 'ND'], ['NE', 'NE'], ['NH', 'NH'], ['NJ', 'NJ'], ['NM', 'NM'], ['NV', 'NV'], ['NY', 'NY'], ['OH', 'OH'], ['OK', 'OK'], ['OR', 'OR'], ['PA', 'PA'], ['RI', 'RI'], ['SC', 'SC'], ['SD', 'SD'], ['TN', 'TN'], ['TX', 'TX'], ['UT', 'UT'], ['VA', 'VA'], ['VT', 'VT'], ['WA', 'WA'], ['WI', 'WI'], ['WV', 'WV'], ['WY', 'WY']]}

**Comment by visstxg** [comment]
Yes writer.get_fields()["State"] returns with Data in '/V' but it is not showing in PDF. But I see data in Print Preview. Is there anything to do to get it showed on PDF rendering

**Comment by visstxg** [comment]
> Yes writer.get_fields()["State"] returns with Data in '/V' but it is not showing in PDF. But I see data in Print Preview. Is there anything to do to get it showed on PDF rendering

This issue only when open in Adobe Acrobat. Works fine in browsers

**Comment by pubpub-zz** [comment]
I've found the issue:
the PDF contains '/I' entries. This is the defintion from the PDF spec:
![image](https://github.com/py-pdf/pypdf/assets/4083478/abec1835-0fad-438e-8c41-290615313f56)

Acrobat is reading this entry first although:
a) the entry is not a multiple entry
b) '/I' is not in line with '/V' which should have priority.

so Acrobat is not compliant with spec. 
when reading properly the spec the "/V" looks sufficient to face all cases (/V should select in fields names which is the displayed text). "/I" can be deleted without further identified impact.

**Comment by pubpub-zz** [comment]
local copy for test:
[FRA F 6180.150.pdf](https://github.com/py-pdf/pypdf/files/15176321/FRA.F.6180.150.pdf)

**Comment by stefan6419846** [comment]
At least during my tests, pdf.js would not render this correctly, while Okular does.

**Comment by visstxg** [comment]
Thank you for working on this.

**Comment by visstxg** [comment]
Same PDF update has some other issues as well I encountered. The same PDF has 2 pages and second page has some fields repeating but in the reader.get_fields() returns the fields only one time. But the update_page_form_field_values is not updating the field from second page

**Comment by pubpub-zz** [comment]
I see only one field on second page (description)
There is no field within the cells "date of accident","RailRoad Accident...", "Highway ...","First Name","Middle Initial" these seems here only if you handwrite on a printed version

**Comment by visstxg** [comment]
Ok Got it. Thank you for the reply.

**Comment by visstxg** [comment]
I am very new to python and PyPDF  so asking. From above conversations I understand that you had a solution for the Acrobat issue with Dropdown. I see you created the PR and merged. But how can I get that changes

**Comment by stefan6419846** [comment]
You can either install the latest *main* version from GitHub or wait for us to publish the next release to allow you to install the package from PyPI (in the past, we usually did a release once a month).

**Comment by pubpub-zz** [comment]
To complete @stefan6419846 you can install the current dev version as shown in the documentation:
https://pypdf.readthedocs.io/en/stable/user/installation.html#development-version

**Comment by visstxg** [comment]
Thank you for the reply

**Comment by visstxg** [comment]
Hi, I am facing another issue in the same PDF. After updating and saving the PDF when the newly created PDF opens in that some of the field's font is too big and not showing up the whole data.

![image](https://github.com/py-pdf/pypdf/assets/160142838/113024ec-6822-4831-80f1-95729efca150)
![image](https://github.com/py-pdf/pypdf/assets/160142838/f863036c-299b-4bb0-93eb-a361fa7f63b2)


Any idea how can I solve it. Thanks

**Comment by pubpub-zz** [comment]
can you provide the filled document

**Comment by visstxg** [comment]
[202312532_2024-05-06.pdf](https://github.com/py-pdf/pypdf/files/15248682/202312532_2024-05-06.pdf)

Two issues facing in this filled document is the font size in some fields and I am encrypting the writer pdf with User access permission for PRINT only. With PRINT only UAP the fields are READ ONLY, but there is a Signature field which looks like editable but not able to click or add signature in the file. Thank you

**Comment by pubpub-zz** [comment]
Setting PRINT only, you have unset the permission "can fill in form fields". Therefore you can not edit any fields. The signature field is not filled however Acrobat seems to set the finger cursor on it (to possibly access some verification popups???)  but the field is definitely empty
font size will be addressed the other issue you've raised

**Comment by visstxg** [comment]
Thank you for the reply. I may need to make each field read only to excluding signature to solve this right
