### ISSUE TITLE
Blank pdf after apply transfer_rotation_to_content to each page

### ISSUE THREAD

**Issue by dfaustryjak** [py-pdf/pypdf#2624]
Hi

I want to normalise pdf files according to Rotate param that exist in file to transform it. Below I write method that remove content from pdf file at the end 😢 . I need to use it because at the end I need to have read files for applying watermarks.. 

```python
def transform_doc_rotation(document_file_path):

    with open(document_file_path, "rb") as document_file_path_file:
        input_doc_pdf = PdfReader(document_file_path_file)
        output = PdfWriter()
        
        for p in input_doc_pdf.pages:
            p.transfer_rotation_to_content()
            output.add_page(p)
           

        with open("./transformed.pdf", "wb") as transformed_file:
            output.write(transformed_file)
```
[dummy_rotated.pdf](https://github.com/py-pdf/pypdf/files/15218993/dummy_rotated.pdf)

**Comment by dfaustryjak** [comment]
@pubpub-zz 

There was an error opening this document. This file cannot be opened because it has no pages....

**Comment by pubpub-zz** [comment]
I'm on dev version. use 
`output = PdfWriter(clone_from="dummy_rotated.pdf")`

**Comment by dfaustryjak** [comment]
<img width="551" alt="Screenshot 2024-05-06 at 12 24 41" src="https://github.com/py-pdf/pypdf/assets/11707706/4700ce08-58cd-407b-83d9-64ad8d906d5b">
<img width="653" alt="Screenshot 2024-05-06 at 12 24 51" src="https://github.com/py-pdf/pypdf/assets/11707706/01ac8876-1e24-4998-bc1d-74edf349a5fc">

**Comment by stefan6419846** [comment]
Something seems to be wrong with your code, it should be https://github.com/py-pdf/pypdf/blob/2ac88e635c8e16478fc11bde02411cfa573a7807/pypdf/_page.py#L666-L699

**Comment by dfaustryjak** [comment]
Yes, you are right we can close it :)

**Comment by pubpub-zz** [comment]
@stefan6419846 is there a bug to be fixed ?

**Comment by stefan6419846** [comment]
@pubpub-zz No, we ship valid code (otherwise CI would not pass, just validated with the latest binary wheel). It seems like there has been tampered with the library code in this case which led to the exception in https://github.com/py-pdf/pypdf/issues/2624#issuecomment-2095654995.
