### ISSUE TITLE
Removing Form Fields after filling them

### ISSUE THREAD

**Issue by Usouf** [py-pdf/pypdf#2639]
After I fill in the form fields, the form fields remain visible and on top of the text filled in causing the filled in text to be hidden under it until you hover.

I tried to remove the annotations, but couldn't achieve that.

What other options do you have to fix this issue?

## Environment

Windows 11

```bash
$ python -m platform
Windows-11-10.0.22631-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.2.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.2.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
        import requests
        from io import BytesIO
        from django.core.files import File
        from django.forms.models import model_to_dict
        from django.conf.urls.static import static

        from pypdf import PdfReader, PdfWriter
        import pypdf

        ctx = model_to_dict(application)

        response = requests.get("http://localhost:8000/static/document/form.pdf")
        if not response.ok:
            log.error("couldn't get form")

        stream = BytesIO(response.content)
        reader = PdfReader(stream)
        print(reader.get_form_text_fields())

        writer = PdfWriter()

        writer.append(reader)

        for page in writer.pages:
            writer.update_page_form_field_values(page, ctx, auto_regenerate=False)
            annotations = page.get('/Annots')
            if annotations:
                new_annotations = [annot for annot in annotations if '/FT' not in annot]
                page[pypdf.pdf.Definition('Annots')] = new_annotations

        application.arabic_document.save("Some file.pdf", File(writer.write(BytesIO())[1]))
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete traceback I see:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\umansoor\Developer\tarasul\tarasul_admin\models.py", line 220, in _fill_form   
    new_annotations = [annot for annot in annotations if '/FT' not in annot]
                                                
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\umansoor\Developer\tarasul\venv\Lib\site-packages\pypdf\generic\_base.py", line 309, in __getitem__
    return self._get_object_with_check()[key]  # type: ignore
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^   
  File "C:\Users\umansoor\Developer\tarasul\venv\Lib\site-packages\pypdf\generic\_data_structures.py", line 409, in __getitem__
    return dict.__getitem__(self, key).get_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 0
```

**Comment by stefan6419846** [comment]
Please provide some standalone code for reproduction as well as a corresponding PDF file.

**Comment by Usouf** [comment]
[form.pdf](https://github.com/py-pdf/pypdf/files/15294612/form.pdf)

The mentioned issue happens when saving to a Django model using `application.arabic_document.save("Some file.pdf", File(writer.write(BytesIO())[1]))` while normally it doesn't make that issue but the field stays editable.

Could it be due to using BytesIO as a stream or something?

I noticed another thing when I use Arabic text, the text is reversed.

![Screenshot 2024-05-14 093611](https://github.com/py-pdf/pypdf/assets/25987391/f38c3381-aa3b-42bc-9913-93c5d23d45d5)

**Comment by stefan6419846** [comment]
I cannot really reproduce your issue, although I am not completely sure what you are trying to achieve either.

Let's take the simplified version of your code which does not depend on Django:

```python3
from io import BytesIO

from pypdf import PdfWriter
import pypdf


writer = PdfWriter(clone_from="form.pdf")
print(writer.get_form_text_fields())

ctx = {"full_name": "Test text"}

for page in writer.pages:
    writer.update_page_form_field_values(page, ctx, auto_regenerate=False)
    annotations = page.get('/Annots')
    # if annotations:
        # new_annotations = [annot for annot in annotations if '/FT' not in annot]
        # page[pypdf.pdf.Definition('Annots')] = new_annotations

output = writer.write(BytesIO())[1]
with open("out.pdf", mode="wb") as fd:
    fd.write(output.getvalue())
```

I had to comment the annotations handling as the list comprehension will not work (anymore) with the current *pypdf* version and `pypdf.pdf.Definition` is something which is not declared by us.

If you run the above code, you will get a filled `full_name` field inside the output file.

**Comment by Usouf** [comment]
UPDATE: 
Turns out the issue of the reversed text is from Django not the library

**Comment by Usouf** [comment]
UPDATE:
The reversed text issue was originally stemming from the browsers (Chrome, Edge), opening the same file in firefox has no reverse issue.

The problem of the field being on top of the text persists:

![Screenshot 2024-05-14 154121](https://github.com/py-pdf/pypdf/assets/25987391/6f1e34d5-e6fe-4fa1-bf2b-122a7993b79d)

**Comment by stefan6419846** [comment]
See #2627 for the read-only part.

**Comment by pubpub-zz** [comment]
@Usouf 
You are filling forms with arabic. I would recommend to use auto_regenerate=True,
You can also set the flags to set the annotations ins Readonly

Can you check with these and provide feed back ?

**Comment by Usouf** [comment]
> @Usouf You are filling forms with arabic. I would recommend to use auto_regenerate=True, You can also set the flags to set the annotations ins Readonly
> 
> Can you check with these and provide feed back ?

This helped in fixing the Arabic issue. Thanks.

I'm still unable to mark the fields as readonly.

I tried the solution the thread suggested by @stefan6419846 but still couldn't resolve it.

**Comment by pubpub-zz** [comment]
@Usouf can you please provide the input, output file and code for review

**Comment by Usouf** [comment]
it worked finally, I just had to adjust the code to the following:

```Python
READ_ONLY_FLAG = 0x01
        
for k,v in writer.get_fields().items():
        o = v.indirect_reference.get_object()
        if o["/FT"] == "/Tx":
            current_flags = o.get("/Ff", 0)
            o[pypdf.generic.NameObject("/Ff")] = pypdf.generic.NumberObject(current_flags | READ_ONLY_FLAG)
```

my only problem is that not all browsers support arabic fields, which causes texts to be reversed for some users.

I will try to print the pdf and save it, which will convert the pages to images.

Hope that works.
