### ISSUE TITLE
Cloning pages no longer possible in 4.0

### ISSUE THREAD

**Issue by raphaelm** [py-pdf/pypdf#2642]
We often use PyPDF to "add a letterhead", i.e. we have a multi-page PDF with content (say, an invoice) and a one-page letterhead PDF we want to use as a background. We use `merge_page` for this like in the example below and `copy.deepcopy` to avoid references. With pypdf 3.x this works fine, with 4.0 or 4.2 it does not, it will render the last page multiple times.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-6.8.2-arch2-1-x86_64-with-glibc2.39

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.2.0, crypt_provider=('cryptography', '42.0.2'), PIL=10.3.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import copy

from pypdf import PdfReader, PdfWriter

bg_pdf = PdfReader("/tmp/background.pdf", strict=False)
fg_pdf = PdfReader("/tmp/foreground.pdf")
output = PdfWriter()

for page in fg_pdf.pages:
    bg_page = copy.deepcopy(bg_pdf.pages[0])
    bg_page.merge_page(page)
    output.add_page(bg_page)

output.write("/tmp/output.pdf")
```

[foreground.pdf](https://github.com/py-pdf/pypdf/files/15305906/foreground.pdf)
[background.pdf](https://github.com/py-pdf/pypdf/files/15305907/background.pdf)
[output.pdf](https://github.com/py-pdf/pypdf/files/15305911/output.pdf)

**Comment by stefan6419846** [comment]
Thanks for the report. Have you verified that version 3.17.4 does work in this case? This might help to pinpoint the corresponding change, while https://github.com/py-pdf/pypdf/compare/3.17.4...4.0.0 does not really seem to indicate a change which would lead to this.

**Comment by raphaelm** [comment]
Yes, I have verified (again) that 3.17.4 works fine. However, I was wrong about 4.0.0, the error appears to be introduced between 4.0.2 and 4.1.0.

**Comment by raphaelm** [comment]
By manually installing versions from git, I was able to narrow it down to 03af2c2b61df45a3ab11fd5e6895a98badbe9346

**Comment by raphaelm** [comment]
…which does override `__deepcopy__` with something other than deep copying, which is… not ideal?

**Comment by stefan6419846** [comment]
Let's wait for @pubpub-zz who implemented this change.

**Comment by pubpub-zz** [comment]
I see no reason to use apply some deep_copy:
This is the code  I've used:
```
import pypdf
r=pypdf.PdfReader("background.pdf")
w=pypdf.PdfWriter("foreground.pdf")
for p in w.pages:
    p.merge_page(r.pages[0])
```
this is the result
[tt.pdf](https://github.com/py-pdf/pypdf/files/15311751/tt.pdf)

**Comment by pubpub-zz** [comment]
@raphaelm 
Is it OK to close it ?

**Comment by raphaelm** [comment]
I'm pretty sure we added the copy statement in the first place for some reason to prevent another issue, but it was years ago and I don't remember the exact scenario. I'll run a few tests in the next days and will report back!

**Comment by pubpub-zz** [comment]
remember to have a look at 
https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html#reset-translation
https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html#advanced-cloning

Deep copy should not be required
