### ISSUE TITLE
Support for Destination

### ISSUE THREAD

**Issue by dawillcox** [py-pdf/pypdf#2647]
## Explanation

Explain briefly what you want to achieve.

## Code Example

How would your feature be used? (Remove this if it is not applicable.)

```python
from pypdf import PdfReader, PdfWriter

...  # your new feature in action!
```

**Comment by stefan6419846** [comment]
Closing due missing details.

**Comment by dawillcox** [comment]
Sorry, apparently this submitted before I was done with the description. I'll recollect my thoughts and then retry.
