### ISSUE TITLE
Support for removing a single annotation

### ISSUE THREAD

**Issue by ag-gaphp** [py-pdf/pypdf#2664]
## Explanation

Currently, pypdf only has a built in method to remove _ALL_ annotations of a provided type, or all annotations of all types. In my use case, it would be nice to have a way to remove only a single annotation.

The code example below works well to remove the annotation from the `/Annots` list, but there is still a reference to the field object in the `/Fields` list and I am not familiar enough with the toolkit to know how to remove it from that list as well. I have found through trial and error over the last couple weeks that PDF viewers and eSign platforms are not uniform in how they parse these fields. Some look at the `/Annots` list and ignore everything else, while others looks at the `/Fields` list and ignore everything else. Due to this inconsistency in available readers, the annotation would need to be removed from both lists to be considered completely 'deleted' from the PDF.

## Code Example

This code came from an answer in [this discussion](https://github.com/py-pdf/pypdf/discussions/2662) that works to remove a single widget from the `/Annots` list, but I am not familiar enough with this toolkit yet to provide a more complete example in the context of the PdfWriter class.

I would expect it to be called using something like: `PdfWriter.remove_annotation(annotation)`

```python
import pypdf
w = pypdf.PdfWriter(clone_from="input.pdf")
to_be_deleted = []
for i, a in enumerate(w.pages[0]["/Annots"]):
   a=a.get_object()
   if #### criteria on a ####:
       to_be_deleted.append(i)
for i in to_be_deleted[::-1]:
   del w.pages[0]["/Annots"][i]

w.write("output.pdf")
```

**Comment by pubpub-zz** [comment]
In order to remove `annotation` you just have to do:
```
del writer.pages[page_number]["/Annots"][writer.pages[page_number]["/Annots"].index(annotation.indirect_reference)]
```
This quite standard python approach
I personally see very little interest to add this function, perhaps just adding some documentation

**Comment by stefan6419846** [comment]
I do not think that this should be part of the public API either as it is quite specific. Removing all objects of one type usually tends to make more sense.

**Comment by ag-gaphp** [comment]
I'm not sure why deleting individual annotations is not a desired functionality. Seems like a generic utility with a lot of use cases.

In my particular use case, LibreOffice does not allow you to add signature fields to forms. So, in order to prepare them for signing via Acrobat or an eSign platform, I need to make placeholders in the document, run them through a script to store their rect, delete, and then use a toolkit called pyHanko to add proper signature fields. All without disturbing the rest of the widgets.

Not my decision, close the ticket if you don't want it open for adding documentation.

@pubpub-zz unfortunately, this bit of code only removes the annotation from the `/Annots` list and not the central list in the PDF. It did lead me in the right direction for that specific issue I'm encountering, where the widget only gets removed from the page's `/Annots` list, but not the document's `/AcroForm/Fields` list.

This additional removal is what I needed for the readers/importers that ignore page `/Annots` list and only look through the document root:
`writer._root_object['/AcroForm']['/Fields'].remove(annotation.indirect_reference)`
