### ISSUE TITLE
Implement '__enter__' in PdfReader

### ISSUE THREAD

**Issue by KevFlo** [py-pdf/pypdf#2665]
## Explanation

Make PdfReader more pythonic by using the 'with' 'as' context.

## Code Example

```
from PyPDF2 import PdfReader
total_text = ""

pdf_file_path = "example/path" # Replace with your PDF file path
with PdfReader(pdf_file_path) as reader:
    total_text = '\n\n'.join([page.extract_text() for page in reader.pages])
```

## Error trace back

Traceback (most recent call last):
  File "pdfotxt.py", line 21, in <module>
    with PdfReader(pdf_file_path) as reader:
AttributeError: __enter__

**Comment by pubpub-zz** [comment]
PyPDF2 is obsolete. Feature should be available in pypdf

**Comment by KevFlo** [comment]
Just installed and re-ran code with pypdf,
I get the same error as with PyPDF2. 

```
Traceback (most recent call last):
  File "pdfotxt.py", line 22, in <module>
    with PdfReader(pdf_file_path) as reader:
AttributeError: __enter__ 

```

**Comment by pubpub-zz** [comment]
Can you propose a PR?
