### ISSUE TITLE
/Rotate not respected when merging pages

### ISSUE THREAD

**Issue by wiffbi** [py-pdf/pypdf#2667]
We use PyPDF to merge a foreground PDF with a background PDF. When either one of those PDFs uses `/Rotate` to rotate its page contents, the other PDF is rotated wrongly when using `PageObject.merge_page`. In the example the foreground is set as A4.landscape whereas the background-PDF is set A4.portrait, but uses `/Rotate 90` to make it landscape as well. When merged, the background-PDF is merged as A4.portrait without rotation.

I think, if the page to be merged has a `/Rotate` then `PageObject.merge_page` should apply a `Transformation` with `rotate` and `translate` as well as fixes to mediabox/cropbox to `page2` before merging it.

Thank you very much!

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-6.8.2-arch2-1-x86_64-with-glibc2.39

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.2.0, crypt_provider=('cryptography', '42.0.2'), PIL=10.3.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader, PdfWriter

bg_pdf = PdfReader("/tmp/background.pdf")
fg_pdf = PdfReader("/tmp/foreground.pdf")
output = PdfWriter()

for page in fg_pdf.pages:
    page.merge_page(bg_pdf.pages[0])
    output.add_page(page)

output.write("/tmp/output.pdf")
```

[foreground.pdf](https://github.com/py-pdf/pypdf/files/15402506/foreground.pdf)
[background.pdf](https://github.com/py-pdf/pypdf/files/15402505/background.pdf)
[output.pdf](https://github.com/py-pdf/pypdf/files/15402504/output.pdf)

**Comment by stefan6419846** [comment]
Did you try the solution from our docs? https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html#merging-rotated-pages

**Comment by wiffbi** [comment]
Wow, I did not see that! Thank you very much, makes it way easier!
