### ISSUE TITLE
PyPDF some fields not showing in generated PDF

### ISSUE THREAD

**Issue by thusharagokulnath** [py-pdf/pypdf#2724]
Hi, 

Can someone please help with this

I am generating few PDF using py PDF pypdf==4.2.0
This is the input PDF
[FRA F 6180.55.pdf](https://github.com/user-attachments/files/15976401/FRA.F.6180.55.pdf)

The marked fields on the image are not filling , but when I get the getfields() of writer and check, there is value(\V) for the fields
![image](https://github.com/py-pdf/pypdf/assets/47005180/9b815328-2de6-4b94-98ee-96c4ba60c4d1)

Few example getfields data:

```
'YARDMILE': {'/T': 'YARDMILE', '/FT': '/Tx', '/TU': 'Yard Switching Train Miles', '/V': '28800', '/AA': {'/F': IndirectObject(57, 0, 2677080479392), '/K': IndirectObject(58, 0, 2677080479392)}},
'WORKERHR': {'/T': 'WORKERHR', '/FT': '/Tx', '/TU': 'Railroad Worker Hours', '/V': '811371', '/AA': {'/F': IndirectObject(65, 0, 2677080479392), '/K': IndirectObject(66, 0, 2677080479392)}},
```

Below is the generated PDF
[FRA F 6180.55_2018-05-01_2018-05-31_2024-06-25_14-31-00.pdf](https://github.com/user-attachments/files/15976506/FRA.F.6180.55_2018-05-01_2018-05-31_2024-06-25_14-31-00.pdf)

TIA

**Comment by thusharagokulnath** [comment]
One thing I found about it is there is data on the field. It display data when I click on the field , it disappear just show the blue editable field when I move the cursor. 

For me I am generating the PDF as readonly in above examples, there I cannot see the data at all

**Comment by pubpub-zz** [comment]
Your form is in readonly. Can you remove this restriction for analysis

**Comment by thusharagokulnath** [comment]
Sure. Please see the comment also

**Comment by pubpub-zz** [comment]
I've seen it but I would like to see how acrobat modifies the fields. In pdf.js the fields are visibles

**Comment by calixteman** [comment]
With pdf.js the values of the fields are correct because we use their `V` entry. But if you try to print the pdf then the indicated fields are empty, so it's likely an issue in the appearance stream of those annotations (Acrobat and Chrome use the AS).

**Comment by thusharagokulnath** [comment]
Below is the editable pdf generated
[FRA F 6180.55_2022-09-01_2022-09-30_2024-06-25_17-35-06.pdf](https://github.com/user-attachments/files/15979615/FRA.F.6180.55_2022-09-01_2022-09-30_2024-06-25_17-35-06.pdf)

Looking forward for a solution asap. It is a blocker for my project deployment

Thanks

**Comment by pubpub-zz** [comment]
I've understood : the boxes ("/Rect") are upside down Rect[1] is greater than Rect[3]. Just checking but a fix/patch should be available soon

**Comment by thusharagokulnath** [comment]
Thank you

**Comment by pubpub-zz** [comment]
can you try to modify _writer.py line 879:
```
        for line_number, line in enumerate(txt.replace("\n", "\r").split("\r")):
            if line in sel:
                # may be improved but cannot find how to get fill working => replaced with lined box
                ap_stream += (
                    f"1 {y_offset - (line_number * abs(font_height) * 1.4) - 1} {abs(rct.width) - 2} {abs(font_height) + 2} re\n" #<------------
                    f"0.5 0.5 0.5 rg s\n{da}\n"
                ).encode()
```

**Comment by thusharagokulnath** [comment]
what need to be modified? I am new to python, just trying understand

**Comment by pubpub-zz** [comment]
start the python idle, 
press alt+M
open "pypdf._writer.py"
press alt+G
goto line 879
it should starts with :
`         f"1 {y_offset - `
replace it with
`                    f"1 {y_offset - (line_number * abs(font_height) * 1.4) - 1} {abs(rct.width) - 2} {abs(font_height) + 2} re\n" #<---------`
save file, rerun your script. check result

**Comment by thusharagokulnath** [comment]
Thank you.
This line of code is in line 843, so got confused.
Even though I tried changing it and rerun the script. but not worked. still the same

**Comment by pubpub-zz** [comment]
at line 839, you can find:
`ap_stream = f"q\n`(...)
replace it with
```
        ap_stream = f"q\n/Tx BMC \nq\n1 1 { abs(rct.width) - 1} {abs(rct.height) - 1} re\nW\nBT\n{da}\n".encode()
```

**Comment by thusharagokulnath** [comment]
Tried it. Still no luck

Thanks

**Comment by pubpub-zz** [comment]
can you provide some test code please

**Comment by thusharagokulnath** [comment]
import json
import getdata
from ReadConfig import read_config
from pypdf import PdfReader,PdfWriter
import argparse
import os
from datetime import datetime
from pypdf.constants import UserAccessPermissions as UAP


todayDate = datetime.today().strftime("%Y-%m-%d_%H-%M-%S")

config = read_config()

input_pdf  = f""+config['FilePaths']['input_pdf']+"FRA F 6180.55.pdf"

def fill_pdf():
    try:  
        merger = PdfWriter()  
        merger.encrypt(user_password="",owner_password="",permissions_flag=UAP.PRINT) 
        reader = PdfReader(input_pdf)
        writer = PdfWriter(clone_from=reader)
        writer.set_need_appearances_writer(True)  
        writer.encrypt(user_password="",owner_password="",permissions_flag=UAP.PRINT)        
        
        for page in writer.pages:   
            writer.update_page_form_field_values(
                page,
                {
                "RailroadName": "A" ,
                "RailroadCode": "B" ,
                "ReportMonthYear": "06/2024" ,
                "County": "MX" ,
                "ReportingOfficerName": "C" ,
                "ReportingOfficerTitle": "D" ,
                "ReportingOfficerAddress": "E" ,
                "ReportingOfficerTelephoneNumber": "F" ,
                "Date1": "" ,
                "Date2": "" ,
                "FreightTrainMiles": "2323" ,
                "PassengerMilesOperated": "34324"   ,
                "YARDMILE": "23324" ,
                "OtherTrainMiles": "45435" ,
                "WORKERHR": "5346" ,
                "PassengerTrainMiles": "65746",
                "PassengersTransported": "4653" ,
                "FatalEmployee": "3" ,
                "FatalEmployeeNotOnDuty": "1" ,
                "FatalPassengers": "4" ,
                "FatalNontrespassers": "5" ,
                "FatalTrespassers": "6" ,
                "FatalContractor": "8" ,
                "FatalContractorOher": "34" ,
                "FatalVolunteer": "64" ,
                "FatalVolunteerOther": "3" ,
                "FatalNonTrespassersOffRailroad": "34" ,
                "FatalGrandTotal": "35" ,
                "NonFatalEmployee": "3" ,
                "NonFatalEmployeeNotOnDuty": "5" ,
                "NonFatalPassenger": "5" ,
                "NonFatalNontrespassers": "34" ,
                "NonFatalTrespassers": "3" ,
                "NonFatalVolunteerOther": "43" ,
                "NonFatalContractor": "2" ,
                "NonFatalContractorOther": "64" ,
                "NonFatalVolunteer": "2" ,
                "NonFatalNonTrespassersOffRailroad": "23" ,
                "NonFatalGrandTotal": "23" ,
                "F618054": "2" ,
                "F618055A": "3",
                "F618056": "3",
                "F618057": "4" ,
                "F618081": "5" ,
                "Description1": "D" ,
                "Description2": "E" ,
                "Description3": "F" ,
                "Description4": "G" ,
                "Description5": "H",
                "State": "NJ"
                },        
                auto_regenerate = False
            )
                
            merger.append(writer)
        output_pdf= f""+config['FilePaths']['output_pdf']+"FRA F 6180.55_1.pdf"
        with open(output_pdf  , "wb") as output_stream:
            merger.write(output_stream) 
    except Exception as e:
        print(e)

fill_pdf()

**Comment by thusharagokulnath** [comment]
Any update?

**Comment by pubpub-zz** [comment]
let me have dinner!😫

**Comment by thusharagokulnath** [comment]
Sorry for pushing . It is a blocker for my project.

**Comment by pubpub-zz** [comment]
We are only volunteers spending spare time for the benefit of the community....
a few more abs shall be added:
line 773:
````
                font_height = abs(rct.height) - 2
```
line 776:
```
        y_offset = abs(rct.height) - 1 - font_height
```

**Comment by pubpub-zz** [comment]
any update ?

**Comment by thusharagokulnath** [comment]
No luck. Still same

**Comment by pubpub-zz** [comment]
working for me 🤔
can you send me your output file ?

**Comment by thusharagokulnath** [comment]
[FRA F 6180.55_1.pdf](https://github.com/user-attachments/files/16020477/FRA.F.6180.55_1.pdf)

**Comment by pubpub-zz** [comment]
I think it should be good now : I missed the /BBox field
for line 745
```
        rct = RectangleObject((0, 0, abs(_rct[2] - _rct[0]), abs(_rct[3] - _rct[1])))
```

**Comment by thusharagokulnath** [comment]
Wow! Perfect. That worked. Thank you so much

**Comment by pubpub-zz** [comment]
This should be part of next release
