### ISSUE TITLE
Broken docs link on PyPI

### ISSUE THREAD

**Issue by bionicles** [py-pdf/pypdf#2748]
I clicked the docs link on pypi and it went to an error page

## Environment

google chrome 

## Code + PDF

This is a minimal, complete example that shows the issue:

https://pypi.org/project/PyPDF2/

the links point to here:
https://pypdf2.readthedocs.io/en/stable/

the index page works:
https://pypdf2.readthedocs.io/en/3.x/

**Comment by stefan6419846** [comment]
PyPDF2 is not maintained any more, thus I tend to close this without further analysis/fixing.

**Comment by bionicles** [comment]
Ok, what if we redirect to the new project? Save some future person some confusion and clicking

**Comment by stefan6419846** [comment]
The PyPI page for PyPDF2 already has a large hint at the top, the (working) docs as well. Replacing the actual link requires a new release which we are not planning to do due to discontinuing maintenance.
