### ISSUE TITLE
Filled Choice Fields Not Rendered Correctly By Adobe Acrobat

### ISSUE THREAD

**Issue by jacobmiller22** [py-pdf/pypdf#2749]
When reading a form with Adobe Acrobat that previously had a `Choice` (`Drop-down list` in Acrobat) field populated with `pypdf` in the manner specified in the documentation, the default value is always rendered. Behavior does not occur with MacOS Preview.

I did see #2747 , #2611, and #2614, but I wanted to provide a full example for reproducing.

I have also tried this on version `4.3.0` and received the same behavior.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-14.5-arm64-arm-64bit

^ Have also experienced this on AWS lambda with amd64 chip and a 2019 MBP with Intel Chip

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.2.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=none
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import pypdf

reader = pypdf.PdfReader("./single-dropdown-field.pdf")

writer = pypdf.PdfWriter()
pages = reader.pages[0] # Unused var, Follows the documentation
fields = reader.get_fields() # Unused var, Follows the documentation

writer.append(reader)

print("Fields before update: ", writer.get_fields())
## Formatted for readability
# Fields before update:  
# {
#     'TEST_DROPDOWN': {
#         '/T': 'TEST_DROPDOWN', 
#         '/FT': '/Ch', 
#         '/Ff': 131072, 
#         '/V': 'Unselected', # Value is currently the default value
#         '/DV': 'Unselected', 
#         '/Opt': ['Unselected', 'Item 1', 'Item 2', 'Item 3'], 
#         '/_States_': ['Unselected', 'Item 1', 'Item 2', 'Item 3']
#     }
# }
##

data = {"TEST_DROPDOWN": "Item 2"}

writer.update_page_form_field_values(
    None,
    data,
    auto_regenerate=True, # Same Behavior with both True and False
)

print("Fields after update: ", writer.get_fields())
## Formatted for readability
# Fields after update:  
# {
#     'TEST_DROPDOWN': {
#         '/T': 'TEST_DROPDOWN', 
#         '/FT': '/Ch', 
#         '/Ff': 131072, 
#         '/V': 'Item 2', # Value is correctly assigned my value
#         '/DV': 'Unselected', 
#         '/Opt': ['Unselected', 'Item 1', 'Item 2', 'Item 3'], 
#         '/_States_': ['Unselected', 'Item 1', 'Item 2', 'Item 3']
#     }
# }
##

writer.write("result-single-dropdown-field.pdf")
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

The below PDFs shared may be used in tests if desired. They were created for the sole purpose of creating a simple PDF to reproduce this issue.

[single-dropdown-field.pdf](https://github.com/user-attachments/files/16179759/single-dropdown-field.pdf)

^ Created using Adobe Acrobat, contains a single "Drop-down list" Field with the name `TEST_DROPDOWN`

[result-single-dropdown-field.pdf](https://github.com/user-attachments/files/16179763/result-single-dropdown-field.pdf)

^ Result from the script

## Snapshots of form in Adobe Acrobat

Posted in comment below

## Additional Details

After populating the fields, I can see the `/V` field is correctly set to the value I want, MacOS preview also renders the PDF correctly. Unfortunately, I need Acrobat compatibility before anything else.

**Comment by jacobmiller22** [comment]
# Snapshots from Adobe Acrobat

Image of PDF before populating. Default value is `Unselected`

<img width="939" alt="Screenshot 2024-07-11 at 11 28 21 AM" src="https://github.com/py-pdf/pypdf/assets/51894836/e2b4108e-ff9a-41bc-934f-c127d3d19d2d">

Image of PDF in the `Prepare a form` menu

<img width="1666" alt="Screenshot 2024-07-11 at 11 29 00 AM" src="https://github.com/py-pdf/pypdf/assets/51894836/55169e16-c1ae-45fa-b17e-05e078171844">

**Comment by jacobmiller22** [comment]
# Snapshots from Adobe Acrobat

Images of Fields properties menu:

<img width="1067" alt="Screenshot 2024-07-11 at 11 29 52 AM" src="https://github.com/py-pdf/pypdf/assets/51894836/da3728f8-e290-48ba-a331-92ebab88ae14">

<img width="1067" alt="Screenshot 2024-07-11 at 11 30 02 AM" src="https://github.com/py-pdf/pypdf/assets/51894836/6e6351e5-b677-46f5-a325-79a8c388730f">

**Comment by stefan6419846** [comment]
Have you tried using the latest *main* code or the 4.3.0 version not yet available on PyPI?

**Comment by jacobmiller22** [comment]
Hi @stefan6419846 

I just downloaded it, I am not facing the same issue with version `4.3.0`. When do you think this version will be officially released?

I appreciate everyone's efforts to build this great library!

**Comment by stefan6419846** [comment]
We intended to get this released already, but our release automation has not been working correctly and thus we are currently waiting for Martin as the maintainer with write permissions to tackle this manually.

**Comment by jacobmiller22** [comment]
Thank you for the update!
