### ISSUE TITLE
`merge_page` increases file size of resulting pdf superlinearly

### ISSUE THREAD

**Issue by lschlesinger** [py-pdf/pypdf#2768]
When adding a stamp onto a page using `merge_page` we observe an unexpected increase in file size. In our situation, we had a file with varying content (images, text, different page dimensions) that contained 1097 pages and the initial size was 90.8 MB. Adding a simple stamp onto every page made the resulting file (same number of pages) have a size of 213.5 MBs.

We systematically tested this with a minimal test setup leading to the following results:

Stamp: [stamp.pdf](https://github.com/user-attachments/files/16339008/stamp.pdf) | 1 page  | 31 KB 

| Test file    | Pages | Size before merging | Size after merging
| -------- | ------- | ------- | ------- | 
| [test-file2.pdf](https://github.com/user-attachments/files/16339009/test-file2.pdf)  | 8 pages |887 KB| 1.2 MB ~35% bigger
| [test-file3.pdf](https://github.com/user-attachments/files/16339010/test-file3.pdf) | 16 pages | 1.9 MB | 2.5 MB ~32% bigger
| [test-file4.pdf](https://github.com/user-attachments/files/16339012/test-file4.pdf) | 32 pages | 3.8 MB | 5.1 MB ~34% bigger
| [test-file5.pdf](https://github.com/user-attachments/files/16339025/test-file5.pdf) | 64 pages | 7.6 MB | 10.3 MB ~36% bigger
| test-file6.pdf  (too big to upload here) | 384 pages | 46,1 MB | 62,3 MB  ~35% bigger
| test-file7.pdf (too big to upload here) | 1536 pages | 111,1 MB | 175,3 MB ~58% bigger

The test files contain the same content set of 8 pages (1 times for test-file2 up to 192 times for test-file7).

These results indicate a superlinear growth in size with an increasing number of pages.

## Environment

Reproducible on py-pdf 3.7.14; also tested with 4.3.1. (latest) which shows the same behavior.

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader, PdfWriter

def main():
    writer = PdfWriter(clone_from="test-file7.pdf")
    for page in writer.pages:
        reader = PdfReader("stamp.pdf")
        stamp = reader.pages[0]
        page.merge_page(page2=stamp, over=True)
    writer.write('result.pdf')

if __name__ == "__main__":
    main()
```

**Comment by pubpub-zz** [comment]
@lschlesinger 
Can you try to call `.compress_content_streams()` on pages you have modifed and check results. As soon as you modify the contents entry, the data are in clear and do not use any compression.

**Comment by lschlesinger** [comment]
@pubpub-zz , I added `.compress_content_steams()` after `merge_page()`, see adapted script below:

```python
from pypdf import PdfReader, PdfWriter

def main():
    writer = PdfWriter(clone_from="test-file7.pdf")
    for page in writer.pages:
        reader = PdfReader("stamp.pdf")
        stamp = reader.pages[0]
        page.merge_page(page2=stamp, over=True)
        page.compress_content_steams()
    writer.write('result.pdf')

if __name__ == "__main__":
    main()
```
These are the results with the same test files. Surprisingly, the file size of the resulting merged pdf is slightly larger after adding `.compress_content_steams()`.

| Test file    | Pages | Size before merging | Size after merging and compressing content stream
| -------- | ------- | ------- | ------- | 
| [test-file2.pdf](https://github.com/user-attachments/files/16339009/test-file2.pdf)  | 8 pages |887 KB| 1.3 MB
| [test-file3.pdf](https://github.com/user-attachments/files/16339010/test-file3.pdf) | 16 pages | 1.9 MB |  2.6 MB
| [test-file4.pdf](https://github.com/user-attachments/files/16339012/test-file4.pdf) | 32 pages | 3.8 MB |  5.3 MB
| [test-file5.pdf](https://github.com/user-attachments/files/16339025/test-file5.pdf) | 64 pages | 7.6 MB |  10.5 MB
| test-file6.pdf  (too big to upload here) | 384 pages | 46,1 MB | 63.9 MB
| test-file7.pdf (too big to upload here) | 1536 pages | 111,1 MB | 181,2 MB

**Comment by j-t-1** [comment]
`compress_content_steams()` calls `zlib.compress`.

The default value is -1 (Z_DEFAULT_COMPRESSION).
Z_DEFAULT_COMPRESSION represents a default compromise between speed and compression (currently equivalent to level 6).
https://docs.python.org/3/library/zlib.html

You could try `compress_content_streams(level=9)`.

`compress_content_streams` does not use LZW and Flate predictor functions, §7.4.4.4, ISO 32000.
Would using them make the compression better for your use case?

**Comment by lschlesinger** [comment]
@j-t-1, I ran it with `compress_content_streams(level=9)` - see adapted script below, almost the same results (no improvement):

```python
from pypdf import PdfReader, PdfWriter

def main():
    writer = PdfWriter(clone_from="test-file7.pdf")
    for page in writer.pages:
        reader = PdfReader("stamp.pdf")
        stamp = reader.pages[0]
        page.merge_page(page2=stamp, over=True)
        page.compress_content_steams(level=9)
    writer.write('result.pdf')

if __name__ == "__main__":
    main()
```

| Test file    | Pages | Size before merging | Size after merging and <br> compressing content stream (level 9)
| -------- | ------- | ------- | ------- | 
| [test-file2.pdf](https://github.com/user-attachments/files/16339009/test-file2.pdf)  | 8 pages |887 KB| 1.3 MB (same)
| [test-file3.pdf](https://github.com/user-attachments/files/16339010/test-file3.pdf) | 16 pages | 1.9 MB |  2.6 MB (same)
| [test-file4.pdf](https://github.com/user-attachments/files/16339012/test-file4.pdf) | 32 pages | 3.8 MB |  5.3 MB (same)
| [test-file5.pdf](https://github.com/user-attachments/files/16339025/test-file5.pdf) | 64 pages | 7.6 MB |  10.6 MB <br> (vs. 10.5 MB with default level)
| test-file6.pdf  (too big to upload here) | 384 pages | 46,1 MB | 64 MB <br>  (vs. 63.9 MB with default level)
| test-file7.pdf (too big to upload here) | 1536 pages | 111,1 MB | 181 MB <br>  (vs. 181.2 MB with default level)

**Comment by pubpub-zz** [comment]
your code is not optimal : you are creating the stamp many times and therefore the stamps are duplicated instead of mutualize some objects. For a rough of magnitude I would say  are duplicating the 31kB of the stamp.pdf file for each page. For test-file5.pdf it means 64x31kB = ~2MB.
your code should be this one:
```
from pypdf import PdfWriter,PdfReader
writer = PdfWriter(clone_from="test-file5.pdf")
reader = PdfReader("e:/Downloads/stamp-1.pdf")
stamp = reader.pages[0]
for page in writer.pages:
        page.merge_page(page2=stamp, over=True)
        page.compress_content_streams()                 
writer.write("out.pdf")
```

I agree there is still some size increase to explain but I'm sorry I miss time to do that

**Comment by lschlesinger** [comment]
Hi @pubpub-zz , I understand your argument but in our actual use case, the stamp varies per page as it contains the page number so it has to be recreated for every page unfortunately.
And as said, in the case for 1536 pages, the difference of  ~70MB (181 MB - 111.1 MB) can't be explained by the size of all stamps (1536*31 KB = 47.9 MB). 
So despite the lack of time, if you have any other idea at any point, I'd really appreciate it.

**Comment by j-t-1** [comment]
`compress_content_streams` gets the content (as a `StreamObject`) of the `PageObejct`. The `StreamObject` method `flate_encode` is later called and this calls `FlateDecode.encode`, which is a one liner: `return zlib.compress(data, level)`.

This does not use any pre-processing, e.g. Paeth predictor, whereas the original files may do. What are the values of the `DecodeParms` of in the original files? This is more guess work, and someone else here will be able to say if this is a likely cause.

**Comment by pubpub-zz** [comment]
I've done the following test:
```
    from pypdf import PdfWriter,PdfReader
    from io import BytesIO
    writer = PdfWriter(clone_from="test-file5.pdf")
    for page in writer.pages:
        reader = PdfReader("stamp.pdf")
        stamp = reader.pages[0]
        page.merge_page(page2=stamp, over=True)
        page.compress_content_steams(level=9)
    b = BytesIO()
    writer.write(b)
    b.seek(0)
    writer2 = PdfWriter(clone_from=b)
    writer2.write('result.pdf')
```
    This reduces drastically the size. This is most probably due to objects remaining unreferenced in the list of internal objects. during the loading into writer2, these are ignored and discarded. It is hardly impossible to "delete" them at first pass during processing as unlinked by the merge, the objects may be used somewhere . the solution to write/load/write is the only thing I can imagine

**Comment by pubpub-zz** [comment]
@lschlesinger Any update ?
