### ISSUE TITLE
Page.scale_to is slow

### ISSUE THREAD

**Issue by cristianocca** [py-pdf/pypdf#277]
Hi there, 

I'm wondering if are there any ways to speed up the Page.scaleTo performance. Right now the time difference between a code that merges a few PDFS scaling pages and without scaling is about 100x, way too much if you ask me.

The same happens when attempting to add watermarks merging pages, to a point where I'm using a different PDF library only for the watermark process.

Edit, adding some timers to each page scaling... The times are awful! There were some pages that took up to 400ms!

0.146000146866
0.188999891281
0.0449998378754
0.0269999504089
0.140000104904
0.151000022888
0.15700006485
0.144999980927
0.174000024796
0.0439999103546
0.15099978447
0.0460000038147
0.141000032425
0.125
0.250999927521
0.146000146866
0.0419998168945
0.149999856949
0.143000125885
0.0659999847412
0.421000003815
0.0720000267029
0.0909998416901
0.0380001068115
0.0320000648499
0.0279998779297
0.15499997139

**Comment by MartinThoma** [comment]
![mine](https://user-images.githubusercontent.com/1658117/173667172-ceab8682-267e-474e-9027-fc1774abfa94.svg)

**Comment by MartinThoma** [comment]
The problem seems to be how we deal with NumberObjects / FloatObjects ... but I don't understand why there are so many calls / how we could avoid it

**Comment by pubpub-zz** [comment]
During the process of applying a transformation to a page, we convert the page content to a ContentStream, which is doing a lot of conversion. There may be a solution to prevent that and accelerate processing

**Comment by MartinThoma** [comment]
Sadly, I don't quite remember what I used as `script.py`, but there is one that might be interesting + similar to the one used above:

```python
from pathlib import Path
from pypdf import PdfReader
from io import BytesIO
from tests import get_pdf_from_url
data = BytesIO(get_pdf_from_url("https://arxiv.org/pdf/2201.00214.pdf", name="2201.00214.pdf"))
reader = PdfReader(data)

for page in reader.pages:
    page.scale_to(100, 100)
```

Then

```
python -m cProfile -o profile.pstats script.py  # takes ~5min
gprof2dot -f pstats profile.pstats | dot -Tsvg -o mine.svg
```

gives:

![mine](https://user-images.githubusercontent.com/1658117/217897108-456e43e6-1b6d-4d86-8f40-e16840cc94a3.svg)

**Comment by MartinThoma** [comment]
`read_until_regex` takes 27% of the time. We only call it with two regexes:

```
NumberPattern = re.compile(b"[^+-.0-9]")  # in NumberObject
delimiter_pattern = re.compile(rb"\s+|[\(\)<>\[\]{}/%]")  # in NameObject
```

At least the number pattern could potentially be re-written in a much simpler way (just using a loop + character comparison; no regex-engine.

**Comment by MartinThoma** [comment]
I'm closing this issue now as I don't have any further approach to speed this up (except for writing a C/C++/Rust module, which would be a very different beast)

**Comment by pubpub-zz** [comment]
I keep it assigned to me : I may have a solution that would prevent to convert to ContentObject. If my work concludes I will reopen it🤫😉😁
