### ISSUE TITLE
PdfWriter created from file stream does not work in 4.3.x (worked in 4.2.0)

### ISSUE THREAD

**Issue by rrthomas** [py-pdf/pypdf#2771]
Trying to create a `PdfWriter` from a file stream, I get a seek error, or on other occasions a read error, or a complaint that the file is empty.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-6.5.0-41-generic-x86_64-with-glibc2.35

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.3.1, crypt_provider=('cryptography', '3.4.8'), PIL=10.1.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import os
import sys
from pypdf import PdfWriter

PdfWriter(os.fdopen(sys.stdout.fileno(), "wb", closefd=False))
```

No PDF file required.

## Traceback

This is the complete traceback I see:

```
Traceback (most recent call last):
  File "/home/rrt/Software/psutils/foo.py", line 5, in <module>
    PdfWriter(os.fdopen(sys.stdout.fileno(), "wb", closefd=False))
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_writer.py", line 228, in __init__
    clone_from = PdfReader(clone_from)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 137, in __init__
    self.read(stream)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 571, in read
    self._basic_validation(stream)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 630, in _basic_validation
    stream.seek(0, os.SEEK_SET)
io.UnsupportedOperation: File or stream is not seekable.
```

There's no problem running the same script with pypdf 4.2.0.

**Comment by rrthomas** [comment]
I get a similar problem writing to a file directly:

With the following script:

```
import sys
from pypdf import PdfWriter

fh = open("foo.pdf", "wb")
PdfWriter(fh)
```

```
Traceback (most recent call last):
  File "/home/rrt/Software/psutils/foo.py", line 5, in <module>
    PdfWriter(fh)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_writer.py", line 228, in __init__
    clone_from = PdfReader(clone_from)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 137, in __init__
    self.read(stream)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 571, in read
    self._basic_validation(stream)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 632, in _basic_validation
    header_byte = stream.read(5)
io.UnsupportedOperation: read
```

**Comment by rrthomas** [comment]
Making the file readable just shifts the error:

```python
import sys
from pypdf import PdfWriter

fh = open("foo.pdf", "wb+")
PdfWriter(fh)
```

```
python foo.py 
Traceback (most recent call last):
  File "/home/rrt/Software/psutils/foo.py", line 5, in <module>
    PdfWriter(fh)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_writer.py", line 228, in __init__
    clone_from = PdfReader(clone_from)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 137, in __init__
    self.read(stream)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 571, in read
    self._basic_validation(stream)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_reader.py", line 636, in _basic_validation
    raise EmptyFileError("Cannot read an empty file")
pypdf.errors.EmptyFileError: Cannot read an empty file
```

**Comment by pubpub-zz** [comment]
PdfWriter constructor has been modified to be homogeneous with PdfReader to initialize data from the stream
To be quick, in your case I recommend the following:
```
writer = PdfWriter()
f=open('out.pdf','wb')
#do what you want to add data in 

writer.write(f)
#do not forget to close stream
```

**Comment by rrthomas** [comment]
Thanks for the workaround! I'm not sure from the above whether you're saying that there is a bug, or that there's a problem with the documentation? Presumably `PdfWriter` should (now) reject a non-readable file descriptor with a clear error?

> In any case I don't writing a pdf in a middle of a stream to prevent it's interpretation

Is this sentence missing "support" after "I don't"?

**Comment by pubpub-zz** [comment]
oups... (diffcult to type on my phone)
please read "I don't recommend writing"
aspecially as you are writing to files, you may use `writer.write("foo.pdf")`

**Comment by rrthomas** [comment]
Apologies @pubpub-zz, I just searched the documentation on https://pypdf.readthedocs.io/ and I can't find the phrase "recommend writing" anywhere; I also tried just "recommend" and didn't find anything relevant. I also tried grepping the git repo. Or did you mean somewhere else? I can't find that phrase elsewhere in this issue or in the issue tracker more generally.

**Comment by pubpub-zz** [comment]
>  I can't find the phrase "recommend writing"

I meant That the missing word in my post was "recommend"  😄😄😄

In your example you have written:
`fh = open("foo.pdf", "wb+")`

which made though you were wishing to add some bytes before and or after the pdf file.

**Comment by rrthomas** [comment]
Thanks for the explanation!

In my actual use case (in [PSPDFUtils](https://github.com/rrthomas/psutils) I have this line:

```
        self.writer = PdfWriter(self.outfile)
```

All I am trying to do here is create a `PdfWriter` that will write to an existing stream. This could be `stdout`, for example.

So, I think `writer.write` will be fine.

**Comment by pubpub-zz** [comment]
ok to close this thread ?

**Comment by rrthomas** [comment]
My question about documentation still applies: I can't see in the docs where it advises me not to do what I did.

In fact, in my code, all I needed to do was remove the argument to `PdfWriter`, since I later write to a buffer anyway, as `pypdf` requires to be able to seek, so using stdout directly doesn't work.

**Comment by pubpub-zz** [comment]
here is in the documentation some indications on writing a file to a stream:
https://pypdf.readthedocs.io/en/stable/user/streaming-data.html?highlight=pdfwriter#writing-a-pdf-directly-to-aws-s3

Can you point out where your syntax is indicated ?

**Comment by rrthomas** [comment]
Sure, I find on this page: https://pypdf.readthedocs.io/en/stable/modules/PdfWriter.html the following documentation:

class pypdf.PdfWriter(fileobj: [Union](https://docs.python.org/3.12/library/typing.html#typing.Union)[[None](https://docs.python.org/3.12/library/constants.html#None), [PdfReader](https://pypdf.readthedocs.io/en/stable/modules/PdfReader.html#pypdf.PdfReader), [str](https://docs.python.org/3.12/library/stdtypes.html#str), [IO](https://docs.python.org/3.12/library/typing.html#typing.IO)[[Any](https://docs.python.org/3.12/library/typing.html#typing.Any)], [Path](https://docs.python.org/3.12/library/pathlib.html#pathlib.Path)] = '', clone_from: [Union](https://docs.python.org/3.12/library/typing.html#typing.Union)[[None](https://docs.python.org/3.12/library/constants.html#None), [PdfReader](https://pypdf.readthedocs.io/en/stable/modules/PdfReader.html#pypdf.PdfReader), [str](https://docs.python.org/3.12/library/stdtypes.html#str), [IO](https://docs.python.org/3.12/library/typing.html#typing.IO)[[Any](https://docs.python.org/3.12/library/typing.html#typing.Any)], [Path](https://docs.python.org/3.12/library/pathlib.html#pathlib.Path)] = None)

It looks like I have misunderstood what the argument `fileobj` is for. I thought it was to give the output stream to write to. It seems I was mistaken! And the documentation is quite clear.

Apologies.

**Comment by stefan6419846** [comment]
You are of course invited to improve the documentation on the `fileobj` parameter to indicate that it only should be used for reading, but not for writing.

**Comment by rrthomas** [comment]
Thanks for the invitation, but I literally could not understand, on re-reading the docs, how past me could possibly have misunderstood them in the way that I did.
