### ISSUE TITLE
Freeze/huge memory use for one page of PDF file

### ISSUE THREAD

**Issue by SyomaKiss** [py-pdf/pypdf#2790]
When trying to extract the text from all pages of the following document, pypdf freezes at page 34, memory consumption grows up to 3.7 GB on Ubuntu server as well as on macbook.

[2407.21154v1.pdf](https://github.com/user-attachments/files/16517852/2407.21154v1.pdf)

The code I am using
```python
from pypdf import PdfReader
from tqdm import tqdm

def extract_text_from_pdf(pdf_path):
    reader = PdfReader(pdf_path)
    all_text = []
    for page in tqdm(reader.pages):
        all_text.append(page.extract_text())
    all_text = '\n'.join(all_text)
   
    return all_text
```

**Comment by stefan6419846** [comment]
From my observations, the slowest extraction call is for page index 34, id est page 35, taking about 1:45 min. I cannot observe a real freeze and no actual memory issue.

The reason for the execution time becomes obvious it you look at the offending page by isolating it and reviewing the content. In my case, extracting page 35 yields to a file sized 127.4 MiB, with the page content being plain render commands only, which need to be processed for possible text to extract. (For comparison: Page 34 will be 6.4 MiB with the same process and mostly refers to an embedded image which is not being touched during text extraction.)

Given that, I do not consider this a memory leak and something which *pypdf* probably cannot do much about. This is just a complex PDF file/page, taking longer to process accordingly.

**Comment by SyomaKiss** [comment]
@stefan6419846 can you please track your RAM usage for this task?
```
CONTAINER ID   NAME                        CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
73080d656d78   <name>   100.17%   4.056GiB / 503.3GiB   0.81%     10.2MB / 25.9kB   4.1kB / 25.5MB   3
```

**Comment by stefan6419846** [comment]
I cannot confirm such a performance when running this natively (without containerization) on different more or less recent i7 systems with Ubuntu in one case. My systems require about 2.5 GB of RAM and less than two minutes to process this file.

There is no way to give concrete values about an "adequate consumption" of RAM. I can just state that the more complex the PDF becomes, the longer the task will most likely take and  increase the used RAM.

**Comment by SyomaKiss** [comment]
> I cannot confirm such a performance when running this natively (without containerization) on different more or less recent i7 systems with Ubuntu in one case. My systems require about 2.5 GB of RAM and less than two minutes to process this file.
> 
> There is no way to give concrete values about an "adequate consumption" of RAM. I can just state that the more complex the PDF becomes, the longer the task will most likely take and increase the used RAM.

Took about 3 hours to process :)

Here is the output of python memory profiler. Monitoring with my eyes separately I noticed a peak of around 6.5 gb RAM used.
```
2024-08-07T06:44:52.127807036Z Line #    Mem usage    Increment  Occurrences   Line Contents
2024-08-07T06:44:52.127810213Z =============================================================
2024-08-07T06:44:52.127817036Z     31    127.0 MiB    127.0 MiB           1   @profile
2024-08-07T06:44:52.127823558Z     32                                         def extract_text_from_pdf(pdf_path, output_folder=None):
2024-08-07T06:44:52.127832475Z     33    135.1 MiB      8.0 MiB           1       reader = PdfReader(pdf_path)
2024-08-07T06:44:52.127838967Z     34    135.1 MiB      0.0 MiB           1       all_text = []
2024-08-07T06:44:52.127845039Z     35   3291.0 MiB    -21.2 MiB          58       for page in tqdm(reader.pages):
2024-08-07T06:44:52.127851190Z     36   3291.0 MiB   3133.8 MiB          57           all_text.append(page.extract_text())
2024-08-07T06:44:52.127857883Z     37   3290.0 MiB     -1.0 MiB           1       all_text = '\n'.join(all_text)
2024-08-07T06:44:52.127864295Z     38   3290.0 MiB      0.0 MiB           1       if output_folder is not None:
2024-08-07T06:44:52.127870567Z     39                                                 doc_output_folder = Path(output_folder) / Path(pdf_path).name.replace(' ', '_')
2024-08-07T06:44:52.127876919Z     40                                                 doc_output_folder.mkdir(exist_ok=True)
2024-08-07T06:44:52.127883010Z     41                                                 with open(doc_output_folder / 'text.txt', 'w') as fp:
2024-08-07T06:44:52.127889272Z     42                                                     fp.write(all_text)
2024-08-07T06:44:52.127895353Z     43   3290.0 MiB      0.0 MiB           1       return all_text
```

**Comment by pubpub-zz** [comment]
page 35 contains 4 XObjects which are "Forms" (i.e. they contain PDF drawing instructions). These images needs are analysed at will as they can/do contain text. here each image after been decompressed contains about 1.2GB/300MB/400MB/450MB of data : the amount of used memory is consistent.

**Comment by pubpub-zz** [comment]
I propose to close this issue

**Comment by SyomaKiss** [comment]
> I propose to close this issue

It does not look to me that analysing such heavy "Forms" is desired behaviour in all cases. I would propose an enhancements of additional argument to the PdfReader which will disable text extraction from such kind of "Forms"

**Comment by pubpub-zz** [comment]
> > I propose to close this issue
> 
> It does not look to me that analysing such heavy "Forms" is desired behaviour in all cases. I would propose an enhancements of additional argument to the PdfReader which will disable text extraction from such kind of "Forms"

Waiting for your PR

**Comment by SyomaKiss** [comment]
Some questions for this task
- What kind of objects are usually XObjects
- Is there a way to diffirintiate between large "Forms" and other staff which is fast to process.

**Comment by pubpub-zz** [comment]
> Some questions for this task
> 
>     * What kind of objects are usually XObjects

these are StreamObject. You should have a look where `extract_xform_text()` is called

> 
>     * Is there a way to diffirintiate between large "Forms" and other staff which is fast to process.

There is no solution: text can be in either formats. I see no reason to reject one type of object and not the other. It is just an optional parameter to be used carefully by advanced users.

**Comment by SyomaKiss** [comment]
@pubpub-zz Do you think we could release resources after each XObject is processed, in the scope of text extraction processing?

This will allow us to store in RAM at most the size of biggest XObject, not their cumulative size.

**Comment by pubpub-zz** [comment]
> @pubpub-zz Do you think we could release resources after each XObject is processed, in the scope of text extraction processing?
> 
> This will allow us to store in RAM at most the size of biggest XObject, not their cumulative size.

Don't know if this is just to call Garbage Collection. Can not remember if you rebuild the whole page content

**Comment by pubpub-zz** [comment]
@SyomaKiss 
any progress ?

**Comment by SyomaKiss** [comment]
Best workaround for the problem is to read page content in separate thread and abort it if reading takes too long.

```
from func_timeout import func_timeout, FunctionTimedOut


def get_text_from_page(page):
    return page.extract_text()


def get_text_from_page_w_timeout(page, timeout=15):
    try:
        page_text = func_timeout(timeout, get_text_from_page, args=(page,))
        return page_text
    except FunctionTimedOut:
        logging.info(f"Text extraction could not complete within {timeout} seconds and was terminated.\n")
        return ''
```

Hope this helps. Updating repo is redundant imho. We can close the issue I suppose
