### ISSUE TITLE
Type hint for page.images needs adjusting

### ISSUE THREAD

**Issue by pm-incyan** [py-pdf/pypdf#2798]
When running mypy for type checking, if you access things like `page.images.keys()` you get a type error:

     error: "list[ImageFile]" has no attribute "keys"  [attr-defined]

This is due to the fact the return type of that property is defined as `List[ImageFile]`

https://github.com/py-pdf/pypdf/blob/cf7fcfd568bb96bb2a3b978a0bd031a18e6d90b7/pypdf/_page.py#L498

In fact the returned object (while it does imitate a sequence) is a `_VirtualListImages`

https://github.com/py-pdf/pypdf/blob/cf7fcfd568bb96bb2a3b978a0bd031a18e6d90b7/pypdf/_page.py#L535

The type hint for the image property doesn't know about this, and so when using the extra methods provided by `_VirtualListImages` such as `keys()` you hit the type checking error.

**Comment by stefan6419846** [comment]
Thanks for the report. Do you want to submit a corresponding PR?

**Comment by pm-incyan** [comment]
Potentially, but I've not got the bandwidth right at this moment, so happy for another to pick up in the meantime.

**Comment by pm-incyan** [comment]
Yes all good testing locally after your second commit to the PR.
