### ISSUE TITLE
Encoding error when inserting bookmark (using add_outline_item)

### ISSUE THREAD

**Issue by DertahSama** [py-pdf/pypdf#2803]
when I'm trying to insert non-ascii characters in bookmark using `add_outline_item()`，it's broken. 

like this:
![image](https://github.com/user-attachments/assets/3e8b6d6b-56d5-4be2-8b24-fd06de820fbf)

I think this is a pretty primitive encoing problem! 
When I was using PyPDF2 some years ago, there is no such error. I hope this can be solved easily.

## Environment

```bash
$ python -m platform
# Windows-10-10.0.19045-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
# pypdf==4.3.1, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=9.5.0
```

encoding: my vscode is UTF-8, win10 is GBK.

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfWriter

with PdfWriter() as ww:
    ww.append("test.pdf")
    ww.add_outline_item("swiper-lazy-preloader-white",0,parent=None)
    ww.add_outline_item("Сколько лет, сколько зим!",0,parent=None)
    ww.add_outline_item("爱开大会，骄傲祭扫好看！",0,parent=None)
    ww.add_outline_item("いつもお世話になっております。",0,parent=None)
    ww.write("test1.pdf",)
```

a test pdf:
[test.pdf](https://github.com/user-attachments/files/16644738/test.pdf)

## Traceback

no traceback since the code can run.

**Comment by pubpub-zz** [comment]
can you try with the lastest build from dev branch (see https://pypdf.readthedocs.io/en/stable/dev/testing.html#evaluate-a-pr-in-progress-version)

**Comment by DertahSama** [comment]
> can you try with the lastest build from dev branch (see https://pypdf.readthedocs.io/en/stable/dev/testing.html#evaluate-a-pr-in-progress-version)

Oh! It's fixed!! Happy to see it get solved so quickly, thx! 
![image](https://github.com/user-attachments/assets/715e75e7-d27e-4760-91d2-5949596ff27d)
I installed `pip install git+https://github.com/pubpub-zz/pypdf.git@iss2754`

Hope you can merge it into main branch soon~

**Comment by pubpub-zz** [comment]
happy the fix was working. We should release the version no latter than early september

**Comment by fragileeye** [comment]
Thanks all, that helps me a lot.
