### ISSUE TITLE
Text Extraction from PDF Results in Garbled Characters

### ISSUE THREAD

**Issue by hrhktkbzyy** [py-pdf/pypdf#2807]
## Issue
When extracting text from the attached PDF, the output contains garbled characters. Additionally, when I tried copying & pasting the content from other PDF viewers, similar issues occurred.

I'm unsure if this is related to encoding settings or if there's a way to correct the extraction process.  Any guidance or fixes would be appreciated.

## PDF is as attached
[king arthur.pdf](https://github.com/user-attachments/files/16707281/king.arthur.pdf)
[The Phantom of the Opera.pdf](https://github.com/user-attachments/files/16707282/The.Phantom.of.the.Opera.pdf)

## pypdf version
`pypdf==4.3.1`

## Code Sample:

```
from pypdf import PdfReader

def get_text_from_pdf_by_pypdf(file_path):
    try:
        text = ''
        reader = PdfReader(file_path.absolute())

        pages = reader.pages
        number_of_pages = len(pages)
        for page_obj in pages:
            text_add = page_obj.extract_text()
            if text_add:
                text += text_add

        return text, number_of_pages

    except Exception as e:
        print(e)
        return None, None
```

## Output
The extracted content includes cid values such as:

```

7KHGDQFHUV

4XLFN4XLFN&ORVHWKHGRRU,W
VKLP
$QQLH6RUHOOLUDQLQW RWKH
GUHVVLQJURRPKHUIDFHZKLWH
2QHRIWKHJLUOVUDQDQGFORVHGWKHGRRUDQGWKHQWKH\DOOWXU QHGWR
$QQLH6RUHOOL
```

**Comment by pubpub-zz** [comment]
your documents have been protected against copy : pypdf reports the same results as other viewers. There is nothing to be done but e-print/scan with OCR.
this has been reported many times
