### ISSUE TITLE
Getting Advanced encoding /UniGB-UTF16-H not implemented error for chinese text

### ISSUE THREAD

**Issue by Aswin4070** [py-pdf/pypdf#2812]
Replace this: What happened? What were you trying to achieve?

## Environment

Which environment were you using when you encountered the problem?

```bash
from pypdf import PdfReader
reader = PdfReader("chinese-text.pdf")
```

Error:
```
"Advanced encoding /UniGB-UTF16-H not implemented yet" error continuously for all the lines.
```

When is looked at the code in her for cmap file in pypdf: 
https://github.com/py-pdf/pypdf/blob/main/pypdf/_cmap.py

I see the the particular encoding - "**/UniGB-UTF16-H**" is not declared in "_predefined_cmap" in the code

Can we add just the encoding type under _predefined_cmap"
```
UniGB-UTF16-H | ISO/IEC 10646 (Unicode), UTF-16 encoding
```
or should we create something like this:
```
elif "UniGB-" in enc:
                encoding = "utf-16-be"
```

**Comment by pubpub-zz** [comment]
@Aswin4070  can you share your test document for analysis

**Comment by pubpub-zz** [comment]
after looking on internet and a few tests I would have more likely proposed to use gb18030:
make a test adding at the end of _prefdefined_cmap:
```
    "\UniGB−UTF16−H": "gb18030",
    "\UniGB−UTF16−V": "gb18030",
```

**Comment by pubpub-zz** [comment]
@Aswin4070 
any update ? is it possible to have a copy of the document ?

**Comment by Aswin4070** [comment]
Hi @pubpub-zz ,

Sorry for the delay.

[W020240105322424121296.pdf](https://github.com/user-attachments/files/16767536/W020240105322424121296.pdf)

You can the pdf from here:
https://www.cpnn.com.cn/news/baogao2023/202401/W020240105322424121296.pdf

**Comment by pubpub-zz** [comment]
Thx
gb18030 was the good choice but I mistype "\" instead of "/"
pr is issued
