### ISSUE TITLE
duplicated pages in the output pdf if PdfMerger.write() being called multiple times

### ISSUE THREAD

**Issue by momincks** [py-pdf/pypdf#2826]
**Issue:**
if input pdf has 3 pages, output pdf would have 9 pages after 3 calls of merger.write()

**Cause:**
.write() add pages to merger.output, but same instance of merger.output being reused for each .write()

**To reproduce:**
```
from pypdf import PdfMerger
merger = PdfMerger()

pdfs = ['x.pdf']
for pdf in pdfs:
    merger.append(pdf)

merger.write(f"y.pdf")
merger.write(f"y.pdf")
merger.write(f"y.pdf")
merger.close()
```

**Comment by stefan6419846** [comment]
`PdfMerger` is deprecated. Please check with the `PdfWriter` which is the recommended replacement.

**Comment by pubpub-zz** [comment]
@momincks any update ?
