### ISSUE TITLE
ignore warnings not working

### ISSUE THREAD

**Issue by AnzhiZhang** [py-pdf/pypdf#2830]
I tried to ignore warnings but warnings still appear: https://pypdf.readthedocs.io/en/stable/user/suppress-warnings.html#warnings

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-11

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.3.1, crypt_provider=('cryptography', '43.0.0'), PIL=9.3.0
```

## Code + PDF

I do not think these are really needed.

This is a minimal, complete example that shows the issue:

```python
merged_pdf = PdfWriter()

for page in pages:
    merged_pdf.append(page.path)

merged_pdf.write(self.merged_pdf_path)
merged_pdf.close()
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete traceback I see:

```
Multiple definitions in dictionary at byte 0xc4d7 for key /Ascent
```

**Comment by AnzhiZhang** [comment]
See also: https://stackoverflow.com/questions/66727458/warnings-filterwarningsignore-doesnt-ignore-logging-warning

By the way, set logging level can resolve this issue.

```python
import logging

logger = logging.getLogger("pypdf")
logger.setLevel(logging.ERROR)
```

**Comment by stefan6419846** [comment]
The corresponding message is emitted using `logger_warning`, which basically maps to `logger.warning`: https://github.com/py-pdf/pypdf/blob/82eac7e316f8f785d00ed600f8ba4aba3296a4a8/pypdf/generic/_data_structures.py#L538 Such warnings cannot be suppressed by `warnings.filterwarnings`.

There already have been some discussions about this in #2020 to improve the docs and mention possible workarounds. Nevertheless, it depends on your specific use case on how you want to deal with these cases - maybe its okay to change the minimum log level to filter for, maybe you want to see it, ... (In some of my own code, I am monkey-patching all imports of `logger_warning` to log at the info level for example, but this is no general-purpose solution unless you know what you are doing.)
