### ISSUE TITLE
PEP 585 – Type Hinting Generics In Standard Collections

### ISSUE THREAD

**Issue by j-t-1** [py-pdf/pypdf#2837]
Should we be removing some typing module imports?
https://peps.python.org/pep-0585/

https://github.com/py-pdf/pypdf/blob/e694d5571ced01b10d0e982ee97d704218b5f991/pyproject.toml#L161

**Comment by stefan6419846** [comment]
Migrating to the new annotations behavior is something which I would postpone to after the next major release and after the currently open bigger PRs from the last days have been merged. This will probably happen next week, although we still need to have a look at getting the automated release builds to work ideally.

**Comment by pubpub-zz** [comment]
@j-t-1 
this can only be proposed when we will no more support 3.8 which will not occur before version 6.0.0 I would assume to be not before 6 months from now. I propose to move this issue into a discussion

**Comment by stefan6419846** [comment]
But doesn't Python 3.8 already support the new annotations behavior? Or are there some limits I am not directly aware of (my minimum Python version I use on a daily basis is 3.9).

**Comment by pubpub-zz** [comment]
PEP-0585 is for python 3.9+

**Comment by pubpub-zz** [comment]
I propose to close this issue. @j-t-1 can you create a new issue when will be drop 3.8 support ?

**Comment by j-t-1** [comment]
> I propose to close this issue. @j-t-1 can you create a new issue when will be drop 3.8 support ?

Yes, will do.
