### ISSUE TITLE
extract_text() with extraction_mode="layout" ignores visitor* arguments

### ISSUE THREAD

**Issue by kaos-ocs** [py-pdf/pypdf#2840]
Trying to get the text information in layout mode. The visitor_text() callable is silently ignored in layout mode and, looking at the code, none of the visitor callables are passed to layout mode.

## Environment

```bash
$ python -m platform
Linux-6.8.0-41-generic-x86_64-with-glibc2.39

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.0.2, crypt_provider=('cryptography', '41.0.7'), PIL=10.2.0
```
This is a minimal, complete example that shows the issue:

```python
#! /bin/env python

from pypdf import PdfReader
def visitor(text, ctm, tm, fd, fs):
    print((text, ctm, tm, fd, fs))

print("layout")
PdfReader('pypdf/resources/toy.pdf').pages[0].extract_text(visitor_text=visitor, extraction_mode="layout")
print("plain")
PdfReader('pypdf/resources/toy.pdf').pages[0].extract_text(visitor_text=visitor, extraction_mode="plain")
```

**Comment by stefan6419846** [comment]
Thanks for the report. Which benefits would you expect from using a visitor with layout mode? AFAIK the visitor is called for each text command to allow for custom processing and position retrieval, which should be identical for both modes.

**Comment by kaos-ocs** [comment]
It was more like "my visitor is not being called, what did I do wrong?", i.e., an unexpected result. This was my first use of pypdf and I used layout mode to preserve the original look.

Update the docstring to note that visitors are not called in layout mode.

**Comment by kaos-ocs** [comment]
https://github.com/py-pdf/pypdf/pull/2845

**Comment by kaos-ocs** [comment]
On a different topic: I could not run pytest against pyenv 3.7.15 because of missing imports from typing such as Protocol, Literal. They are in typing_extensions for 3.7.15 but not in typing. pytest ran fine in 3.12.3, but the Makefile specifies 3.7.15. How do people run pytest against 3.7.15?

**Comment by stefan6419846** [comment]
The *main* branch recently dropped support for Python 3.7, thus running *pytest* there would fail even after a `typing_extensions` change. I guess nobody has used (or is actively using) the Makefile for running the tests since then. Feel free to propose a fix as well.
