### ISSUE TITLE
Handling of incomplete EOF markers

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#2853]
I just stumbled upon a PDF sent by e-mail where the final `OF` of the EOF marker has been missing. Apparently, pdf.js and Evince are able to display it correctly, while *pypdf* fails.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.14.21-150400.24.100-default-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.3.1, crypt_provider=('pycryptodome', '3.18.0'), PIL=10.0.0
```

Note: The version is the latest *main* code.

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

reader = PdfReader('file.pdf')
```

For the file, just take any valid PDF file and remove the final `OF` characters of `%%EOF`.

## Traceback

This is the complete traceback I see:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/temp/pdf/pypdf/_reader.py", line 142, in __init__
    self.read(stream)
  File "/home/stefan/temp/pdf/pypdf/_reader.py", line 566, in read
    self._find_eof_marker(stream)
  File "/home/stefan/temp/pdf/pypdf/_reader.py", line 658, in _find_eof_marker
    line = read_previous_line(stream)
  File "/home/stefan/temp/pdf/pypdf/_utils.py", line 279, in read_previous_line
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
pypdf.errors.PdfStreamError: Stream has ended unexpectedly

```

**Comment by pubpub-zz** [comment]
there is one extra point behind that I've detected : If the %%EOF is truncated/missing, pypdf searches further in the file. If the file is linearized or has been incrementally built, a full "section" may be ignored without warning.
