### ISSUE TITLE
Object 3702 0 not defined.

### ISSUE THREAD

**Issue by mohamedsaeed138** [py-pdf/pypdf#2870]
When I'm trying  to make a PdfWriter from a local pdf file using the clone_from argument in the PdfWriter constructor, it prints to the console this statement "Object 3702 0 not defined."

**Comment by stefan6419846** [comment]
This is just a warning and indicates that there might be some standard violation within your PDF file. If there are further issues, please provide the corresponding code and PDF file for further analysis.

**Comment by mohamedsaeed138** [comment]
I appreciate your help.
