### ISSUE TITLE
incorrect startxref pointer(3)

### ISSUE THREAD

**Issue by mohamedsaeed138** [py-pdf/pypdf#2871]
When I'm trying to make a PdfWriter from a local pdf file using the clone_from argument in the PdfWriter constructor, it prints to the console this statement "incorrect startxref pointer(3)".

**Comment by stefan6419846** [comment]
Please avoid reporting each warning you receive unless there are real issues. In these cases, please use the existing issue templates and fill them accordingly to allow further analysis.
