### ISSUE TITLE
BUG: infinite loop on damaged pdf file

### ISSUE THREAD

**Issue by pubpub-zz** [py-pdf/pypdf#2877]
(for issue creation/tracking)
Note : With the latest dev build 

an infinite loop occurs when getting number of pages
https://github.com/user-attachments/files/17162634/7f40cb209fb97d1782bffcefc5e7be40.pdf

_Originally posted by @pubpub-zz in https://github.com/py-pdf/pypdf/issues/2876#issuecomment-2379649591_

**Comment by pubpub-zz** [comment]
the pdf contains some dictionnaries where the << and >> are not balanced. this creates an infinite loop when parsing file

**Comment by stefan6419846** [comment]
How is this different from #2876?

**Comment by pubpub-zz** [comment]
from my understanding, #2876 deals with memory. Here, the infinite has been generated because of #2872.
maybe at the end the fix will cover both.
