### ISSUE TITLE
PDF /PageLayout and /PageMode options

### ISSUE THREAD

**Issue by snorfalorpagus** [py-pdf/pypdf#29]
Hi,

I've been using PyPDF2 to merge some PDF files, adding bookmarks to the various pages as needed. I've been using the code below to set the initial view of the output PDF so that it shows one page at a time, and displays the bookmarks navigation panel.

```
pdf = PdfFileWriter()
root = output.getObject(pdf._root)
root.update({NameObject('/PageLayout'): NameObject('/SinglePage'), NameObject('/PageMode'): NameObject('/UseOutlines')})
```

I'm wondering if there would be any interest in writing this into a more formal method. Maybe something like:

```
pdf = PdfFileWriter()
pdf.page_layout = 'SinglePage'
pdf.page_mode = 'Bookmarks'
```

I'm happy to write this an submit a pull request, but I though I'd get some feedback on the syntax.

In addition to this, it would be nice to be modify the author, title, etc. Maybe this is already possible and I've just missed it...

**Comment by RenatoBMLR** [comment]
Hi,
I'm trying to read a PDF file and extract the contents from it, however, I could't  realize how the method (setPageLayout) works and then read it correctly.. Would you mind to create an example to better understand?
thx
