### ISSUE TITLE
Add an argument ``layout_mode_height_weight`` to control inference of vertical space when extracting text in layout mode

### ISSUE THREAD

**Issue by hpierre001** [py-pdf/pypdf#2915]
Sometimes, two lines can be separated by an empty line which is height is smaller than than font_height.
The goal would be to control wether it should be kept as an empty line or not.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
