### ISSUE TITLE
Unable to load some certain PDFs using the latest version.

### ISSUE THREAD

**Issue by AliFaridCollide** [py-pdf/pypdf#2948]
Unable to load some PDFs with the latest version. Same PDFs can be loaded using version 4.3.1.
A sample PDF is attached.
Getting:
UnboundLocalError: local variable 'v' referenced before assignment
[aboutaha1998.pdf](https://github.com/user-attachments/files/17777330/aboutaha1998.pdf)

**Comment by stefan6419846** [comment]
Please use the bug report template for reporting to ensure that the proper details are given. AFAIK this only affects `extract_text`.

Apart from this, you should have a look at similar issues before opening a new one. This has already been reported in #2925 and fixed on *main*, but not yet released.
