### ISSUE TITLE
Update namespace links in xmp.py

### ISSUE THREAD

**Issue by j-t-1** [py-pdf/pypdf#2951]
The namespace links in [xmp.py](https://github.com/py-pdf/pypdf/blob/main/pypdf/xmp.py) need updating.

**Comment by stefan6419846** [comment]
Could you please elaborate with a source for this?

**Comment by j-t-1** [comment]
The Adobe links are not working. Preferably we can find updates from the PDF Association or  ISO websites.

**Comment by j-t-1** [comment]
Good find. I can update these sometime this week.

**Comment by stefan6419846** [comment]
As mentioned, the namespace should not require a change according to the linked docs, thus I am not sure if there is anything to do about this issue at all.

**Comment by j-t-1** [comment]
You are saying (almost certainly correctly) that the links (like `XMP_NAMESPACE = "http://ns.adobe.com/xap/1.0/`) did contain correct data that was used. There may not be anything to do here then (a non-issue). I will read more about XMP as have not used before.
