### ISSUE TITLE
Local variable 'v' referenced before assignment causing exception.

### ISSUE THREAD

**Issue by ajrlewis** [py-pdf/pypdf#2959]
I got an UnboundLocalError when extracting text from a LaTeX document that contains symbols (e.g. /Letter for mail symbol, /Mundus for world symbol). Simple fix to `_type1_alternative` method in `pypdf/_cmap.py` module by adding `v = ""` on line 515.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# macOS-10.16-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
# pypdf==5.1.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.3.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
for page in pdf_reader.pages:
    pdf_text = page.extract_text()
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete traceback I see:

```
pypdf/_cmap.py", line 530, in _type1_alternative
    map_dict[chr(i)] = v
UnboundLocalError: local variable 'v' referenced before assignment
```

**Comment by stefan6419846** [comment]
Please have a look at the existing issues before opening a new one. This has already been reported before in #2925, but just not released.

**Comment by jakep-allenai** [comment]
I can confirm, ran into a similar issue, and it is fixed in the latest main branch
