### ISSUE TITLE
Transferred Annotations not Rendering Correctly

### ISSUE THREAD

**Issue by eth-wa** [py-pdf/pypdf#2960]
We often get new/revised PDF's for plan documents. Part of the transfer process is transferring any Annotations from the previous version to the new version. We've been doing this using our PDF software, but I wanted to try an hammer it out programmatically with pypdf.
However, I'm not sure if our PDF software is under-defining the Annotation data or what, but it's inconsistent with what existed vs. what's rendered in the new PDF.
If this is user error, I apologize. I'm intermediate at best in Python, so if there's a way I can filter the Annotation data to get on the correct format, I'm all ears (and very grateful)
*There are some foobar annotations that I was using for testing.

## Environment
```bash
$ python -m platform
Windows-11-10.0.22631-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==5.1.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=none
```

## Code + PDF

Below is a test code I was working on that pulls in the New/Old PDF, extracts the Annotation objects from the Old PDF, and attempts to write them to the New PDF

```python
import pypdf

writer = pypdf.PdfWriter()

OldPath = "\\\\UNC\\Folder\\OldPath.pdf"
NewPath = "\\\\UNC\\Folder\\NewPath.pdf"
SavePath = "\\\\UNC\\Folder\\SavePath.pdf"

#setup Writer (new plan sheet)
writer.append(NewPath)

#setup Reader (old plan sheet)
input_stream = open(OldPath, "rb")
reader = pypdf.PdfReader(input_stream, strict=False)
page = reader.pages[0]

if '/Annots' in page: #if the page has Annotations
    for annot in page['/Annots']:
        obj = annot.get_object()
        if '/Type' in obj: #Annotation has /Type
            if obj['/Type'] == '/Annot': #/Type is /Annot
                if obj['/F'] !=132: #Skip Locked Annotations
                    writer.add_annotation(page_number=0, annotation=obj) #Add annotation to Writer

with open(SavePath,"wb") as new:
    writer.write(new) #Save PDF

#Clean up
reader.close
writer.close
```

Below are the PDF files - OldPath, NewPath, and SavePath
[OldPath.pdf](https://github.com/user-attachments/files/17834822/OldPath.pdf)
[NewPath.pdf](https://github.com/user-attachments/files/17834823/NewPath.pdf)
[SavePath.pdf](https://github.com/user-attachments/files/17834825/SavePath.pdf)

## Traceback
No Traceback as the code runs without error, but the end result is unexpected.

**Comment by stefan6419846** [comment]
Not related to your issue, bout `reader.close` and `writer.close` do nothing unless you actually call `.close()` instead ;)

Apart from this: The issue should be much easier to analyze if you could provide a small example showing the same problem without all the overhead of the page content. I would appreciate a simple reproducer with the following properties:

* A simple PDF file without annotations.
* The simple PDF file with the annotations added.
* The simple PDF file with the annotations copied on through *pypdf*.

This way, we should be able to better spot which values might changed in-between without too much overhead.

Are you able to provide such an example?

**Comment by eth-wa** [comment]
@stefan6419846 , yes I will be able to provide a much simpler example at a later time, hopefully within the next 24 hours at the most. I'll also include multiple annotation types.
thanks for the not-related comment -- that actually answers a not-related issue I was having while doing my troubleshooting. I'm too used to VBA it seems.

**Comment by eth-wa** [comment]
@stefan6419846 , attached are four files:

File to read Annotations from (reader): 
[1OldFile.pdf](https://github.com/user-attachments/files/17856082/1OldFile.pdf)

File to write Annotations to (writer):
[2NewFile.pdf](https://github.com/user-attachments/files/17856085/2NewFile.pdf)

PyPDF Output (writer.write):
[3SaveFile.pdf](https://github.com/user-attachments/files/17856090/3SaveFile.pdf)

Expected Output (3rd party PDF software annotations transfer):
[4ExpectedFile.pdf](https://github.com/user-attachments/files/17856093/4ExpectedFile.pdf)


If I need to make it any simpler, please let me know. I added about every annotation type I had at my disposal.

And thank you again!

**Comment by pubpub-zz** [comment]
AddAnnotation does not handle properly the indirect objects. as an alternative I would propose this:
```
import pypdf
r = pypdf.PdfReader("1OldFile.pdf")
w = pypdf.PdfWriter("2NewFile.pdf")

if "/Annots" not in w.pages[0];
    w.pages[0][pypdf.generic.NameObject("/Annots")] = pypdf.generic.ArrayObject()

for a in r.pages[0]["/Annots"]:
    w.pages[0]["/Annots"].append(a.clone(w,ignore_fields=("/P",)))  # ignore "/P" to discard the pointer to the page, invalid in clone and which is optional

w.write("e:/tt.pdf")
```

**Comment by eth-wa** [comment]
> ```
> import pypdf
> r = pypdf.PdfReader("1OldFile.pdf")
> w = pypdf.PdfWriter("2NewFile.pdf")
> 
> if "/Annots" not in w.pages[0];
>     w.pages[0][pypdf.generic.NameObject("/Annots")] = pypdf.generic.ArrayObject()
> 
> for a in r.pages[0]["/Annots"]:
>     w.pages[0]["/Annots"].append(a.clone(w,ignore_fields=("/P",)))  # ignore "/P" to discard the pointer to the page, invalid in clone and which is optional
> 
> w.write("output.pdf")
> ```

@pubpub-zz , Thank you! that solution worked - all Annotations transferred perfectly.
As a matter of fact, they transfered BETTER than what my Expected File (using 3rd party "import annotations" method) had.
Quicker, Easier, and Better? You don't get that often, if ever. Yet here we are.

Marking this as Closed, thanks for correcting the "user error", and thank you again for your time and knowledge
