### ISSUE TITLE
PdfReadError: Image data is not rectangular

### ISSUE THREAD

**Issue by Verdant31** [py-pdf/pypdf#2993]
I don't know exactly what I'm describing here, I just tried opening a PDF and checking the images and it keeps giving this strange error

## Environment

Python 3.12.4
Pypdf 5.1.0

## Code + PDF

```python
for index, page in enumerate(reader.pages):
    for count, image_file_object in enumerate(page.images):
        with open(str(count) + image_file_object.name, "wb") as fp:
            fp.write(image_file_object.data)
```

I cant display the pdf here because it has confidencial info

## Traceback

    176 @staticmethod
    177 def _decode_png_prediction(data: bytes, columns: int, rowlength: int) -> bytes:
    178     # PNG prediction can vary from row to row
    179     if len(data) % rowlength != 0:
    180         raise PdfReadError("Image data is not rectangular")
    181     output = []
    182     prev_rowdata = (0,) * rowlength
    PdfReadError: Image data is not rectangular

**Comment by stefan6419846** [comment]
The encoded image data has the wrong number of bytes and thus decoding cannot be done by default. Please provide the corresponding PDF file for further analysis - maybe there is a way to solve this specific case.

**Comment by Verdant31** [comment]
Tried using pymupdf to load the images from that specific page that throws the error using pypdf and it worked. I will close the pull request because i cant display the PDF here for more info (has confidencial pages)
