### ISSUE TITLE
Question about documentation for xmp_metadata.dc_description and xmp_metadata.dc_subject

### ISSUE THREAD

**Issue by dfkettle** [py-pdf/pypdf#3023]
I think I'm just a little confused about the terminology in the documentation. Initially I was using dc_subject to retrieve the subject and pdf_keywords to retrieve the keywords. About after some trial-and-error, it seems I should be using xmp_metadata.dc_description and xmp_metadata.dc_subject to retrieve the subject and keywords, respectively. 

Here's the final version of my code (after making the change described above):

```
from pypdf import PdfReader

reader = PdfReader("The History of the Franks by Gregory of Tours.pdf")

print("Subject: %s" % reader.xmp_metadata.dc_description)
print("Keywords: %s" %reader.xmp_metadata.dc_subject)
```

It returns the following results (the metadata provided by the publisher isn't very helpful in this case, but that's beside the point):

```
Subject: {'x-default': 'www.delphiclassics.com'}
Keywords: ['Medieval Library']

```

When I open the file in Adobe Acrobat Reader and display the metadata, I see this:

![Image1](https://github.com/user-attachments/assets/a7c7dfa7-e9b3-49c3-86b9-3d1d53504e5c)

So I guess Adobe just uses different terminology. What Adobe calls "Subject" is stored in dc_description, and what Adobe calls "Keywords" is stored in dc_subject. I'm not suggesting that you change the behaviour of pypdf, but maybe the documentation could be made a little clearer (translate pypdf-speak to Adobe-speak).

**Comment by stefan6419846** [comment]
Thanks for opening this issue. This mapping sounds a bit odd for me. Could you please provide a corresponding test file or at least verify with the "regular" (non-XMP) metadata that the values are not coming from there for Acrobat?

**Comment by dfkettle** [comment]
I'm not sure I understand the question, but this behaviour occurs with any pdf file (assuming it has subject and keywords, as displayed by Adobe Acrobat). Anyway, here's the file. I'm using pypdf 5.1.0 under Python 3.10.12 and Windows 10 v22H2.

[The History of the Franks by Gregory of Tours.pdf](https://github.com/user-attachments/files/18259444/The.History.of.the.Franks.by.Gregory.of.Tours.pdf)

**Comment by stefan6419846** [comment]
Most of the values seem to originate from the regular metadata:

```
>>> from pypdf import PdfReader
>>> reader = PdfReader('The.History.of.the.Franks.by.Gregory.of.Tours.pdf')
>>> reader.metadata
{'/Author': 'Gregory of Tours', '/CreationDate': "D:20241225163028+00'00'", '/Creator': 'calibre 7.23.0', '/Keywords': 'Medieval Library', '/ModDate': "D:20241225163028+00'00'", '/Producer': 'calibre 7.23.0', '/Title': 'The History of the Franks by Gregory of Tours'}
```

Adobe Acrobat most likely shows them. Regular and (mostly optional) XMP metadata might differ and are generated by the PDF creator, thus we have no control over them and who assigns which value where and whether it makes sense.

For me, this is no issue for *pypdf*.

**Comment by pubpub-zz** [comment]
you have to not mix up /metadata and /info
![image](https://github.com/user-attachments/assets/88cadcf5-526c-4b3e-b8f5-44d65163c597)

Most probably acrobat reader has used description from the xml metadata as no subject is avaible in info

**Comment by dfkettle** [comment]
As I said, I'm not saying there is any problem with pypdf. I just find the terminology in the documentation a little confusing, as it seems to differ from Adobe's terminology, as far as "subject" and "keywords" (Adobe's terminology) are concerned.

I'm not really very familiar with the internal structures of PDF files, or the difference between "metadata" and "info". Nor am I familiar with how Acrobat works or where it pulls the data from. I'm just trying to develop a program in Python to display and edit these fields. I just have the free version of Adobe Acrobat, so all I can do is display them. I've tried using Calibre (https://www.calibre-ebook.com/) to do this, but I find it a little confusing.

Anyway, thanks for your help.

**Comment by stefan6419846** [comment]
As already mentioned: The XMP metadata looks wrong (id est it uses the wrong fields leading to your confusion) as generated by Delphi Classics (or whoever created this PDF file).

**Comment by dfkettle** [comment]
And like I said, the metadata provided by the publisher,Delphi Classics (https://www.delphiclassics.com/), is nonsense. That's why I wanted to update it. But that's not the cause of my confusion. My confusion is probably just a result of my lack of knowledge about the internal structure of PDF files. Although I am using Calibre to convert epub files (the format used by the publisher) to pdf files. Maybe it's possible that Calibre is scrambling some of the data, although it has a fairly large user base, so I think that's unlikely.
