### ISSUE TITLE
PdfReadError: EOF marker not found 

### ISSUE THREAD

**Issue by nishantvarma** [py-pdf/pypdf#34]
We are getting error like PdfReadError: EOF marker not found . 

Scenario: We concatenate some PDF's using pyPDF - input can be princeXML supplied PDF , normal PDF etc .
No issues here .  

princeXML PDF + Adobe PDF = pyPDF generated Concatendated PDF - Cool works fine . 

Issue happens we we now use the above type of pyPDF concated pdf  and concat with other normal pdf again using pyPDF itself . 

princeXML PDF + some pyPDF generated PDF = pyPDF generated Concatendated PDF (Expected) works in most cases  some cases this won't work . It basically complaints that the pyPDF generated PDF EOF marker not found ! However it was generated by pyPDF itself , did pyPDF miss putting EOF marker in some strange cases ? 

Can anyone look at this bug ? This has happened quite rarely but some online sites are handling this same pdf pretty well . How can I attach the PDF to Github for inspection ? 

A relevant question can be seen here : 
http://stackoverflow.com/questions/15177587/merge-non-standard-pdfs-with-pypdf

**Comment by umapathireddy** [comment]
sorry for late response, thank you to all

**Comment by AvlWx2014** [comment]
Just ran in to this issue with `PyPDF2 1.26.0` using `Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32`. Was able to bypass by opening each PDF page in Adobe Reader DC, then saving with a new filename. Program worked fine after that.

I was using the library to merge individual pages from a homework assignment written on notebook paper that I scanned page-by-page using the Android Microsoft Lens app. Encountered the error, ended up in this thread, attempted solution above, succeeded.
