### ISSUE TITLE
Named Destinations are going corrupt in output pdf

### ISSUE THREAD

**Issue by icosaeder** [py-pdf/pypdf#370]
It seems "Named Destinations" gonna break.

## Generate Source PDF

I'm using pdf generated by `pdflatex` with cross-refs inside. Here is the tex-file I use: 

```tex
\documentclass[a4paper]{article}
\usepackage{hyperref}
\newcounter{cnt}

\begin{document}

\par Alpha -- \pageref{a}
\par Beta -- \pageref{b}
\par Gamma -- \pageref{c}

\newpage
Alpha Page \refstepcounter{cnt}\label{a}
\newpage
Beta Page \refstepcounter{cnt}\label{b}
\newpage
Gamma Page \refstepcounter{cnt}\label{c}

\end{document}
```

And here is the `input.pdf` generated by `pdflatex`: [input.pdf](https://github.com/mstamy2/PyPDF2/files/1259416/input.pdf)
You can click on the numbers and go to the corresponding page, everything's fine.

## MCVE: PDF + Code

Next, I use the following python code:

```python
import PyPDF2

reader = PyPDF2.PdfFileReader(open("input.pdf", "rb"))
writer = PyPDF2.PdfFileWriter()

# Transfer pages
for page in reader.pages:
    writer.addPage(page)

# Transfer named destinations -- am I missing something?
for nd in reader.namedDestinations:
    print(nd)
    writer.addNamedDestinationObject(reader.namedDestinations[nd])

outputStream = open("output.pdf", "wb")
writer.write(outputStream)
outputStream.close()
```

## The Problem

I get the following output: [output.pdf](https://github.com/mstamy2/PyPDF2/files/1259415/output.pdf)

As you can see, links to pages 2 and 3 stop working, however, the last one works.

I tested this with different LaTeX-generated documents and the named destinations seem to break randomly (some of them survive, but the most fail). This issue is both for python 2 and 3.

**Comment by polymesh** [comment]
I'm having the same issue. This is the primary reason I'd like to use this module, but I can't seem to write destinations and then read the file and get destinations:

```
inputPdf = PdfFileReader("input.pdf")
outputPdf = PdfFileWriter()
for page in p.pages:
    outputPdf.addPage(page)

outputPdf.addNamedDestination(NameObject("Hello"), NumberObject(4))

outFile = file("output.pdf", "wb")
outputPdf.write(outFile)
outFile.close()

reopenedPdf = PdfFileReader("output.pdf")
print(reopenedPdf.getNamedDestinations())
```

I get an exception:

```
Traceback (most recent call last):
  File "C:\test.py", line 76, in <module>
    print(p2.getNamedDestinations())
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1304, in getNamedDestinations
    tree = names['/Dests']
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 518, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 178, in getObject
    return self.pdf.getObject(self).getObject()
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1611, in getObject
    retval = readObject(self.stream, self)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 581, in readFromStream
    value = readObject(stream, pdf)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 71, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 166, in readFromStream
    arr.append(readObject(stream, pdf))
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 98, in readObject
    return NumberObject.readFromStream(stream)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 275, in readFromStream
    return NumberObject(num)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 257, in __new__
    val = int(value)
ValueError: invalid literal for int() with base 10: ''
```

Looks like it is getting an empty string where it expects a number. Which makes me thing streaming out destination objects is broken.

Any help appreciated! Really hoping to use this module.

**Comment by polymesh** [comment]
I figured out what I was doing wrong. When I changed:
`outputPdf.addNamedDestination(NameObject("Hello"), NumberObject(4))`
to:
`outputPdf.addNamedDestination(TextStringObject("Hello"), NumberObject(4))`

I can now reload and query without crashing. Also tested that the destination worked. Probably doesn't solve what you are experiencing, but figured I would post anyway.

**Comment by polymesh** [comment]
Okay, so now that I've been able to get things working and I've added more than one destination, I can confirm - only one of them works. In my case it is the first one in the list when calling getNamedDestinations(). So the destinations seem to be getting into the output pdf, but there is something missing that allows all of them to work.

**Comment by polymesh** [comment]
A little closer to understanding the bug. If I change the names of my bookmarks to "Hello1", "Hello2", "Hello3", etc, those bookmarks work. However once I get to "Hello10" it fails. My guess is that "Hello1" and "Hello10" have the same starting string, though I have no idea why that would cause an issue.

To prove this theory, I changed my names to Hello0001 (added padding,) and this indeed caused all my named destinations to work. However, does that mean I'm stuck with named destinations with numbers and padding? Currently I am trying to use hashes for names since I am dynamically generating content and using hash names to reference them. The large hashes don't seem to work at all, not totally sure why. I don't see how padding is any different than random numbers/letters.

Hopefully someone in the know can chime in??

**Comment by polymesh** [comment]
Likewise, 0001_HASHNAME seems to work.

**Comment by SundeepPidugu** [comment]
How do i change the Text `Alpha – 2` to something like Alpha and assign the same destination for the text ? @polymesh

**Comment by pubpub-zz** [comment]
@MartinThoma 
I propose to close this issue as obsolete : It is dealing with a too old version
your opinion?

**Comment by MartinThoma** [comment]
I agree.

If anybody faces this problem, please add a comment with your pypdf version
