### ISSUE TITLE
Repeated merging does not transfer bookmarks

### ISSUE THREAD

**Issue by pjbulls** [py-pdf/pypdf#450]
I have to merge several PDFs into combined files, and then combine those files again into one big PDF (I need both the big file and the in-between combined files). Also, I need a bookmark for each file, while retaining any preexisting bookmarks:

```python
from PyPDF2 import PdfFileMerger

pdf1 = ["test1.pdf", "test2.pdf"]
pdf2 = ["test3.pdf", "test4.pdf"]

def pdf_cat(input, output):
	merger = PdfFileMerger()
	for pdf in input:
		merger.append(pdf, bookmark=pdf, import_bookmarks=True)
	merger.write(output)

pdf_cat(pdf1, "merge1.pdf")
pdf_cat(pdf2, "merge2.pdf")

pdf3 = ["merge1.pdf", "merge2.pdf"]

pdf_cat(pdf3, "mergeALL.pdf")
```

The first files contain all bookmarks including those on the source files, e.g.:

```
test1
   bookmark
   bookmark
test2
   bookmark
```

However, the final file only contains the top-level bookmarks, and not those in parenthesis:

```
merge1
   (test1)
      (bookmark)
      (bookmark)
   (...)
merge2
```

If I perform the second step using Adobe Acrobat Pro all bookmarks are recovered, so from my initial testing it appears this issue is limited to the importing of bookmarks set by PyPDF2 itself. They can also be read from the intermediary files with a PdfFileReader, but they are not transferred into the new output.

EDIT: I've digged around a bit (not particularly experienced), but I think the source of this issue is in the _trim_outline method of PdfFileMerger. Commenting out line 152 in merger.py stops this behavior from happening.

**Comment by DmitriySelischev** [comment]
Got the same issue.
The workaround that I found:
```python
merger = PdfFileMerger()
reader = PdfFileReader(pdf)
outlines = reader.getOutlines()
merger.append(pdf)
merger.bookmarks = outlines
```

**Comment by pubpub-zz** [comment]
All,
pypdf have been upgraded, recommanding to use `PdfWriter` instead of `PdfMerger`. The `append()` function has been upgraded. Can some on retest and upgrade status

**Comment by pubpub-zz** [comment]
I close this issue as fixed as old and with no rescent update. also many other issues were dealing with merging.
