### ISSUE TITLE
Multiple definitions in dictionary error

### ISSUE THREAD

**Issue by alisufian** [py-pdf/pypdf#46]
Getting a Multiple definitions in dictionary at byte 0x3ee546 for key /CPUCstFn1 for file
http://docs.cpuc.ca.gov/PublishedDocs/Efile/G000/M075/K768/75768464.PDF
when doing reader.getPage()
The file opens without an issue in Foxit.

**Comment by LFBJC** [comment]
I'm getting the same error for some pdf files (I can't share them as they are confidential data) I have to use strict=False on the pdf reader object and yet it raises a warning. Could you please clarify what does this error mean?
