### ISSUE TITLE
Can not see Form PDF data

### ISSUE THREAD

**Issue by shubhpy** [py-pdf/pypdf#481]
Hey,

https://s3.ap-south-1.amazonaws.com/public-sharing-purpose/aoc_gooded_tech.pdf

I have been trying since a long time to read the data inside this PDF with any python library.
Somehow I landed here.

I tried opening this PDF but can not see the data.

History:
So when I open this PDF in Adobe Acrobat Reader, I see security warning of if you trust ... site and it asks to either allow or block. When I allow I can see the data.
But when I open it in Preview(Mac), It doesn't ask anything and shows data.

When I passed this PDF to any Python Library (PyPDF2, tabula, PyMuPDF, pdfminer), I didn't see the data but only fields.

One day, I opened it in Preview(Mac) and exported as PDF.
And Voila It was working and libraries were able to read full data.

Can anyone help me how can I see the full data in python?
Thanks

**Comment by chiencarlos11** [comment]
I'm having the same issue. i was able to get around by opening the PDF with chrome then print as PDF. this is the form im having problem with

https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/forms/pdf/pptc153.pdf

**Comment by admin-codecycle** [comment]
Hi @shubhpy and @chiencarlos11.

I was having a similar problem. Then a colleague pointed out that flattening the PDF's could help. So I used natikinis' solution, here https://stackoverflow.com/questions/27023043/generate-flattened-pdf-with-python.

Now my files can be read on both Acrobat and Preview.

` pagesTotalNumber = len(pagesDictionary['pages'])
        pdf_merger = PdfFileMerger()
        for fileNumber in range(1, pagesTotalNumber + 1):
            # this flattens the PDF
            pypdftk.fill_form(inputFolder + 'pg' + str(fileNumber) + '.pdf', out_file= inputFolder +'flattened' + str(fileNumber)+ '.pdf', flatten=True)
          
            pdf_merger.append(PdfFileReader(inputFolder + 'flattened' + str(fileNumber) + '.pdf', 'rb'))

        pdf_merger.write("./Forms_ca2019/mergedPDFOutput/mergedPDFOutput.pdf")

        # Close the PDF writer
        pdf_merger.close()`

Best,

juancarlucci

**Comment by pubpub-zz** [comment]
@shubhpy  your pdf is no more available => no  analysis is possible
@chiencarlos11 : the pdf is an XFA form (https://en.wikipedia.org/wiki/XFA) the form by its how is like a web page that is dynamically displayed in the viewer. The data can be extracted with `get_fields()`/`get_form_text_fields()` 

This issue can be closed

**Comment by pubpub-zz** [comment]
I close this issue feel free to provide updates to reopen it
