### ISSUE TITLE
Problem with attaching multiple files

### ISSUE THREAD

**Issue by Billie05** [py-pdf/pypdf#527]
When I am trying to attach muliple files to one PDF, it will be just the last one attached, even if I am trying to iterate over the List of attachements.
```
for j in range(1, len(List)):
    fileWriter.addAtachment(List1[j],List[j])
```
Is there any posible Solution to add muliple files to one PDF?

**Comment by MartinThoma** [comment]
Can you make this example complete (hence add missing imports and variable assignments)?

**Comment by Billie05** [comment]
It seems to me like the addAttachment-Method always replaces the current attachment.

`self._root_object.update({
        NameObject("/Names"): embeddedFilesDictionary
        })`

I modified the add function and made this one. It helped me to solve my problem.

`

    def appendAttachment(myPdfFileWriterObj, fname, fdata):
    
        # The entry for the file
        file_entry = DecodedStreamObject()
        file_entry.setData(fdata)
        file_entry.update({NameObject("/Type"): NameObject("/EmbeddedFile")})

        # The Filespec entry
        efEntry = DictionaryObject()
        efEntry.update({ NameObject("/F"):file_entry })

        filespec = DictionaryObject()
        filespec.update({NameObject("/Type"): NameObject("/Filespec"),NameObject("/F"): createStringObject(fname),NameObject("/EF"): efEntry})

        if "/Names" not in myPdfFileWriterObj._root_object.keys():
            # No files attached yet. Create the entry for the root, as it needs a reference to the Filespec
            embeddedFilesNamesDictionary = DictionaryObject()
            embeddedFilesNamesDictionary.update({NameObject("/Names"): ArrayObject([createStringObject(fname), filespec])})

            embeddedFilesDictionary = DictionaryObject()
            embeddedFilesDictionary.update({NameObject("/EmbeddedFiles"): embeddedFilesNamesDictionary})
            myPdfFileWriterObj._root_object.update({NameObject("/Names"): embeddedFilesDictionary})
        else:
            # There are files already attached. Append the new file.
            myPdfFileWriterObj._root_object["/Names"]["/EmbeddedFiles"]["/Names"].append(createStringObject(fname))
            myPdfFileWriterObj._root_object["/Names"]["/EmbeddedFiles"]["/Names"].append(filespec)
`

**Comment by MartinThoma** [comment]
What do you think about making this a PR?

Why did you close this issue? I think it's pretty likely that this is a bug we want to fix in PyPDF2

**Comment by Billie05** [comment]
Sorry, I just wanted to comment. And yes, that's a great idea. I will try to pack it in PR!

**Comment by MartinThoma** [comment]
@Billie05 How are things going with the PR? Do you need support?
