### ISSUE TITLE
PdfMerger should update FieldName with page index to ensure uniqueness

### ISSUE THREAD

**Issue by leezu** [py-pdf/pypdf#606]
When using `pdftk input1.pdf input2.pdf cat output output.pdf` to concatenate two input pdf containing the same AcroForm form fields (ie. to separately saved variants of the same pdf with different values entered into the form fields), pdftk will prepend the document index to the form field name. PdfFileMerger does not do this.

This can lead to serious problems when viewing the resulting PDF. For example, the [Master PDF Editor](https://code-industry.net/masterpdfeditor/) will display the form data from the input2.pdf on all pages of the concatenated document, instead of displaying first input1.pdf followed by the pages of input2.pdf.

**Comment by MartinThoma** [comment]
Do you have an example PDF + (PyPDF2) code that shows the issue?

**Comment by pubpub-zz** [comment]
@leezu 
PR #1553 that has just been released in 3.4.0 
you should have a look in the documentation : https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html#merging-forms

**Comment by pubpub-zz** [comment]
I close this issue as fixed. feel free to reopen it
