### ISSUE TITLE
ENH: Modify page attributes that depend on page orientation after rotating page

### ISSUE THREAD

**Issue by thommiano** [py-pdf/pypdf#633]
Rotating a page, e.g., using `page.RotateClockwise()` only updates the `/Rotate` attribute:

```python
def rotateClockwise(self, angle):
        """
        Rotates a page clockwise by increments of 90 degrees.

        :param int angle: Angle to rotate the page.  Must be an increment
            of 90 deg.
        """
        assert angle % 90 == 0
        self._rotate(angle)
        return self

def rotateCounterClockwise(self, angle):
        """
        Rotates a page counter-clockwise by increments of 90 degrees.

        :param int angle: Angle to rotate the page.  Must be an increment
            of 90 deg.
        """
        assert angle % 90 == 0
        self._rotate(-angle)
        return self

def _rotate(self, angle):
        currentAngle = self.get("/Rotate", 0)
        self[NameObject("/Rotate")] = NumberObject(currentAngle + angle)
```     

The expected behavior is that other attributes that depend on a page's origin should also be updated based on rotation. For example:

- `/mediaBox` - The x, y dimensions of the page. If the page is rotated 90 degrees, the values in the mediaBox should swap places
- `/Annots`...`/Rect` - The coordinates of a rectangular bounding box for an annotation. These coordinates are [x0, y0, x1, y1], with the origin being at the bottom left of the page. If the page is rotated, the origin with respect to the annotations according from the users perspective has changed and so should the coordinates.

## Notes

I created this issue to capture a more general issue that is happening in more specific cases that haven't been resolved:

- https://github.com/mstamy2/PyPDF2/issues/525#issue-529556145
- https://github.com/mstamy2/PyPDF2/issues/558#issue-629515115

**Comment by thommiano** [comment]
What I find most confusing is that `/Rotation` doesn't update, given:

```python
def rotateClockwise(self, angle):
        """
        Rotates a page clockwise by increments of 90 degrees.

        :param int angle: Angle to rotate the page.  Must be an increment
            of 90 deg.
        """
        assert angle % 90 == 0
        self._rotate(angle)
        return self

def _rotate(self, angle):
        currentAngle = self.get("/Rotate", 0)
        self[NameObject("/Rotate")] = NumberObject(currentAngle + angle)
```

It seems like calling `.rotateClockwise()` should change the page `/Rotation` to some value other than `None`.

**Comment by thommiano** [comment]
Just realized that I was using `/Rotation` instead of `/Rotate` above... Re-testing, then will update above.

**Comment by thommiano** [comment]
This can be used to rotate the `/Annots` `/Rect`:
```python
def rotate_coordinates(coordinates: Tuple[float], degrees: int) -> Tuple[float]:
    def rotate_left(coordinates, start_idx):
        # Get new list beginning at start_idx, moving prior indices to end of list
        return coordinates[start_idx:] + coordinates[:start_idx]

    rotation_degrees = degrees % 360  # get position within 360-degrees
    VALID_DEGREES = (0, 90, 180, 270, 360)
    if rotation_degrees not in VALID_DEGREES:
        raise ValueError(f"{degrees} is not a valid option in {VALID_DEGREES}.")

    rotation_idx = VALID_DEGREES.index(rotation_degrees)
    return rotate_left(coordinates, rotation_idx)
```

**Comment by pubpub-zz** [comment]
`transfer_rotation_to_content()` has been developped since. I propose to close this issue
